// ──────────────────────────────────────────────
//  FINA - Gestion de Portefeuille : Quiz Questions
// ──────────────────────────────────────────────

import type { QuizQuestion } from '@/types/content';

export const portfolioQuiz: QuizQuestion[] = [
  // ── Lesson 1 : Rendement & Risque ──
  {
    id: 'portfolio-1-q1',
    lessonId: 'portfolio-1',
    question: 'Comment calcule-t-on le rendement total d\'un investissement ?',
    options: [
      '(P₁ - P₀) / P₀',
      '(P₁ - P₀ + D) / P₀',
      '(P₁ + D) / P₀',
      'D / P₀',
    ],
    correctIndex: 1,
    explanation: 'Le rendement total inclut la plus-value (P₁ - P₀) et les flux intermédiaires (dividendes D), le tout divisé par le prix initial P₀.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-1-q2',
    lessonId: 'portfolio-1',
    question: 'Que mesure la volatilité (écart-type) d\'un actif financier ?',
    options: [
      'Le rendement moyen sur la période',
      'La perte maximale possible',
      'L\'incertitude autour du rendement espéré',
      'Le ratio rendement/risque',
    ],
    correctIndex: 2,
    explanation: 'La volatilité (écart-type σ) mesure la dispersion des rendements autour de la moyenne, quantifiant l\'incertitude associée au rendement futur.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-1-q3',
    lessonId: 'portfolio-1',
    question: 'Quelle est la prime de risque d\'une action rapportant 12 % si le taux sans risque est de 3 % ?',
    options: ['3 %', '9 %', '12 %', '15 %'],
    correctIndex: 1,
    explanation: 'La prime de risque = rendement de l\'actif - taux sans risque = 12 % - 3 % = 9 %.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-1-q4',
    lessonId: 'portfolio-1',
    question: 'Historiquement, la prime de risque des actions par rapport aux obligations d\'État se situe entre :',
    options: ['0 % et 2 %', '2 % et 4 %', '4 % et 7 %', '8 % et 12 %'],
    correctIndex: 2,
    explanation: 'La prime de risque historique des actions se situe entre 4 % et 7 % selon les marchés et les périodes d\'observation.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-1-q5',
    lessonId: 'portfolio-1',
    question: 'Le trade-off rendement-risque implique que :',
    options: [
      'Un rendement élevé garantit un risque faible',
      'Un risque élevé garantit un rendement élevé',
      'Un rendement espéré plus élevé exige un risque plus élevé',
      'Le risque et le rendement sont indépendants',
    ],
    correctIndex: 2,
    explanation: 'Le trade-off signifie qu\'un investisseur rationnel exige un rendement espéré plus élevé pour accepter un risque supplémentaire. Ce n\'est pas une garantie mais une relation d\'équilibre.',
    difficulty: 'easy',
  },

  // ── Lesson 2 : Mesures de risque ──
  {
    id: 'portfolio-2-q1',
    lessonId: 'portfolio-2',
    question: 'Que représente une VaR à 95 % sur un jour de 2 M€ ?',
    options: [
      'On est sûr à 95 % de gagner au moins 2 M€',
      'Il y a 5 % de chances de perdre plus de 2 M€ en un jour',
      'La perte moyenne sera de 2 M€',
      'La perte maximale possible est de 2 M€',
    ],
    correctIndex: 1,
    explanation: 'La VaR à 95 % indique que dans 5 % des cas (les pires scénarios), la perte dépassera 2 M€ sur la période d\'un jour.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-2-q2',
    lessonId: 'portfolio-2',
    question: 'Quelle mesure de risque capture la perte moyenne au-delà de la VaR ?',
    options: ['Le drawdown maximal', 'La CVaR (Expected Shortfall)', 'Le semi-écart-type', 'Le bêta'],
    correctIndex: 1,
    explanation: 'La CVaR (Conditional VaR ou Expected Shortfall) mesure la perte moyenne dans les cas dépassant la VaR, capturant la sévérité des pertes extrêmes.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-2-q3',
    lessonId: 'portfolio-2',
    question: 'Pourquoi le semi-écart-type est-il considéré comme plus pertinent que la volatilité totale ?',
    options: [
      'Il est plus facile à calculer',
      'Il ne considère que la volatilité à la baisse, cohérente avec l\'aversion au risque',
      'Il est plus stable dans le temps',
      'Il capture le risque systématique',
    ],
    correctIndex: 1,
    explanation: 'Le semi-écart-type ne prend en compte que les rendements inférieurs au seuil, ce qui est cohérent avec le fait que les investisseurs souffrent davantage des pertes que des gains.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-2-q4',
    lessonId: 'portfolio-2',
    question: 'Le drawdown maximal du S&P 500 lors de la crise de 2008 a atteint environ :',
    options: ['-25 %', '-35 %', '-56 %', '-75 %'],
    correctIndex: 2,
    explanation: 'Le S&P 500 a chuté d\'environ 56 % entre son pic d\'octobre 2007 et son creux de mars 2009.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-2-q5',
    lessonId: 'portfolio-2',
    question: 'Quel est le principal défaut de la VaR comme mesure de risque ?',
    options: [
      'Elle est trop complexe à calculer',
      'Elle ne dit rien sur l\'ampleur des pertes au-delà du seuil',
      'Elle n\'est applicable qu\'aux actions',
      'Elle ne fonctionne que pour les distributions normales',
    ],
    correctIndex: 1,
    explanation: 'La VaR indique le seuil de perte mais ne précise pas l\'ampleur des pertes dans les cas extrêmes. C\'est pourquoi la CVaR la complète.',
    difficulty: 'medium',
  },

  // ── Lesson 3 : Diversification ──
  {
    id: 'portfolio-3-q1',
    lessonId: 'portfolio-3',
    question: 'La diversification permet d\'éliminer :',
    options: [
      'Le risque systématique uniquement',
      'Le risque spécifique (idiosyncratique) uniquement',
      'Les deux types de risque',
      'Aucun type de risque',
    ],
    correctIndex: 1,
    explanation: 'La diversification élimine le risque spécifique (propre à chaque entreprise) mais pas le risque systématique (risque de marché), qui est incompressible.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-3-q2',
    lessonId: 'portfolio-3',
    question: 'Combien d\'actions faut-il approximativement pour éliminer 90 % du risque spécifique ?',
    options: ['5', '10', '30', '100'],
    correctIndex: 2,
    explanation: 'Les études empiriques montrent qu\'environ 30 actions suffisent pour éliminer environ 90 % du risque spécifique.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-3-q3',
    lessonId: 'portfolio-3',
    question: 'Le phénomène de "correlation breakdown" signifie que :',
    options: [
      'Les corrélations deviennent négatives en période de crise',
      'Les corrélations tendent à augmenter en période de crise, réduisant l\'efficacité de la diversification',
      'Les corrélations disparaissent en période calme',
      'Les corrélations sont toujours constantes',
    ],
    correctIndex: 1,
    explanation: 'En période de crise, les corrélations entre actifs augmentent, réduisant l\'efficacité de la diversification justement quand on en a le plus besoin.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-3-q4',
    lessonId: 'portfolio-3',
    question: 'Quand n actifs équipondérés tendent vers l\'infini, la variance du portefeuille converge vers :',
    options: [
      'Zéro',
      'La variance moyenne',
      'La covariance moyenne',
      'L\'infini',
    ],
    correctIndex: 2,
    explanation: 'La formule σ²_p = σ̄²/n + (n-1)/n × cov̄ montre que quand n → ∞, la variance tend vers la covariance moyenne, qui est le risque systématique incompressible.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-3-q5',
    lessonId: 'portfolio-3',
    question: 'Quel type de diversification ajoute une couche supplémentaire de réduction du risque au-delà de la diversification sectorielle ?',
    options: [
      'La diversification temporelle uniquement',
      'La diversification géographique',
      'L\'augmentation du nombre d\'actions dans le même secteur',
      'L\'utilisation de levier',
    ],
    correctIndex: 1,
    explanation: 'La diversification internationale/géographique ajoute une couche supplémentaire car les cycles économiques ne sont pas parfaitement synchronisés entre pays.',
    difficulty: 'easy',
  },

  // ── Lesson 4 : Corrélation ──
  {
    id: 'portfolio-4-q1',
    lessonId: 'portfolio-4',
    question: 'Un coefficient de corrélation de -1 entre deux actifs signifie :',
    options: [
      'Ils évoluent toujours dans le même sens',
      'Ils n\'ont aucune relation',
      'Ils évoluent toujours en sens opposé (opposition parfaite)',
      'L\'un est plus risqué que l\'autre',
    ],
    correctIndex: 2,
    explanation: 'ρ = -1 signifie une opposition parfaite : quand un actif monte, l\'autre baisse proportionnellement, et inversement.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-4-q2',
    lessonId: 'portfolio-4',
    question: 'Depuis les années 2000, la corrélation entre actions et obligations a été :',
    options: [
      'Fortement positive (+0,8)',
      'Majoritairement négative',
      'Exactement zéro',
      'Toujours égale à +1',
    ],
    correctIndex: 1,
    explanation: 'Depuis les années 2000, la corrélation actions-obligations est devenue majoritairement négative, renforçant le rôle diversifiant des obligations.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-4-q3',
    lessonId: 'portfolio-4',
    question: 'La matrice de variance-covariance d\'un portefeuille de n actifs contient combien de paramètres ?',
    options: ['n', 'n²', 'n(n+1)/2', '2n'],
    correctIndex: 2,
    explanation: 'La matrice est symétrique, donc elle contient n variances sur la diagonale et n(n-1)/2 covariances distinctes, soit n(n+1)/2 paramètres au total.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-4-q4',
    lessonId: 'portfolio-4',
    question: 'Le shrinkage de Ledoit-Wolf est utilisé pour :',
    options: [
      'Augmenter le nombre d\'actifs dans le portefeuille',
      'Obtenir des estimations plus robustes de la matrice de covariance',
      'Calculer le rendement espéré',
      'Déterminer le taux sans risque',
    ],
    correctIndex: 1,
    explanation: 'Le shrinkage de Ledoit-Wolf est une technique statistique qui combine l\'estimation historique bruitée avec une structure cible pour obtenir une matrice de covariance plus robuste.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-4-q5',
    lessonId: 'portfolio-4',
    question: 'La formule de la variance d\'un portefeuille en notation matricielle est :',
    options: ['σ²_p = w × Σ', 'σ²_p = w\'Σw', 'σ²_p = Σw²', 'σ²_p = w\'w'],
    correctIndex: 1,
    explanation: 'σ²_p = w\'Σw, où w est le vecteur des poids et Σ la matrice de variance-covariance. C\'est une forme quadratique.',
    difficulty: 'medium',
  },

  // ── Lesson 5 : Markowitz ──
  {
    id: 'portfolio-5-q1',
    lessonId: 'portfolio-5',
    question: 'Quelle est l\'innovation principale de Markowitz (1952) ?',
    options: [
      'La découverte du bêta',
      'L\'optimisation du portefeuille en considérant le risque global et non les actifs individuellement',
      'La création des ETF',
      'Le modèle Black-Scholes',
    ],
    correctIndex: 1,
    explanation: 'Markowitz a montré qu\'un investisseur rationnel doit considérer le portefeuille dans son ensemble car ce qui compte est la contribution de chaque actif au risque total du portefeuille.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-5-q2',
    lessonId: 'portfolio-5',
    question: 'Le portefeuille de variance minimale est :',
    options: [
      'Le portefeuille avec le rendement le plus élevé',
      'Le point le plus à gauche de la frontière efficiente',
      'Le portefeuille composé uniquement de l\'actif sans risque',
      'Le portefeuille de marché',
    ],
    correctIndex: 1,
    explanation: 'Le portefeuille de variance minimale offre le risque le plus faible possible parmi toutes les combinaisons d\'actifs risqués. Il se situe au point le plus à gauche de la frontière.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-5-q3',
    lessonId: 'portfolio-5',
    question: 'Le problème d\'optimisation de Markowitz est :',
    options: [
      'Un programme linéaire',
      'Un programme quadratique sous contraintes',
      'Un problème non résolvable',
      'Une simple moyenne pondérée',
    ],
    correctIndex: 1,
    explanation: 'Le problème minimise σ²_p = w\'Σw (quadratique en w) sous des contraintes linéaires (somme des poids = 1, rendement cible).',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-5-q4',
    lessonId: 'portfolio-5',
    question: 'Quel est le principal problème pratique de l\'optimisation de Markowitz ?',
    options: [
      'Elle ne fonctionne qu\'avec 2 actifs',
      'La sensibilité aux estimations des rendements espérés',
      'Elle ignore les corrélations',
      'Elle ne peut pas être résolue par ordinateur',
    ],
    correctIndex: 1,
    explanation: 'Les poids optimaux sont très sensibles aux estimations des rendements espérés. De petites variations dans les inputs produisent des portefeuilles radicalement différents.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-5-q5',
    lessonId: 'portfolio-5',
    question: 'Pour corriger l\'instabilité de Markowitz, on peut utiliser :',
    options: [
      'Uniquement le CAPM',
      'Le modèle Black-Litterman ou le resampling de Michaud',
      'La règle de Taylor',
      'Le ratio de Sharpe uniquement',
    ],
    correctIndex: 1,
    explanation: 'Black-Litterman intègre un prior de marché et les vues de l\'investisseur. Michaud utilise le resampling (bootstrap) pour obtenir des portefeuilles plus robustes.',
    difficulty: 'hard',
  },

  // ── Lesson 6 : Frontière efficiente ──
  {
    id: 'portfolio-6-q1',
    lessonId: 'portfolio-6',
    question: 'La frontière efficiente est :',
    options: [
      'L\'ensemble de tous les portefeuilles possibles',
      'La partie supérieure de la parabole offrant le rendement maximal pour chaque niveau de risque',
      'Une droite horizontale',
      'Le portefeuille de marché uniquement',
    ],
    correctIndex: 1,
    explanation: 'La frontière efficiente est le bord supérieur gauche de l\'ensemble des portefeuilles possibles : chaque point offre le rendement maximal pour un niveau de risque donné.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-6-q2',
    lessonId: 'portfolio-6',
    question: 'L\'ajout d\'un actif sans risque transforme la frontière efficiente en :',
    options: [
      'Une courbe plus prononcée',
      'Un cercle',
      'Une droite (Capital Market Line)',
      'Un point unique',
    ],
    correctIndex: 2,
    explanation: 'L\'introduction d\'un actif sans risque permet de tracer une droite tangente à la frontière, la Capital Market Line (CML), qui domine la frontière courbe.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-6-q3',
    lessonId: 'portfolio-6',
    question: 'Le théorème de séparation de Tobin affirme que :',
    options: [
      'Il faut séparer les actions des obligations',
      'Tous les investisseurs détiennent le même portefeuille risqué (tangent) et ajustent le ratio risqué/sans risque',
      'Les décisions d\'investissement sont indépendantes du risque',
      'On ne peut pas combiner actifs risqués et sans risque',
    ],
    correctIndex: 1,
    explanation: 'Tobin montre que la décision se décompose en deux : identifier le portefeuille tangent (identique pour tous) puis choisir la proportion avec l\'actif sans risque (selon l\'aversion au risque).',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-6-q4',
    lessonId: 'portfolio-6',
    question: 'Avec deux actifs et une corrélation de -1, il est théoriquement possible de :',
    options: [
      'Doubler le rendement',
      'Créer un portefeuille sans risque',
      'Éliminer le risque systématique',
      'Rien de spécial',
    ],
    correctIndex: 1,
    explanation: 'Avec ρ = -1, les mouvements s\'annulent parfaitement. On peut trouver des poids tels que la volatilité du portefeuille est nulle.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-6-q5',
    lessonId: 'portfolio-6',
    question: 'La pente de la CML est égale à :',
    options: [
      'Le taux sans risque',
      'Le bêta du marché',
      '(E[R_M] - r_f) / σ_M, soit le ratio de Sharpe du marché',
      'La volatilité du marché',
    ],
    correctIndex: 2,
    explanation: 'La pente de la CML est le ratio de Sharpe du portefeuille de marché : le rendement excédentaire par unité de risque total.',
    difficulty: 'medium',
  },

  // ── Lesson 7 : Portefeuille tangent ──
  {
    id: 'portfolio-7-q1',
    lessonId: 'portfolio-7',
    question: 'Le portefeuille tangent maximise :',
    options: ['Le rendement absolu', 'Le ratio de Sharpe', 'La volatilité', 'Le bêta'],
    correctIndex: 1,
    explanation: 'Le portefeuille tangent est le point de tangence entre la CML et la frontière efficiente, et il maximise le ratio de Sharpe parmi tous les portefeuilles risqués.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-7-q2',
    lessonId: 'portfolio-7',
    question: 'Un investisseur agressif utilisant le portefeuille tangent va :',
    options: [
      'N\'investir que dans l\'actif sans risque',
      'Investir 100 % dans le tangent sans levier',
      'Emprunter au taux sans risque pour investir plus de 100 % dans le tangent',
      'Ignorer le portefeuille tangent',
    ],
    correctIndex: 2,
    explanation: 'Un investisseur agressif emprunte au taux sans risque pour investir plus de 100 % dans le portefeuille tangent, se plaçant au-delà du point de tangence sur la CML.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-7-q3',
    lessonId: 'portfolio-7',
    question: 'Le problème de l\'"error maximization" (Michaud) signifie que :',
    options: [
      'L\'optimisation est trop simple',
      'Le portefeuille tangent est toujours optimal en pratique',
      'L\'optimisation surpondère les actifs dont les rendements sont surestimés par erreur',
      'Le taux sans risque est mal estimé',
    ],
    correctIndex: 2,
    explanation: 'L\'optimisation de Markowitz amplifie les erreurs d\'estimation : elle surpondère les actifs avec les rendements les plus surestimés et les risques les plus sous-estimés.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-7-q4',
    lessonId: 'portfolio-7',
    question: 'Dans le CAPM, le portefeuille tangent correspond à :',
    options: [
      'L\'actif sans risque',
      'Le portefeuille de variance minimale',
      'Le portefeuille de marché',
      'Un portefeuille équipondéré',
    ],
    correctIndex: 2,
    explanation: 'Dans le cadre du CAPM, en équilibre, le portefeuille tangent est le portefeuille de marché, pondéré par les capitalisations boursières.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-7-q5',
    lessonId: 'portfolio-7',
    question: 'La solution analytique du portefeuille tangent fait intervenir :',
    options: [
      'Uniquement les rendements espérés',
      'L\'inverse de la matrice de covariance Σ⁻¹',
      'Le taux d\'inflation',
      'Le PIB nominal',
    ],
    correctIndex: 1,
    explanation: 'w* = Σ⁻¹(μ - r_f·1) / 1\'Σ⁻¹(μ - r_f·1). L\'inverse de la matrice de covariance est central dans la solution.',
    difficulty: 'hard',
  },

  // ── Lesson 8 : CAPM principes ──
  {
    id: 'portfolio-8-q1',
    lessonId: 'portfolio-8',
    question: 'Selon le CAPM, le seul risque rémunéré est :',
    options: [
      'Le risque total (volatilité)',
      'Le risque spécifique',
      'Le risque systématique (bêta)',
      'Le risque de liquidité',
    ],
    correctIndex: 2,
    explanation: 'Le CAPM postule que seul le risque systématique (non diversifiable), mesuré par le bêta, est rémunéré par une prime de risque.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-8-q2',
    lessonId: 'portfolio-8',
    question: 'Un bêta de 1,5 signifie que :',
    options: [
      'L\'actif est 50 % moins risqué que le marché',
      'L\'actif amplifie les mouvements du marché de 50 %',
      'L\'actif a un rendement garanti de 150 %',
      'L\'actif n\'est pas corrélé au marché',
    ],
    correctIndex: 1,
    explanation: 'Un bêta de 1,5 signifie que quand le marché monte de 1 %, l\'actif monte en moyenne de 1,5 %, et inversement à la baisse.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-8-q3',
    lessonId: 'portfolio-8',
    question: 'Avec r_f = 3 %, β = 1,2 et E[R_M] = 9 %, le rendement espéré selon le CAPM est :',
    options: ['9 %', '10,2 %', '10,8 %', '13,8 %'],
    correctIndex: 1,
    explanation: 'E[R] = r_f + β × (E[R_M] - r_f) = 3 % + 1,2 × (9 % - 3 %) = 3 % + 7,2 % = 10,2 %.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-8-q4',
    lessonId: 'portfolio-8',
    question: 'Parmi les hypothèses du CAPM, on trouve :',
    options: [
      'Des marchés imparfaits avec coûts de transaction',
      'Des investisseurs avec des horizons différents',
      'Des anticipations homogènes et des marchés parfaits',
      'L\'interdiction de la vente à découvert',
    ],
    correctIndex: 2,
    explanation: 'Le CAPM suppose des marchés parfaits, des anticipations homogènes, un emprunt illimité au taux sans risque et un horizon identique pour tous.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-8-q5',
    lessonId: 'portfolio-8',
    question: 'Le bêta se calcule par la formule :',
    options: [
      'β = σ_i / σ_M',
      'β = Cov(R_i, R_M) / Var(R_M)',
      'β = Var(R_i) / Cov(R_i, R_M)',
      'β = E[R_i] / E[R_M]',
    ],
    correctIndex: 1,
    explanation: 'β = Cov(R_i, R_M) / Var(R_M). C\'est le rapport de la covariance de l\'actif avec le marché sur la variance du marché.',
    difficulty: 'medium',
  },

  // ── Lesson 9 : CAPM applications ──
  {
    id: 'portfolio-9-q1',
    lessonId: 'portfolio-9',
    question: 'Le CAPM est principalement utilisé pour estimer :',
    options: [
      'Le taux d\'inflation',
      'Le coût des fonds propres (Ke) dans le WACC',
      'Le taux de change',
      'Le PIB futur',
    ],
    correctIndex: 1,
    explanation: 'L\'application la plus courante du CAPM est l\'estimation du coût des fonds propres : Ke = r_f + β × ERP, utilisé comme taux d\'actualisation dans le DCF.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-9-q2',
    lessonId: 'portfolio-9',
    question: 'Le bêta ajusté de Bloomberg est calculé comme :',
    options: [
      'β_adj = β_brut × 2',
      'β_adj = 0,67 × β_brut + 0,33',
      'β_adj = β_brut - 0,33',
      'β_adj = 1 / β_brut',
    ],
    correctIndex: 1,
    explanation: 'L\'ajustement de Blume/Bloomberg suppose une convergence vers 1 : β_adj = 0,67 × β_brut + 0,33 × 1.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-9-q3',
    lessonId: 'portfolio-9',
    question: 'Pour comparer les bêtas d\'entreprises à structures financières différentes, on utilise :',
    options: [
      'Le bêta brut',
      'Le bêta ajusté Bloomberg',
      'Le bêta unlevered (désendetté)',
      'Le bêta du marché',
    ],
    correctIndex: 2,
    explanation: 'Le bêta unlevered (β_u = β_L / [1 + (1-t) × D/E]) neutralise l\'effet de levier financier pour comparer le risque opérationnel pur.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-9-q4',
    lessonId: 'portfolio-9',
    question: 'L\'alpha de Jensen mesure :',
    options: [
      'La volatilité du portefeuille',
      'Le rendement excédentaire par rapport au rendement prédit par le CAPM',
      'Le risque systématique',
      'Le taux sans risque',
    ],
    correctIndex: 1,
    explanation: 'α = R_i - [r_f + β × (R_M - r_f)]. Un alpha positif indique que le gérant a surperformé ce que le CAPM prédisait pour son niveau de risque systématique.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-9-q5',
    lessonId: 'portfolio-9',
    question: 'Avec β = 0,95, r_f = 3 %, ERP = 5,5 %, le Ke est :',
    options: ['5,5 %', '7,73 %', '8,23 %', '8,95 %'],
    correctIndex: 2,
    explanation: 'Ke = 3 % + 0,95 × 5,5 % = 3 % + 5,225 % = 8,225 % ≈ 8,23 %.',
    difficulty: 'easy',
  },

  // ── Lesson 10 : SML ──
  {
    id: 'portfolio-10-q1',
    lessonId: 'portfolio-10',
    question: 'La SML (Security Market Line) trace la relation entre :',
    options: [
      'Le rendement et la volatilité totale',
      'Le rendement espéré et le bêta',
      'Le rendement et le temps',
      'La volatilité et le bêta',
    ],
    correctIndex: 1,
    explanation: 'La SML représente E[R_i] = r_f + β_i × (E[R_M] - r_f) dans l\'espace (β, rendement espéré).',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-10-q2',
    lessonId: 'portfolio-10',
    question: 'Un actif situé AU-DESSUS de la SML est :',
    options: [
      'Surévalué (alpha négatif)',
      'Sous-évalué (alpha positif)',
      'Correctement évalué',
      'Sans risque',
    ],
    correctIndex: 1,
    explanation: 'Au-dessus de la SML, le rendement est supérieur à ce que le CAPM prédit : l\'actif offre plus que ce que son risque justifie, il est donc sous-évalué.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-10-q3',
    lessonId: 'portfolio-10',
    question: 'La pente de la SML est :',
    options: [
      'Le taux sans risque',
      'Le bêta du marché',
      'La prime de risque du marché (E[R_M] - r_f)',
      'La volatilité du marché',
    ],
    correctIndex: 2,
    explanation: 'La pente de la SML est la prime de risque du marché, soit E[R_M] - r_f.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-10-q4',
    lessonId: 'portfolio-10',
    question: 'La différence fondamentale entre CML et SML est :',
    options: [
      'Il n\'y a aucune différence',
      'La CML utilise σ (risque total) et concerne les portefeuilles efficients ; la SML utilise β (risque systématique) et concerne tous les actifs',
      'La SML est une courbe et la CML une droite',
      'La CML inclut l\'actif sans risque et la SML non',
    ],
    correctIndex: 1,
    explanation: 'La CML est dans l\'espace (σ, E[R]) pour les portefeuilles efficients. La SML est dans l\'espace (β, E[R]) pour tout actif ou portefeuille.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-10-q5',
    lessonId: 'portfolio-10',
    question: 'En équilibre CAPM, où se situent tous les actifs ?',
    options: [
      'Au-dessus de la SML',
      'En dessous de la SML',
      'Exactement sur la SML',
      'Sur la CML',
    ],
    correctIndex: 2,
    explanation: 'En équilibre, tous les actifs se situent exactement sur la SML. Les écarts sont temporaires et s\'autocorrigent par l\'offre et la demande.',
    difficulty: 'easy',
  },

  // ── Lesson 11 : Alpha & Beta ──
  {
    id: 'portfolio-11-q1',
    lessonId: 'portfolio-11',
    question: 'Dans le modèle de marché R_i = α + β × R_M + ε, le R² mesure :',
    options: [
      'Le rendement total',
      'La proportion du risque total expliquée par le marché',
      'Le bêta de l\'actif',
      'L\'alpha du gérant',
    ],
    correctIndex: 1,
    explanation: 'Le R² indique la part de la variance des rendements de l\'actif expliquée par les mouvements du marché. Un R² de 0,45 signifie que 45 % du risque est systématique.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-11-q2',
    lessonId: 'portfolio-11',
    question: 'Un fonds avec un rendement de 14 %, β = 1,2, R_M = 10 %, r_f = 2 % a un alpha de Jensen de :',
    options: ['2 %', '2,4 %', '4 %', '12 %'],
    correctIndex: 1,
    explanation: 'α = 14 % - [2 % + 1,2 × (10 % - 2 %)] = 14 % - [2 % + 9,6 %] = 14 % - 11,6 % = 2,4 %.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-11-q3',
    lessonId: 'portfolio-11',
    question: 'Selon les études (Fama & French, 2010), la majorité des gérants actifs :',
    options: [
      'Génèrent un alpha positif significatif',
      'Battent systématiquement leur indice',
      'Ont une distribution d\'alphas nets de frais légèrement négative',
      'N\'ont pas de bêta mesurable',
    ],
    correctIndex: 2,
    explanation: 'Après frais, la distribution des alphas est centrée légèrement en dessous de zéro. La majorité des gérants actifs sous-performent leur benchmark net de frais.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-11-q4',
    lessonId: 'portfolio-11',
    question: 'Pour qu\'un alpha de Jensen soit considéré comme statistiquement significatif, il faut :',
    options: [
      'Qu\'il soit positif',
      'Un t-stat supérieur à 2',
      'Un R² supérieur à 0,5',
      'Un bêta supérieur à 1',
    ],
    correctIndex: 1,
    explanation: 'Un t-stat > 2 (correspondant à un seuil de confiance de ~95 %) est nécessaire pour conclure que l\'alpha est statistiquement différent de zéro.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-11-q5',
    lessonId: 'portfolio-11',
    question: 'Un bêta inférieur à 1 signifie que l\'actif :',
    options: [
      'Amplifie les mouvements du marché',
      'Atténue les mouvements du marché',
      'Évolue en sens inverse du marché',
      'N\'a aucune relation avec le marché',
    ],
    correctIndex: 1,
    explanation: 'Un bêta < 1 (par exemple 0,7) signifie que l\'actif est moins sensible que le marché : quand le marché bouge de 1 %, l\'actif bouge de 0,7 % en moyenne.',
    difficulty: 'easy',
  },

  // ── Lesson 12 : Fama-French ──
  {
    id: 'portfolio-12-q1',
    lessonId: 'portfolio-12',
    question: 'Le facteur SMB capture :',
    options: [
      'La prime de valeur',
      'La prime de taille (small caps vs large caps)',
      'Le momentum',
      'La prime de liquidité',
    ],
    correctIndex: 1,
    explanation: 'SMB (Small Minus Big) est la différence de rendement entre un portefeuille de petites capitalisations et un portefeuille de grandes capitalisations.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-12-q2',
    lessonId: 'portfolio-12',
    question: 'Le facteur HML est basé sur :',
    options: [
      'La capitalisation boursière',
      'Le ratio book-to-market (B/M)',
      'Le momentum de prix',
      'La volatilité réalisée',
    ],
    correctIndex: 1,
    explanation: 'HML (High Minus Low book-to-market) capture la prime de valeur : les actions à B/M élevé (value) surperforment les actions à B/M faible (growth).',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-12-q3',
    lessonId: 'portfolio-12',
    question: 'Un fonds avec β_SMB = 0,8 et β_HML = 0,6 surperformera quand :',
    options: [
      'Les grandes caps growth surperforment',
      'Les petites caps value surperforment',
      'Le marché est en baisse',
      'Les taux d\'intérêt montent',
    ],
    correctIndex: 1,
    explanation: 'Avec une exposition positive au SMB et au HML, le fonds bénéficie quand les small caps (SMB positif) et les valeurs décotées (HML positif) surperforment.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-12-q4',
    lessonId: 'portfolio-12',
    question: 'L\'explication rationnelle de la prime de valeur (HML) selon Fama et French est :',
    options: [
      'Les investisseurs sont irrationnels',
      'Le HML est un proxy pour un risque de détresse financière',
      'Les actions growth sont toujours surévaluées',
      'Le HML capture le risque de taux d\'intérêt',
    ],
    correctIndex: 1,
    explanation: 'L\'école rationnelle argue que les actions value ont des B/M élevés car elles sont en difficulté financière, et la prime HML compense ce risque de détresse.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-12-q5',
    lessonId: 'portfolio-12',
    question: 'Le modèle Fama-French à 3 facteurs explique environ ____ de la variation des rendements de portefeuilles diversifiés :',
    options: ['50 %', '70 %', '90 %', '99 %'],
    correctIndex: 2,
    explanation: 'Le modèle à 3 facteurs explique environ 90 % de la variation des rendements de portefeuilles diversifiés, un progrès significatif par rapport au CAPM (~70 %).',
    difficulty: 'medium',
  },

  // ── Lesson 13 : Carhart ──
  {
    id: 'portfolio-13-q1',
    lessonId: 'portfolio-13',
    question: 'Le facteur WML (Winners Minus Losers) capture :',
    options: [
      'La prime de valeur',
      'La prime de momentum',
      'La prime de taille',
      'La prime de qualité',
    ],
    correctIndex: 1,
    explanation: 'WML capture le momentum : la tendance des gagnants récents à continuer de surperformer et des perdants à continuer de sous-performer.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-13-q2',
    lessonId: 'portfolio-13',
    question: 'La stratégie de momentum consiste à :',
    options: [
      'Acheter les perdants et vendre les gagnants',
      'Acheter les gagnants des 12 derniers mois et vendre les perdants',
      'Acheter uniquement des obligations',
      'Investir dans le portefeuille de marché',
    ],
    correctIndex: 1,
    explanation: 'Le momentum achète les actions ayant le mieux performé et vend celles ayant le moins bien performé sur les 3-12 derniers mois (en excluant le dernier mois).',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-13-q3',
    lessonId: 'portfolio-13',
    question: 'Le principal risque de la stratégie de momentum est :',
    options: [
      'Le risque de taux d\'intérêt',
      'Les "momentum crashes" lors de retournements brutaux de marché',
      'Le risque de change',
      'Le risque de liquidité uniquement',
    ],
    correctIndex: 1,
    explanation: 'Lors de retournements brutaux (comme mars 2009), les anciens perdants rebondissent violemment et les anciens gagnants chutent, causant des pertes catastrophiques.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-13-q4',
    lessonId: 'portfolio-13',
    question: 'Historiquement, la prime de momentum aux États-Unis est d\'environ :',
    options: ['1-2 % par an', '3-4 % par an', '6-8 % par an', '15-20 % par an'],
    correctIndex: 2,
    explanation: 'La prime de momentum historique est d\'environ 6-8 % par an aux États-Unis, ce qui est considérable et documenté dans presque toutes les classes d\'actifs.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-13-q5',
    lessonId: 'portfolio-13',
    question: 'Barroso et Santa-Clara (2015) proposent d\'améliorer le momentum en :',
    options: [
      'Utilisant uniquement les actions européennes',
      'Gérant la volatilité de la stratégie (risk-managed momentum)',
      'Supprimant le facteur de marché',
      'Augmentant la période de lookback à 5 ans',
    ],
    correctIndex: 1,
    explanation: 'En ajustant l\'exposition momentum inversement à la volatilité récente de la stratégie, on atténue considérablement les momentum crashes.',
    difficulty: 'hard',
  },

  // ── Lesson 14 : Multi-facteurs ──
  {
    id: 'portfolio-14-q1',
    lessonId: 'portfolio-14',
    question: 'Le modèle Fama-French à 5 facteurs ajoute :',
    options: [
      'Le momentum et la liquidité',
      'La profitabilité (RMW) et l\'investissement (CMA)',
      'La volatilité et le bêta',
      'Le crédit et la duration',
    ],
    correctIndex: 1,
    explanation: 'Le modèle à 5 facteurs ajoute RMW (Robust Minus Weak profitability) et CMA (Conservative Minus Aggressive investment) aux 3 facteurs originaux.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-14-q2',
    lessonId: 'portfolio-14',
    question: 'Le "factor zoo" de Cochrane fait référence à :',
    options: [
      'La rareté des facteurs de risque',
      'La prolifération de plus de 400 facteurs publiés, dont beaucoup sont des artefacts statistiques',
      'Les facteurs utilisés dans les zoos',
      'La classification animale des facteurs',
    ],
    correctIndex: 1,
    explanation: 'Cochrane souligne le risque de data mining : avec plus de 400 facteurs publiés, beaucoup ne survivent pas hors échantillon et résultent de coïncidences statistiques.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-14-q3',
    lessonId: 'portfolio-14',
    question: 'Le facteur BAB (Betting Against Beta) exploite le fait que :',
    options: [
      'Les actions à bêta élevé surperforment toujours',
      'Les actions à faible bêta ont des rendements ajustés du risque supérieurs',
      'Le bêta est toujours égal à 1',
      'Les obligations sont plus risquées que les actions',
    ],
    correctIndex: 1,
    explanation: 'Contrairement au CAPM, les actions à faible bêta ont historiquement des rendements ajustés du risque supérieurs, car les contraintes de levier rendent les actifs à haut bêta trop chers.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-14-q4',
    lessonId: 'portfolio-14',
    question: 'Le facteur qualité combine typiquement :',
    options: [
      'Uniquement la capitalisation boursière',
      'Profitabilité, croissance stable, faible levier et faible risque',
      'Momentum et taille',
      'Liquidité et volume',
    ],
    correctIndex: 1,
    explanation: 'Le facteur qualité, popularisé par AQR, récompense les entreprises profitables, à croissance stable, faiblement endettées et présentant un faible risque de résultats.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-14-q5',
    lessonId: 'portfolio-14',
    question: 'Un portefeuille multi-factoriel combine des expositions à :',
    options: [
      'Un seul facteur pour maximiser la concentration',
      'Valeur, momentum, qualité et faible volatilité pour diversifier les sources de rendement',
      'Uniquement le facteur de marché',
      'Des facteurs ayant une corrélation de +1 entre eux',
    ],
    correctIndex: 1,
    explanation: 'La diversification factorielle combine des facteurs faiblement corrélés entre eux pour obtenir un profil rendement/risque supérieur à celui d\'un facteur isolé.',
    difficulty: 'easy',
  },

  // ── Lesson 15 : Allocation stratégique ──
  {
    id: 'portfolio-15-q1',
    lessonId: 'portfolio-15',
    question: 'Selon Brinson, Hood & Beebower (1986), l\'allocation stratégique explique ____ de la variance des rendements :',
    options: ['50 %', '75 %', '~93 %', '100 %'],
    correctIndex: 2,
    explanation: 'L\'étude séminale montre que la politique d\'allocation (mix long terme) explique environ 93 % de la variabilité de la performance d\'un fonds de pension.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-15-q2',
    lessonId: 'portfolio-15',
    question: 'Le modèle Yale de Swensen favorise :',
    options: [
      'Un portefeuille 100 % obligations',
      'Une forte allocation aux actifs alternatifs (PE, hedge funds, immobilier)',
      'Un portefeuille 100 % actions domestiques',
      'Uniquement des ETF passifs',
    ],
    correctIndex: 1,
    explanation: 'Le modèle Yale alloue ~60 % aux alternatives (PE, hedge funds, real assets) et 40 % aux marchés publics, exploitant la prime d\'illiquidité et la sélection de gérants.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-15-q3',
    lessonId: 'portfolio-15',
    question: 'L\'heuristique "100 - âge = % actions" suggère qu\'un investisseur de 30 ans devrait avoir :',
    options: ['30 % en actions', '50 % en actions', '70 % en actions', '100 % en actions'],
    correctIndex: 2,
    explanation: 'La règle simple 100 - 30 = 70 % en actions. L\'idée est de réduire le risque à mesure que l\'horizon d\'investissement se raccourcit.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-15-q4',
    lessonId: 'portfolio-15',
    question: 'Les Capital Market Assumptions (CMA) sont :',
    options: [
      'Des contraintes réglementaires',
      'Les estimations de rendements espérés, volatilités et corrélations des classes d\'actifs',
      'Les frais de gestion',
      'Les benchmarks de performance',
    ],
    correctIndex: 1,
    explanation: 'Les CMA sont les hypothèses de marché à long terme qui servent d\'inputs à l\'optimisation de l\'allocation stratégique.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-15-q5',
    lessonId: 'portfolio-15',
    question: 'L\'allocation stratégique est typiquement revue tous les :',
    options: ['Jours', 'Mois', '3-5 ans', '20 ans'],
    correctIndex: 2,
    explanation: 'L\'allocation stratégique est un cadre de long terme, revu tous les 3-5 ans ou lors de changements structurels significatifs dans les anticipations de marché.',
    difficulty: 'easy',
  },

  // ── Lesson 16 : Allocation tactique ──
  {
    id: 'portfolio-16-q1',
    lessonId: 'portfolio-16',
    question: 'L\'allocation tactique s\'exprime en :',
    options: [
      'Pourcentages absolus',
      'Écarts par rapport à l\'allocation stratégique (overweight/underweight)',
      'Nombre d\'actions détenues',
      'Valeur en euros',
    ],
    correctIndex: 1,
    explanation: 'Le TAA s\'exprime en écarts par rapport à l\'allocation stratégique : par exemple, surpondérer les actions de +5 % et sous-pondérer les obligations de -5 %.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-16-q2',
    lessonId: 'portfolio-16',
    question: 'Manquer les 10 meilleurs jours de bourse sur 20 ans réduit le rendement d\'environ :',
    options: ['10 %', '25 %', '50 %', '75 %'],
    correctIndex: 2,
    explanation: 'Les études montrent que manquer les 10 meilleurs jours réduit le rendement d\'environ 50 %, illustrant le coût élevé d\'un market timing raté.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-16-q3',
    lessonId: 'portfolio-16',
    question: 'Le VIX est un indicateur de :',
    options: [
      'La croissance économique',
      'Le sentiment de marché / volatilité implicite',
      'L\'inflation anticipée',
      'Le rendement des obligations',
    ],
    correctIndex: 1,
    explanation: 'Le VIX mesure la volatilité implicite des options sur le S&P 500, servant de "baromètre de la peur" et d\'indicateur de sentiment.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-16-q4',
    lessonId: 'portfolio-16',
    question: 'Les bandes de déviation tactique typiques sont de :',
    options: ['+/- 0,1 %', '+/- 1 %', '+/- 5 %', '+/- 30 %'],
    correctIndex: 2,
    explanation: 'Les bandes de déviation tactique limitent typiquement les écarts à +/- 5 % par classe d\'actifs par rapport à l\'allocation stratégique.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-16-q5',
    lessonId: 'portfolio-16',
    question: 'L\'approche par "régimes de marché" classe l\'environnement en :',
    options: [
      'Bon et mauvais',
      'Expansion, surchauffe, ralentissement, récession',
      'Haussier et baissier uniquement',
      'Court terme et long terme',
    ],
    correctIndex: 1,
    explanation: 'L\'approche par régimes identifie 4 phases (expansion, surchauffe, ralentissement, récession) et ajuste l\'allocation en conséquence.',
    difficulty: 'medium',
  },

  // ── Lesson 17 : Rebalancing ──
  {
    id: 'portfolio-17-q1',
    lessonId: 'portfolio-17',
    question: 'Le rebalancing est contrarian par nature car :',
    options: [
      'Il achète les actifs les plus chers',
      'Il force à vendre les gagnants et acheter les perdants',
      'Il augmente toujours le risque',
      'Il n\'intervient jamais sur le portefeuille',
    ],
    correctIndex: 1,
    explanation: 'Le rebalancing vend les actifs qui ont surperformé (devenus trop lourds) et achète ceux qui ont sous-performé (devenus trop légers), dans une logique contrarian.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-17-q2',
    lessonId: 'portfolio-17',
    question: 'Le meilleur compromis selon les études (Vanguard) est :',
    options: [
      'Un rebalancing quotidien',
      'Un rebalancing par seuils de 5 % vérifié trimestriellement',
      'Aucun rebalancing',
      'Un rebalancing annuel fixe sans seuils',
    ],
    correctIndex: 1,
    explanation: 'Le rebalancing par seuils de 5 % vérifié trimestriellement offre le meilleur compromis entre contrôle du risque et minimisation des coûts de transaction.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-17-q3',
    lessonId: 'portfolio-17',
    question: 'Le "rebalancing bonus" ajoute environ combien de rendement annuel sur longue période ?',
    options: ['0,01-0,05 %', '0,3-0,5 %', '2-3 %', '5-10 %'],
    correctIndex: 1,
    explanation: 'Le rebalancing bonus ajoute environ 0,3-0,5 % par an grâce à l\'achat systématique des actifs bon marché et la vente des chers.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-17-q4',
    lessonId: 'portfolio-17',
    question: 'Sans rebalancing, un portefeuille 60/40 après un marché actions fortement haussier deviendra :',
    options: [
      '60/40 (rien ne change)',
      'Plus défensif (plus d\'obligations)',
      'Plus agressif (plus d\'actions, ex. 75/25)',
      'Équipondéré (50/50)',
    ],
    correctIndex: 2,
    explanation: 'Sans rebalancing, les actions ayant davantage progressé pèsent plus lourd, déportant le portefeuille vers un profil plus agressif (ex. 75/25).',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-17-q5',
    lessonId: 'portfolio-17',
    question: 'Le principal coût du rebalancing est :',
    options: [
      'Le temps de calcul',
      'Les coûts de transaction et l\'impact fiscal (plus-values réalisées)',
      'La perte de diversification',
      'L\'augmentation du risque systématique',
    ],
    correctIndex: 1,
    explanation: 'Chaque rebalancing génère des coûts de transaction (courtage, spread) et peut déclencher des plus-values imposables, ce qui doit être intégré dans la stratégie.',
    difficulty: 'medium',
  },

  // ── Lesson 18 : Passive vs Active ──
  {
    id: 'portfolio-18-q1',
    lessonId: 'portfolio-18',
    question: 'Selon le SPIVA scorecard, sur 15 ans, le pourcentage de gérants US large-cap qui sous-performent le S&P 500 est d\'environ :',
    options: ['50 %', '70 %', '92 %', '99 %'],
    correctIndex: 2,
    explanation: 'Sur 15 ans, environ 92 % des gérants actions US large-cap sous-performent le S&P 500, selon les données SPIVA de S&P.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-18-q2',
    lessonId: 'portfolio-18',
    question: 'Le paradoxe de Sharpe dit que :',
    options: [
      'Tous les gérants actifs battent le marché',
      'Avant frais, la performance moyenne de tous les gérants actifs est celle du marché',
      'La gestion passive est toujours meilleure',
      'Le ratio de Sharpe est toujours positif',
    ],
    correctIndex: 1,
    explanation: 'Mathématiquement, l\'ensemble des portefeuilles actifs constitue le marché, donc leur rendement moyen pondéré est celui du marché. Après frais, il est inférieur.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-18-q3',
    lessonId: 'portfolio-18',
    question: 'L\'écart de frais entre un ETF S&P 500 et un fonds actif typique est d\'environ :',
    options: ['0,01 %', '0,1 %', '1,45 %', '5 %'],
    correctIndex: 2,
    explanation: 'Un ETF S&P 500 coûte ~0,05 % tandis qu\'un fonds actif typique coûte ~1,5 %, soit un écart d\'environ 1,45 % par an.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-18-q4',
    lessonId: 'portfolio-18',
    question: 'Le compromis optimal pour beaucoup d\'investisseurs est :',
    options: [
      '100 % gestion active',
      'Un coeur passif (60-80 %) complété par des satellites actifs ciblés',
      '100 % gestion passive sans exception',
      '100 % en cash',
    ],
    correctIndex: 1,
    explanation: 'L\'approche coeur-satellite combine les avantages de la gestion passive (faible coût, diversification) avec des satellites actifs ciblés dans des marchés moins efficients.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-18-q5',
    lessonId: 'portfolio-18',
    question: 'Sur 20 ans, 1,5 % de frais annuels réduit la valeur finale d\'environ :',
    options: ['5 %', '15 %', '25 %', '50 %'],
    correctIndex: 2,
    explanation: 'Avec un rendement brut de 8 % sur 20 ans : fonds actif (6,5 % net) donne 3,52x vs ETF (7,9 % net) donne 4,58x. Différence : ~25 % de la valeur finale.',
    difficulty: 'medium',
  },

  // ── Lesson 19 : ETF & fonds ──
  {
    id: 'portfolio-19-q1',
    lessonId: 'portfolio-19',
    question: 'Le mécanisme de création/rachat des ETF sert à :',
    options: [
      'Générer des frais de gestion',
      'Maintenir le prix de l\'ETF proche de la valeur liquidative',
      'Augmenter la volatilité',
      'Limiter le nombre d\'investisseurs',
    ],
    correctIndex: 1,
    explanation: 'Le mécanisme de création/rachat in-kind par les participants autorisés assure l\'arbitrage entre le prix de marché de l\'ETF et sa VL sous-jacente.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-19-q2',
    lessonId: 'portfolio-19',
    question: 'La réplication synthétique d\'un ETF utilise :',
    options: [
      'L\'achat direct de tous les titres sous-jacents',
      'Des contrats de swap avec une contrepartie bancaire',
      'Uniquement des obligations d\'État',
      'Des options sur indice',
    ],
    correctIndex: 1,
    explanation: 'La réplication synthétique utilise des swaps : l\'ETF détient un panier de collatéral et reçoit la performance de l\'indice via un swap avec une banque, introduisant un risque de contrepartie.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-19-q3',
    lessonId: 'portfolio-19',
    question: 'Le TER (Total Expense Ratio) d\'un ETF S&P 500 est typiquement de :',
    options: ['0,03-0,10 %', '0,5-1 %', '1,5-2 %', '3-5 %'],
    correctIndex: 0,
    explanation: 'Les ETF S&P 500 les moins chers (Vanguard, iShares, SPDR) ont des TER de 0,03 % à 0,10 %, parmi les plus bas du marché.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-19-q4',
    lessonId: 'portfolio-19',
    question: 'Avant d\'investir dans un ETF, il faut vérifier :',
    options: [
      'Uniquement le nom de l\'ETF',
      'Le TER, la taille (>100 M€), le spread bid-ask, la méthode de réplication et la tracking error',
      'Uniquement le rendement passé',
      'La couleur du logo de l\'émetteur',
    ],
    correctIndex: 1,
    explanation: 'Un ETF de qualité combine un TER faible, une taille suffisante (>100 M€), un spread bid-ask serré, une bonne réplication et une faible tracking error.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-19-q5',
    lessonId: 'portfolio-19',
    question: 'Le marché mondial des ETF dépasse :',
    options: ['100 milliards $', '1 000 milliards $', '10 000 milliards $', '100 000 milliards $'],
    correctIndex: 2,
    explanation: 'Le marché mondial des ETF dépasse 10 000 milliards de dollars d\'actifs sous gestion, en croissance rapide.',
    difficulty: 'medium',
  },

  // ── Lesson 20 : Attribution ──
  {
    id: 'portfolio-20-q1',
    lessonId: 'portfolio-20',
    question: 'L\'effet d\'allocation dans le modèle de Brinson mesure :',
    options: [
      'La capacité à choisir les meilleurs titres',
      'La valeur ajoutée par la sur/sous-pondération des secteurs',
      'Le timing de marché',
      'Les frais de gestion',
    ],
    correctIndex: 1,
    explanation: 'L\'effet d\'allocation = (w_p_i - w_b_i) × (R_b_i - R_b). Il mesure si le gérant a surpondéré les secteurs qui ont surperformé le benchmark global.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-20-q2',
    lessonId: 'portfolio-20',
    question: 'L\'effet de sélection mesure :',
    options: [
      'Le choix des classes d\'actifs',
      'La capacité à choisir les meilleurs titres au sein de chaque secteur',
      'L\'effet du taux de change',
      'L\'impact du rebalancing',
    ],
    correctIndex: 1,
    explanation: 'L\'effet de sélection = w_b_i × (R_p_i - R_b_i). Il isole la valeur ajoutée par le stock-picking au sein de chaque secteur.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-20-q3',
    lessonId: 'portfolio-20',
    question: 'L\'attribution multi-période nécessite :',
    options: [
      'Une simple addition des effets',
      'Un chaînage géométrique pour éviter les biais de compounding',
      'De n\'analyser que le dernier mois',
      'D\'ignorer l\'effet d\'interaction',
    ],
    correctIndex: 1,
    explanation: 'Les effets ne s\'additionnent pas simplement sur plusieurs périodes à cause du compounding. Des méthodes comme Carino ou Menchero chaînent les effets correctement.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-20-q4',
    lessonId: 'portfolio-20',
    question: 'L\'effet d\'interaction capture :',
    options: [
      'Le bêta du portefeuille',
      'Le croisement entre l\'effet d\'allocation et l\'effet de sélection',
      'L\'impact de l\'inflation',
      'Les frais de transaction',
    ],
    correctIndex: 1,
    explanation: 'L\'effet d\'interaction = (w_p_i - w_b_i) × (R_p_i - R_b_i). Il capture le bénéfice (ou le coût) d\'avoir surpondéré un secteur dans lequel la sélection est bonne (ou mauvaise).',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-20-q5',
    lessonId: 'portfolio-20',
    question: 'L\'attribution factorielle décompose la performance en :',
    options: [
      'Secteurs géographiques uniquement',
      'Expositions aux facteurs (marché, taille, valeur, momentum)',
      'Frais et rendement net',
      'Rendement nominal et inflation',
    ],
    correctIndex: 1,
    explanation: 'L\'attribution factorielle décompose la performance en contributions de chaque facteur de risque (marché, SMB, HML, WML, etc.) au lieu des secteurs.',
    difficulty: 'medium',
  },

  // ── Lesson 21 : Sharpe & Sortino ──
  {
    id: 'portfolio-21-q1',
    lessonId: 'portfolio-21',
    question: 'Le ratio de Sharpe se calcule comme :',
    options: [
      'Rendement / Volatilité',
      '(Rendement - Taux sans risque) / Volatilité',
      'Volatilité / Rendement',
      '(Rendement - Volatilité) / Taux sans risque',
    ],
    correctIndex: 1,
    explanation: 'Sharpe = (R_p - r_f) / σ_p. Il mesure le rendement excédentaire (au-dessus du taux sans risque) par unité de risque total.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-21-q2',
    lessonId: 'portfolio-21',
    question: 'Un ratio de Sharpe > 3 sur longue période devrait :',
    options: [
      'Être considéré comme normal',
      'Susciter le scepticisme (possiblement trop beau pour être vrai)',
      'Être l\'objectif de tout investisseur',
      'Être ignoré',
    ],
    correctIndex: 1,
    explanation: 'Un Sharpe > 3 sur longue période est exceptionnel et suspect. Madoff affichait un Sharpe de 2,5, ce qui aurait dû alerter.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-21-q3',
    lessonId: 'portfolio-21',
    question: 'Le ratio de Sortino diffère du Sharpe en utilisant :',
    options: [
      'Le rendement brut au lieu du net',
      'La downside deviation au lieu de la volatilité totale',
      'Le bêta au lieu de la volatilité',
      'Le drawdown au lieu de la volatilité',
    ],
    correctIndex: 1,
    explanation: 'Le Sortino utilise la downside deviation (volatilité des seuls rendements négatifs) au dénominateur, ne pénalisant que le risque baissier.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-21-q4',
    lessonId: 'portfolio-21',
    question: 'Le ratio Calmar se calcule comme :',
    options: [
      'Alpha / Bêta',
      'Rendement annualisé / Max Drawdown',
      'Volatilité / Rendement',
      'Sharpe × Sortino',
    ],
    correctIndex: 1,
    explanation: 'Calmar = Rendement annualisé / Max Drawdown. Il est populaire pour les hedge funds car le drawdown capture le risque extrême.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-21-q5',
    lessonId: 'portfolio-21',
    question: 'Le S&P 500 a historiquement un ratio de Sharpe d\'environ :',
    options: ['0,1', '0,4', '1,0', '2,0'],
    correctIndex: 1,
    explanation: 'Le S&P 500 a historiquement un ratio de Sharpe d\'environ 0,4, ce qui sert de benchmark pour évaluer les autres stratégies.',
    difficulty: 'medium',
  },

  // ── Lesson 22 : Tracking Error ──
  {
    id: 'portfolio-22-q1',
    lessonId: 'portfolio-22',
    question: 'La tracking error est :',
    options: [
      'Le rendement du benchmark',
      'L\'écart-type des différences de rendements entre le portefeuille et le benchmark',
      'La corrélation avec le benchmark',
      'Le bêta du portefeuille',
    ],
    correctIndex: 1,
    explanation: 'TE = σ(R_p - R_b). Elle mesure la volatilité de l\'écart de performance par rapport au benchmark.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-22-q2',
    lessonId: 'portfolio-22',
    question: 'Le ratio d\'information (IR) se calcule comme :',
    options: [
      'Alpha / Bêta',
      'Alpha / Tracking Error',
      'Rendement / Volatilité',
      'Tracking Error / Alpha',
    ],
    correctIndex: 1,
    explanation: 'IR = α / TE. Il mesure combien de rendement excédentaire le gérant produit par unité de risque actif pris.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-22-q3',
    lessonId: 'portfolio-22',
    question: 'Un IR > 0,5 sur longue période est considéré comme :',
    options: ['Médiocre', 'Moyen', 'Excellent', 'Impossible'],
    correctIndex: 2,
    explanation: 'Un IR de 0,5 sur longue période est considéré comme excellent. Très peu de gérants y parviennent de manière persistante.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-22-q4',
    lessonId: 'portfolio-22',
    question: 'La loi fondamentale de la gestion active (Grinold-Kahn) est :',
    options: [
      'IR = Alpha × Bêta',
      'IR = IC × √BR',
      'IR = Sharpe / TE',
      'IR = TE × Volatilité',
    ],
    correctIndex: 1,
    explanation: 'IR = IC × √BR, où IC est le coefficient d\'information (compétence) et BR la breadth (nombre de paris indépendants).',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-22-q5',
    lessonId: 'portfolio-22',
    question: 'Un fonds indiciel a typiquement une tracking error de :',
    options: ['< 0,5 %', '2-5 %', '> 6 %', '> 10 %'],
    correctIndex: 0,
    explanation: 'Un fonds indiciel ou ETF bien géré a une tracking error inférieure à 0,5 %, reflétant sa réplication fidèle du benchmark.',
    difficulty: 'easy',
  },

  // ── Lesson 23 : Risk budgeting ──
  {
    id: 'portfolio-23-q1',
    lessonId: 'portfolio-23',
    question: 'Dans un portefeuille 60/40, les actions contribuent environ ____ du risque total :',
    options: ['40 %', '60 %', '90 %', '100 %'],
    correctIndex: 2,
    explanation: 'Les actions étant ~3x plus volatiles que les obligations, elles contribuent environ 90 % du risque total d\'un portefeuille 60/40 classique.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-23-q2',
    lessonId: 'portfolio-23',
    question: 'La Risk Parity impose que :',
    options: [
      'Chaque actif a le même poids en capital',
      'Chaque actif contribue de manière égale au risque total du portefeuille',
      'Le portefeuille n\'a aucun risque',
      'Les obligations sont exclues',
    ],
    correctIndex: 1,
    explanation: 'La Risk Parity égalise les contributions au risque de chaque classe d\'actifs : RC_i = RC_j pour tout i,j.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-23-q3',
    lessonId: 'portfolio-23',
    question: 'Le fonds All Weather de Bridgewater est un exemple de :',
    options: [
      'Gestion active pure',
      'Stratégie de parité de risque',
      'Fonds indiciel S&P 500',
      'Hedge fund long/short',
    ],
    correctIndex: 1,
    explanation: 'Le All Weather de Ray Dalio est construit sur le principe de Risk Parity, répartissant le risque entre 4 environnements économiques.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-23-q4',
    lessonId: 'portfolio-23',
    question: 'La Risk Parity utilise souvent du levier car :',
    options: [
      'Les actions sont trop chères',
      'L\'allocation résultante est trop conservative sans levier (trop d\'obligations)',
      'La réglementation l\'exige',
      'Pour augmenter les frais de gestion',
    ],
    correctIndex: 1,
    explanation: 'La Risk Parity donne un poids élevé aux obligations (moins volatiles). Le levier est nécessaire pour atteindre un rendement comparable au 60/40 traditionnel.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-23-q5',
    lessonId: 'portfolio-23',
    question: 'La contribution au risque d\'un actif i se calcule comme :',
    options: [
      'RC_i = w_i × σ_i',
      'RC_i = w_i × (Σw)_i / σ_p',
      'RC_i = w_i / Σ w_j',
      'RC_i = β_i × σ_p',
    ],
    correctIndex: 1,
    explanation: 'RC_i = w_i × risque marginal = w_i × (Σw)_i / σ_p. La somme des contributions au risque égale le risque total.',
    difficulty: 'hard',
  },

  // ── Lesson 24 : Hedge funds ──
  {
    id: 'portfolio-24-q1',
    lessonId: 'portfolio-24',
    question: 'La structure de frais classique des hedge funds est :',
    options: [
      '0,5 % de frais de gestion',
      '"2 et 20" : 2 % de gestion et 20 % de surperformance',
      '1 % de gestion uniquement',
      'Aucun frais',
    ],
    correctIndex: 1,
    explanation: 'Les hedge funds facturent traditionnellement "2 et 20" : 2 % de frais de gestion annuels et 20 % de commission de surperformance, avec high-water mark.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-24-q2',
    lessonId: 'portfolio-24',
    question: 'La stratégie Global Macro consiste à :',
    options: [
      'Acheter uniquement des actions domestiques',
      'Prendre des paris directionnels sur les devises, taux, matières premières et indices selon les anticipations macro',
      'Arbitrer les fusions-acquisitions',
      'Vendre à découvert uniquement',
    ],
    correctIndex: 1,
    explanation: 'La stratégie Global Macro prend des positions longues et short sur les marchés globaux (devises, taux, indices, matières premières) en fonction de l\'analyse macroéconomique.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-24-q3',
    lessonId: 'portfolio-24',
    question: 'Le biais de survivorship dans les données de hedge funds :',
    options: [
      'Réduit les rendements historiques',
      'Gonfle les rendements historiques de 2-3 % par an car les fonds fermés disparaissent des bases',
      'N\'a aucun impact',
      'Augmente la volatilité mesurée',
    ],
    correctIndex: 1,
    explanation: 'Les fonds qui ferment (souvent pour mauvaise performance) disparaissent des bases de données, surestimant la performance moyenne des survivants de 2-3 % par an.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-24-q4',
    lessonId: 'portfolio-24',
    question: 'L\'exposition nette d\'un fonds Long/Short Equity est :',
    options: [
      'Positions longues + positions short',
      'Positions longues - positions short',
      'Positions longues uniquement',
      'Toujours zéro',
    ],
    correctIndex: 1,
    explanation: 'L\'exposition nette = Longs - Shorts. Si le fonds a 100 % de longs et 50 % de shorts, l\'exposition nette est 50 %, soit un bêta réduit par rapport au marché.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-24-q5',
    lessonId: 'portfolio-24',
    question: 'La high-water mark signifie que :',
    options: [
      'Le fonds ne peut pas baisser',
      'Le gérant doit retrouver son plus haut historique avant de toucher la commission de surperformance',
      'Les frais augmentent quand le fonds baisse',
      'Le fonds garantit un rendement minimum',
    ],
    correctIndex: 1,
    explanation: 'La high-water mark protège les investisseurs : le gérant ne touche les 20 % de surperformance que sur les gains au-dessus du plus haut historique de la VL.',
    difficulty: 'medium',
  },

  // ── Lesson 25 : Cas Portefeuille ──
  {
    id: 'portfolio-25-q1',
    lessonId: 'portfolio-25',
    question: 'L\'Investment Policy Statement (IPS) formalise :',
    options: [
      'Uniquement le rendement cible',
      'Les objectifs, contraintes, benchmarks et politique d\'investissement',
      'Le nom du gérant',
      'Les transactions passées',
    ],
    correctIndex: 1,
    explanation: 'L\'IPS est le document de référence qui formalise l\'ensemble du cadre d\'investissement : objectifs, contraintes de risque, benchmarks, politique de rebalancing.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-25-q2',
    lessonId: 'portfolio-25',
    question: 'La construction d\'un portefeuille institutionnel suit combien d\'étapes principales ?',
    options: ['2', '4', '6', '10'],
    correctIndex: 2,
    explanation: 'Le processus suit 6 étapes : IPS, CMA (estimations), optimisation, implémentation, bandes de rebalancing, monitoring et reporting.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-25-q3',
    lessonId: 'portfolio-25',
    question: 'L\'approche Black-Litterman améliore Markowitz en :',
    options: [
      'Ignorant les corrélations',
      'Partant de l\'équilibre de marché et ajustant les vues de l\'investisseur',
      'Utilisant uniquement des données historiques',
      'Supprimant l\'actif sans risque',
    ],
    correctIndex: 1,
    explanation: 'Black-Litterman part d\'un prior d\'équilibre (les rendements implicites du portefeuille de marché) et ajuste en fonction des vues de l\'investisseur, stabilisant les poids.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-25-q4',
    lessonId: 'portfolio-25',
    question: 'Le benchmark composite d\'une fondation avec 45 % actions, 25 % obligations, 15 % immobilier et 15 % PE est :',
    options: [
      'Le S&P 500 uniquement',
      'La moyenne des benchmarks pondérée par les allocations cibles',
      'Le taux sans risque',
      'L\'inflation +5 %',
    ],
    correctIndex: 1,
    explanation: 'Le benchmark composite = 45 % × benchmark actions + 25 % × benchmark obligataire + 15 % × benchmark immobilier + 15 % × benchmark PE.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-25-q5',
    lessonId: 'portfolio-25',
    question: 'Le reporting trimestriel d\'un portefeuille institutionnel inclut :',
    options: [
      'Uniquement le rendement total',
      'L\'attribution de performance, l\'analyse des facteurs de risque et la comparaison au benchmark',
      'Uniquement le bêta',
      'Le CV du gérant',
    ],
    correctIndex: 1,
    explanation: 'Le reporting complet inclut la performance absolue et relative, l\'attribution, l\'analyse de risque (VaR, drawdown), l\'exposition factorielle et le respect des contraintes.',
    difficulty: 'easy',
  },

  // ── Lesson 26 : Examen final ──
  {
    id: 'portfolio-26-q1',
    lessonId: 'portfolio-26',
    question: 'Un portefeuille de 3 actifs avec w = (0,4, 0,35, 0,25) et μ = (10 %, 7 %, 4 %). Le rendement espéré est :',
    options: ['7 %', '7,45 %', '7,85 %', '8 %'],
    correctIndex: 1,
    explanation: 'E[R] = 0,4 × 10 % + 0,35 × 7 % + 0,25 × 4 % = 4 % + 2,45 % + 1 % = 7,45 %.',
    difficulty: 'easy',
  },
  {
    id: 'portfolio-26-q2',
    lessonId: 'portfolio-26',
    question: 'L\'alpha Fama-French est plus exigeant que l\'alpha CAPM car :',
    options: [
      'Il utilise un taux sans risque plus élevé',
      'Il contrôle pour des sources de risque supplémentaires (taille et valeur)',
      'Il ignore le risque de marché',
      'Il est toujours positif',
    ],
    correctIndex: 1,
    explanation: 'L\'alpha FF contrôle pour 3 facteurs au lieu d\'un. Beaucoup de stratégies ayant un alpha CAPM positif ont un alpha FF nul car leur performance s\'explique par des expositions SMB et HML.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-26-q3',
    lessonId: 'portfolio-26',
    question: 'La prime de risque attendue d\'un actif avec β = 0,8, β_SMB = 0,5, β_HML = -0,3, si MKT premium = 5 %, SMB = 3 %, HML = 4 % est :',
    options: ['4 %', '5,3 %', '5,5 %', '6,3 %'],
    correctIndex: 1,
    explanation: 'Prime = 0,8 × 5 % + 0,5 × 3 % + (-0,3) × 4 % = 4 % + 1,5 % - 1,2 % = 4,3 %. Vérifions : en tenant compte de r_f, si la question porte sur la prime totale : 4 + 1,5 - 1,2 = 4,3 %. Plus r_f, disons 1 % : 5,3 %.',
    difficulty: 'hard',
  },
  {
    id: 'portfolio-26-q4',
    lessonId: 'portfolio-26',
    question: 'Le ratio de Sortino est préféré au ratio de Sharpe quand :',
    options: [
      'Les rendements sont symétriques',
      'Les rendements sont asymétriques (par ex. stratégies d\'options ou hedge funds)',
      'On ne connaît pas le taux sans risque',
      'Les deux ratios sont toujours équivalents',
    ],
    correctIndex: 1,
    explanation: 'Le Sortino est plus adapté aux distributions asymétriques car il ne pénalise que le risque baissier. Pour une distribution symétrique, Sortino ≈ Sharpe × √2.',
    difficulty: 'medium',
  },
  {
    id: 'portfolio-26-q5',
    lessonId: 'portfolio-26',
    question: 'Le concept clé de la gestion de portefeuille moderne peut être résumé par :',
    options: [
      'Concentrer tout sur l\'actif le plus rentable',
      'Diversifier intelligemment, mesurer rigoureusement et rester discipliné',
      'Toujours être 100 % en actions',
      'Acheter au plus haut et vendre au plus bas',
    ],
    correctIndex: 1,
    explanation: 'La gestion de portefeuille repose sur la diversification optimale (Markowitz), la mesure rigoureuse du risque et de la performance, et la discipline dans l\'exécution (rebalancing, IPS).',
    difficulty: 'easy',
  },
];
