// ──────────────────────────────────────────────
//  FINA - Finances Personnelles : Quiz
// ──────────────────────────────────────────────

import type { QuizQuestion } from '../types';

export const personalFinanceQuiz: QuizQuestion[] = [
  {
    id: 'pf-q1',
    lessonId: 'pf-1',
    question: 'Selon la règle 50/30/20, quelle part du revenu net devrait être consacrée à l\'épargne ?',
    options: ['10%', '15%', '20%', '30%'],
    correctIndex: 2,
    explanation: 'La règle 50/30/20 : 50% pour les besoins essentiels, 30% pour les envies et 20% pour l\'épargne et le remboursement de dettes.',
    difficulty: 'easy',
  },
  {
    id: 'pf-q2',
    lessonId: 'pf-2',
    question: 'Combien de mois de dépenses courantes un fonds d\'urgence doit-il couvrir ?',
    options: ['1 à 2 mois', '3 à 6 mois', '12 à 18 mois', '24 mois'],
    correctIndex: 1,
    explanation: 'Le fonds d\'urgence doit couvrir 3 à 6 mois de dépenses courantes : 3 mois pour un salarié en CDI stable, 6 mois pour un indépendant ou un CDD.',
    difficulty: 'easy',
  },
  {
    id: 'pf-q3',
    lessonId: 'pf-3',
    question: 'Après combien d\'années le PEA bénéficie-t-il de l\'exonération d\'impôt sur le revenu ?',
    options: ['3 ans', '5 ans', '8 ans', '10 ans'],
    correctIndex: 1,
    explanation: 'Après 5 ans de détention, les plus-values du PEA sont exonérées d\'impôt sur le revenu. Seuls les prélèvements sociaux (17.2%) s\'appliquent.',
    difficulty: 'easy',
  },
  {
    id: 'pf-q4',
    lessonId: 'pf-3',
    question: 'Quel est le plafond de versements du PEA ?',
    options: ['50 000€', '100 000€', '150 000€', 'Illimité'],
    correctIndex: 2,
    explanation: 'Le plafond de versements du PEA est de 150 000€ (les gains sont illimités). Un PEA-PME permet de verser 75 000€ supplémentaires.',
    difficulty: 'easy',
  },
  {
    id: 'pf-q5',
    lessonId: 'pf-4',
    question: 'Après 8 ans, quel est l\'abattement annuel sur les gains retirés d\'une assurance-vie pour un célibataire ?',
    options: ['1 000€', '4 600€', '9 200€', '15 000€'],
    correctIndex: 1,
    explanation: 'Après 8 ans de détention, un abattement annuel de 4 600€ (célibataire) ou 9 200€ (couple) s\'applique aux gains inclus dans chaque retrait.',
    difficulty: 'medium',
  },
  {
    id: 'pf-q6',
    lessonId: 'pf-5',
    question: 'Quel est le principal avantage fiscal du PER ?',
    options: [
      'Les gains sont exonérés d\'impôt',
      'Les versements sont déductibles du revenu imposable',
      'La sortie en capital est exonérée',
      'Les plus-values ne sont pas imposées',
    ],
    correctIndex: 1,
    explanation: 'Le PER permet de déduire les versements du revenu imposable (dans la limite de 10% des revenus). L\'avantage est de différer l\'impôt de la vie active à la retraite.',
    difficulty: 'medium',
  },
  {
    id: 'pf-q7',
    lessonId: 'pf-6',
    question: 'Selon la règle de 72, combien d\'années faut-il pour doubler un capital à 8% par an ?',
    options: ['7 ans', '9 ans', '12 ans', '15 ans'],
    correctIndex: 1,
    explanation: 'Règle de 72 : 72 / 8 = 9 ans pour doubler le capital. C\'est une approximation rapide de l\'effet des intérêts composés.',
    difficulty: 'easy',
  },
  {
    id: 'pf-q8',
    lessonId: 'pf-6',
    question: 'Alice investit 200€/mois de 25 à 65 ans (40 ans) à 7%. Bob investit 400€/mois de 35 à 65 ans (30 ans) à 7%. Qui a le plus gros capital à 65 ans ?',
    options: [
      'Bob, car il investit le double chaque mois',
      'Alice, car les 10 ans supplémentaires compensent le montant moindre',
      'Ils arrivent au même résultat',
      'Impossible à dire sans calculer',
    ],
    correctIndex: 1,
    explanation: 'Alice : ~480 000€ (pour 96 000€ versés). Bob : ~365 000€ (pour 144 000€ versés). Alice investit moins au total mais gagne 31% de plus grâce aux 10 années supplémentaires.',
    difficulty: 'medium',
  },
  {
    id: 'pf-q9',
    lessonId: 'pf-7',
    question: 'Quel est le rendement historique moyen des actions mondiales sur le long terme (dividendes réinvestis) ?',
    options: ['3-4% par an', '5-6% par an', '7-10% par an', '12-15% par an'],
    correctIndex: 2,
    explanation: 'Les actions mondiales ont historiquement rendu 7-10% par an en moyenne, dividendes réinvestis, sur des périodes de 20+ ans.',
    difficulty: 'easy',
  },
  {
    id: 'pf-q10',
    lessonId: 'pf-8',
    question: 'Quel pourcentage des fonds gérés activement sous-performent leur indice de référence sur 10 ans ?',
    options: ['30-40%', '50-60%', '70-80%', '80-90%'],
    correctIndex: 3,
    explanation: '80-90% des fonds actifs ne battent pas leur indice de référence sur 10 ans, après frais. C\'est l\'argument principal en faveur de la gestion passive (ETF).',
    difficulty: 'medium',
  },
  {
    id: 'pf-q11',
    lessonId: 'pf-8',
    question: 'Quelle est la différence de capital final entre un ETF à 0.2% de frais et un fonds actif à 1.8% de frais, sur 100 000€ investis pendant 20 ans à 7% brut ?',
    options: ['~15 000€', '~45 000€', '~83 000€', '~120 000€'],
    correctIndex: 2,
    explanation: 'ETF (6.8% net) : ~363 000€. Fonds actif (5.2% net) : ~280 000€. Différence : ~83 000€ (23% du capital final). Les frais sont le plus grand ennemi de la performance.',
    difficulty: 'hard',
  },
  {
    id: 'pf-q12',
    lessonId: 'pf-9',
    question: 'Quel régime fiscal est le plus avantageux pour un investisseur locatif en meublé ?',
    options: [
      'Le micro-foncier',
      'Le régime réel foncier',
      'Le LMNP (Loueur Meublé Non Professionnel)',
      'Le régime micro-BIC',
    ],
    correctIndex: 2,
    explanation: 'Le LMNP au régime réel permet de déduire les charges ET l\'amortissement du bien et du mobilier, réduisant souvent le résultat imposable à zéro les premières années.',
    difficulty: 'medium',
  },
  {
    id: 'pf-q13',
    lessonId: 'pf-10',
    question: 'Quel est le taux d\'endettement maximum fixé par le HCSF pour un crédit immobilier ?',
    options: ['25%', '30%', '33%', '35%'],
    correctIndex: 3,
    explanation: 'Le HCSF limite le taux d\'endettement à 35% des revenus nets pour les crédits immobiliers, avec une durée maximale de 25 ans (27 ans dans le neuf).',
    difficulty: 'easy',
  },
  {
    id: 'pf-q14',
    lessonId: 'pf-11',
    question: 'Quel est le taux de la flat tax (PFU) en France ?',
    options: ['17.2%', '25%', '30%', '33%'],
    correctIndex: 2,
    explanation: 'La flat tax (Prélèvement Forfaitaire Unique) est de 30% : 12.8% d\'impôt sur le revenu + 17.2% de prélèvements sociaux. Elle s\'applique aux revenus du capital.',
    difficulty: 'easy',
  },
  {
    id: 'pf-q15',
    lessonId: 'pf-12',
    question: 'Quel est l\'abattement en succession via l\'assurance-vie pour les versements effectués avant 70 ans ?',
    options: [
      '100 000€ par bénéficiaire',
      '152 500€ par bénéficiaire',
      '200 000€ par bénéficiaire',
      '500 000€ au total',
    ],
    correctIndex: 1,
    explanation: 'Pour les versements effectués avant 70 ans, l\'assurance-vie offre un abattement de 152 500€ par bénéficiaire, hors succession. C\'est un outil de transmission très puissant.',
    difficulty: 'medium',
  },
  {
    id: 'pf-q16',
    lessonId: 'pf-13',
    question: 'Selon les études, combien de rendement annuel l\'investisseur moyen perd-il par rapport au marché à cause du market timing ?',
    options: ['1% par an', '2% par an', '3-4% par an', '5-6% par an'],
    correctIndex: 2,
    explanation: 'Les études Dalbar montrent que l\'investisseur moyen gagne 3-4% de moins que le marché par an, principalement à cause du market timing (acheter après la hausse, vendre après la baisse).',
    difficulty: 'hard',
  },
];
