// ──────────────────────────────────────────────
//  FINA - Crypto & Blockchain : Quiz
// ──────────────────────────────────────────────

import type { QuizQuestion } from '../types';

export const cryptoQuiz: QuizQuestion[] = [
  {
    id: 'crypto-q1',
    lessonId: 'crypto-1',
    question: 'Quelle propriété rend la blockchain immuable ?',
    options: [
      'Le chiffrement des données',
      'Le hash cryptographique liant chaque bloc au précédent',
      'La vitesse de traitement',
      'Le nombre de nœuds',
    ],
    correctIndex: 1,
    explanation: 'Chaque bloc contient le hash du bloc précédent. Modifier un bloc changerait son hash, invalidant toute la chaîne suivante.',
    difficulty: 'easy',
  },
  {
    id: 'crypto-q2',
    lessonId: 'crypto-2',
    question: 'Quelle est l\'offre maximale de Bitcoin ?',
    options: ['10 millions', '21 millions', '100 millions', 'Illimitée'],
    correctIndex: 1,
    explanation: 'L\'offre de Bitcoin est plafonnée à 21 millions d\'unités, programmée dans le protocole. Le dernier BTC sera miné vers 2140.',
    difficulty: 'easy',
  },
  {
    id: 'crypto-q3',
    lessonId: 'crypto-2',
    question: 'Qu\'est-ce que le halving de Bitcoin ?',
    options: [
      'La division du prix par deux',
      'La réduction de moitié de la récompense de minage tous les ~4 ans',
      'Le fractionnement d\'un BTC en deux',
      'La mise à jour du protocole',
    ],
    correctIndex: 1,
    explanation: 'Le halving réduit de 50% la récompense des mineurs tous les ~210 000 blocs (~4 ans), créant une raréfaction programmée de l\'offre.',
    difficulty: 'easy',
  },
  {
    id: 'crypto-q4',
    lessonId: 'crypto-3',
    question: 'Quelle réduction de consommation énergétique Ethereum a-t-il réalisée en passant au PoS (The Merge) ?',
    options: ['~50%', '~80%', '~95%', '~99.95%'],
    correctIndex: 3,
    explanation: 'The Merge (septembre 2022) a réduit la consommation d\'Ethereum de ~99.95%, passant de la puissance de calcul (PoW) au staking de capital (PoS).',
    difficulty: 'medium',
  },
  {
    id: 'crypto-q5',
    lessonId: 'crypto-4',
    question: 'Qu\'est-ce qu\'un smart contract ?',
    options: [
      'Un contrat juridique signé électroniquement',
      'Un programme auto-exécutable déployé sur la blockchain',
      'Un accord entre deux exchanges',
      'Une licence logicielle',
    ],
    correctIndex: 1,
    explanation: 'Un smart contract est un programme stocké sur la blockchain dont l\'exécution est automatique et garantie par le réseau, sans intermédiaire.',
    difficulty: 'easy',
  },
  {
    id: 'crypto-q6',
    lessonId: 'crypto-5',
    question: 'Quel standard Ethereum définit les tokens fongibles ?',
    options: ['ERC-721', 'ERC-20', 'ERC-1155', 'ERC-4626'],
    correctIndex: 1,
    explanation: 'ERC-20 est le standard pour les tokens fongibles (interchangeables) sur Ethereum. ERC-721 est le standard pour les NFT (non fongibles).',
    difficulty: 'easy',
  },
  {
    id: 'crypto-q7',
    lessonId: 'crypto-6',
    question: 'Quel événement a démontré la fragilité des stablecoins algorithmiques ?',
    options: [
      'Le hack de Mt. Gox (2014)',
      'Le crash UST/Luna (mai 2022)',
      'Le halving de Bitcoin (2024)',
      'Le depeg de l\'USDT (2019)',
    ],
    correctIndex: 1,
    explanation: 'Le crash de UST/Luna en mai 2022 a vaporisé ~40 Md$ en quelques jours, révélant la fragilité des mécanismes algorithmiques de maintien du peg.',
    difficulty: 'medium',
  },
  {
    id: 'crypto-q8',
    lessonId: 'crypto-7',
    question: 'Que mesure le TVL (Total Value Locked) en DeFi ?',
    options: [
      'Le volume de trading quotidien',
      'La valeur totale des actifs déposés dans les protocoles DeFi',
      'Le nombre total de transactions',
      'La capitalisation des tokens DeFi',
    ],
    correctIndex: 1,
    explanation: 'Le TVL mesure la valeur totale des actifs déposés (verrouillés) dans les smart contracts des protocoles DeFi. C\'est l\'indicateur de taille de l\'écosystème.',
    difficulty: 'easy',
  },
  {
    id: 'crypto-q9',
    lessonId: 'crypto-8',
    question: 'Sur Aave, que se passe-t-il quand le Health Factor d\'un emprunteur tombe en dessous de 1 ?',
    options: [
      'Le taux d\'intérêt augmente',
      'Le prêt est automatiquement remboursé',
      'La position est liquidée (le collatéral est vendu)',
      'Le compte est bloqué pendant 24h',
    ],
    correctIndex: 2,
    explanation: 'Si le Health Factor < 1, n\'importe qui peut liquider la position : le collatéral est vendu pour rembourser le prêt, avec un bonus de 5-10% pour le liquidateur.',
    difficulty: 'medium',
  },
  {
    id: 'crypto-q10',
    lessonId: 'crypto-9',
    question: 'Quelle formule utilise l\'AMM d\'Uniswap pour déterminer les prix ?',
    options: [
      'x + y = k',
      'x × y = k',
      'x / y = k',
      'x² + y² = k',
    ],
    correctIndex: 1,
    explanation: 'Uniswap utilise la formule du produit constant x × y = k, où x et y sont les réserves de chaque token dans le pool. Le prix est déterminé par le ratio y/x.',
    difficulty: 'medium',
  },
  {
    id: 'crypto-q11',
    lessonId: 'crypto-10',
    question: 'Qu\'est-ce que l\'impermanent loss pour un fournisseur de liquidité ?',
    options: [
      'La perte due aux frais de gas',
      'La perte par rapport au simple holding quand les prix des tokens divergent',
      'La perte en cas de hack du protocole',
      'La dépréciation du token de gouvernance',
    ],
    correctIndex: 1,
    explanation: 'L\'impermanent loss est la différence de valeur entre fournir de la liquidité et simplement détenir les tokens. Elle survient quand le prix d\'un token diverge par rapport à l\'entrée.',
    difficulty: 'hard',
  },
  {
    id: 'crypto-q12',
    lessonId: 'crypto-12',
    question: 'Que signifie un ratio MC/FDV de 20% pour un token ?',
    options: [
      'Le token est sous-évalué de 80%',
      '80% de l\'offre totale n\'est pas encore en circulation (risque de dilution)',
      'Le protocole a 20% de part de marché',
      'Les frais représentent 20% des revenus',
    ],
    correctIndex: 1,
    explanation: 'MC/FDV = 20% signifie que seuls 20% des tokens sont en circulation. Les 80% restants seront progressivement débloqués (vesting), créant une pression vendeuse potentielle.',
    difficulty: 'hard',
  },
  {
    id: 'crypto-q13',
    lessonId: 'crypto-13',
    question: 'Sous MiCA, qu\'est-ce qu\'un EMT (e-money token) ?',
    options: [
      'Un token de gouvernance',
      'Un stablecoin adossé à une seule monnaie fiat',
      'Un token non fongible',
      'Un token de récompense de minage',
    ],
    correctIndex: 1,
    explanation: 'Un EMT (Electronic Money Token) est un stablecoin adossé à une seule monnaie fiat (ex : USDC adossé au dollar). Sous MiCA, il doit être émis par un établissement agréé.',
    difficulty: 'medium',
  },
  {
    id: 'crypto-q14',
    lessonId: 'crypto-14',
    question: 'Quel principe résume l\'enjeu de custody en crypto ?',
    options: [
      'Buy the dip',
      'Not your keys, not your coins',
      'Don\'t trust, verify',
      'HODL',
    ],
    correctIndex: 1,
    explanation: '« Not your keys, not your coins » : si vous ne détenez pas la clé privée (self-custody), c\'est le dépositaire qui contrôle vos actifs. Le cas FTX l\'a douloureusement illustré.',
    difficulty: 'easy',
  },
  {
    id: 'crypto-q15',
    lessonId: 'crypto-15',
    question: 'Quel ratio permet de comparer la valorisation d\'un protocole DeFi à ses revenus ?',
    options: [
      'P/TVL',
      'P/Revenue (Market Cap / Revenus annuels)',
      'TVL/Users',
      'FDV/MC',
    ],
    correctIndex: 1,
    explanation: 'P/Revenue = Market Cap / Revenus annuels du protocole. C\'est l\'équivalent du PER en finance traditionnelle, adapté aux protocoles DeFi.',
    difficulty: 'medium',
  },
  {
    id: 'crypto-q16',
    lessonId: 'crypto-16',
    question: 'Quel événement de 2022 a conduit à la faillite de FTX et à la perte de 8 Md$ de fonds clients ?',
    options: [
      'Un hack de smart contract',
      'L\'utilisation des fonds clients pour combler les pertes d\'Alameda Research',
      'Un crash de Bitcoin',
      'Une attaque 51% sur Ethereum',
    ],
    correctIndex: 1,
    explanation: 'FTX a détourné les fonds de ses clients pour couvrir les pertes de trading de sa filiale Alameda Research, entraînant une perte de 8 Md$ et la condamnation de son fondateur.',
    difficulty: 'medium',
  },
];
