// ──────────────────────────────────────────────
//  FINA - Finance Immobilière : Quiz
// ──────────────────────────────────────────────

import type { QuizQuestion } from '../types';

export const realEstateQuiz: QuizQuestion[] = [
  {
    id: 're-q1',
    lessonId: 're-1',
    question: 'Quelles sont les deux sources de rendement d\'un investissement immobilier ?',
    options: [
      'Dividendes et coupons',
      'Revenus locatifs et plus-value en capital',
      'Commissions et frais de gestion',
      'Intérêts et prime de risque',
    ],
    correctIndex: 1,
    explanation: 'Le rendement immobilier provient des revenus locatifs (income return) et de l\'appréciation du capital (capital return) à la revente.',
    difficulty: 'easy',
  },
  {
    id: 're-q2',
    lessonId: 're-2',
    question: 'Quel segment immobilier a le plus bénéficié du boom du e-commerce ?',
    options: ['Bureaux', 'Commerce de centre-ville', 'Logistique', 'Résidentiel'],
    correctIndex: 2,
    explanation: 'La logistique (entrepôts, centres de distribution, « last mile ») a fortement bénéficié de la croissance du e-commerce.',
    difficulty: 'easy',
  },
  {
    id: 're-q3',
    lessonId: 're-3',
    question: 'Dans un DCF immobilier, comment calcule-t-on la valeur terminale ?',
    options: [
      'En multipliant le loyer par 10',
      'En appliquant un exit cap rate au NOI de la dernière année',
      'En divisant le prix d\'achat par la durée',
      'En actualisant les frais de gestion',
    ],
    correctIndex: 1,
    explanation: 'La valeur terminale = NOI de la dernière année (ou année suivante) divisé par le taux de capitalisation de sortie (exit cap rate).',
    difficulty: 'medium',
  },
  {
    id: 're-q4',
    lessonId: 're-4',
    question: 'Comment calcule-t-on le cap rate ?',
    options: [
      'Loyer brut / Surface',
      'NOI / Valeur du bien',
      'Valeur du bien / NOI',
      'Loyer net / Charges',
    ],
    correctIndex: 1,
    explanation: 'Cap rate = NOI (Net Operating Income) / Valeur du bien. Plus le cap rate est bas, plus l\'actif est cher (à NOI constant).',
    difficulty: 'easy',
  },
  {
    id: 're-q5',
    lessonId: 're-4',
    question: 'Que se passe-t-il quand les cap rates se compriment ?',
    options: [
      'Les valeurs immobilières baissent',
      'Les valeurs immobilières augmentent',
      'Les loyers diminuent',
      'Les charges augmentent',
    ],
    correctIndex: 1,
    explanation: 'Compression de cap rate = les valeurs augmentent (Valeur = NOI / cap rate). Si le cap rate baisse de 5% à 4.5%, la valeur monte de ~11%.',
    difficulty: 'medium',
  },
  {
    id: 're-q6',
    lessonId: 're-5',
    question: 'Que le NOI exclut-il ?',
    options: [
      'Les charges de copropriété',
      'La taxe foncière',
      'Le service de la dette et l\'amortissement',
      'L\'assurance du propriétaire',
    ],
    correctIndex: 2,
    explanation: 'Le NOI exclut le service de la dette, l\'amortissement et les impôts. C\'est un indicateur de performance opérationnelle, avant financement.',
    difficulty: 'medium',
  },
  {
    id: 're-q7',
    lessonId: 're-6',
    question: 'Quand le levier financier est-il « positif » en immobilier ?',
    options: [
      'Quand le LTV est inférieur à 50%',
      'Quand le cap rate est supérieur au coût de la dette',
      'Quand le DSCR est supérieur à 2x',
      'Quand le bien est neuf',
    ],
    correctIndex: 1,
    explanation: 'Le levier est positif quand le rendement de l\'actif (cap rate) dépasse le coût de la dette. Le cash-on-cash return est alors supérieur au cap rate.',
    difficulty: 'medium',
  },
  {
    id: 're-q8',
    lessonId: 're-7',
    question: 'Quelle est la couche de financement la plus risquée dans la structure de capital immobilière ?',
    options: [
      'La dette senior',
      'La dette mezzanine',
      'L\'equity',
      'Le prêt hypothécaire',
    ],
    correctIndex: 2,
    explanation: 'L\'equity absorbe les premières pertes et est la dernière remboursée en cas de défaut. C\'est la couche la plus risquée, qui exige le rendement le plus élevé (IRR 8-20%).',
    difficulty: 'easy',
  },
  {
    id: 're-q9',
    lessonId: 're-8',
    question: 'Un bien vaut 50 M€ avec un LTV max de 65% et un NOI de 3 M€ avec un DSCR min de 1.3x. La contrainte d\'annuité max est 2.31 M€, soit ~34 M€ de dette. Quelle est la contrainte active ?',
    options: [
      'Le DSCR (34 M€)',
      'Le LTV (32.5 M€)',
      'Les deux sont identiques',
      'Aucune, le bien n\'est pas finançable',
    ],
    correctIndex: 1,
    explanation: 'LTV max → 50 × 65% = 32.5 M€. DSCR max → ~34 M€. Le prêteur retient le minimum : 32.5 M€ (contrainte LTV).',
    difficulty: 'hard',
  },
  {
    id: 're-q10',
    lessonId: 're-9',
    question: 'Quelle obligation distingue un REIT (ou SIIC en France) d\'une société immobilière classique ?',
    options: [
      'L\'obligation d\'investir uniquement en bureaux',
      'L\'obligation de distribuer la quasi-totalité de ses bénéfices',
      'L\'interdiction d\'emprunter',
      'L\'obligation d\'être cotée au CAC 40',
    ],
    correctIndex: 1,
    explanation: 'Un REIT doit distribuer ≥ 90% de ses bénéfices (US) ou 95% de ses loyers (SIIC France) en échange de la transparence fiscale (pas d\'IS).',
    difficulty: 'easy',
  },
  {
    id: 're-q11',
    lessonId: 're-10',
    question: 'Qu\'est-ce que le FFO (Funds From Operations) d\'un REIT ?',
    options: [
      'Le chiffre d\'affaires du REIT',
      'Le résultat net + amortissements − plus-values de cession',
      'Les dividendes versés aux actionnaires',
      'La trésorerie disponible',
    ],
    correctIndex: 1,
    explanation: 'Le FFO = Résultat net + Amortissements − Plus-values de cession. Il mesure le cash-flow opérationnel récurrent du REIT.',
    difficulty: 'medium',
  },
  {
    id: 're-q12',
    lessonId: 're-11',
    question: 'Quel est le principal avantage de la SCPI par rapport à l\'immobilier direct ?',
    options: [
      'Un rendement toujours supérieur',
      'L\'absence de fiscalité',
      'L\'accessibilité (ticket d\'entrée faible) et l\'absence de gestion',
      'La garantie en capital',
    ],
    correctIndex: 2,
    explanation: 'La SCPI permet d\'investir en immobilier avec un ticket faible (quelques centaines d\'euros) sans gérer les locataires ni les travaux. Les revenus sont versés comme des dividendes.',
    difficulty: 'easy',
  },
  {
    id: 're-q13',
    lessonId: 're-12',
    question: 'En promotion immobilière, qu\'est-ce que la VEFA ?',
    options: [
      'Valorisation Estimative des Fonds Alloués',
      'Vente en l\'État Futur d\'Achèvement',
      'Vérification Externe des Financements Autorisés',
      'Valeur Économique du Foncier Aménagé',
    ],
    correctIndex: 1,
    explanation: 'La VEFA (Vente en l\'État Futur d\'Achèvement) permet au promoteur de vendre les logements avant la fin de la construction, sécurisant le financement.',
    difficulty: 'easy',
  },
  {
    id: 're-q14',
    lessonId: 're-14',
    question: 'Pourquoi le cycle immobilier est-il décalé par rapport au cycle économique ?',
    options: [
      'Les taux d\'intérêt réagissent en retard',
      'Le temps de construction (2-5 ans) crée un décalage entre la décision et la livraison',
      'Les investisseurs immobiliers sont plus prudents',
      'La réglementation impose des délais',
    ],
    correctIndex: 1,
    explanation: 'Le délai de construction (2-5 ans) crée un décalage : quand les projets lancés en période d\'expansion sont livrés, le marché peut déjà avoir ralenti, créant une offre excédentaire.',
    difficulty: 'medium',
  },
  {
    id: 're-q15',
    lessonId: 're-15',
    question: 'Un immeuble a un NOI de 870 K€ et un prix de 15 M€. Quel est le cap rate going-in ?',
    options: ['4.2%', '5.8%', '6.5%', '7.2%'],
    correctIndex: 1,
    explanation: 'Cap rate = NOI / Prix = 870 000 / 15 000 000 = 5.8%.',
    difficulty: 'easy',
  },
  {
    id: 're-q16',
    lessonId: 're-16',
    question: 'Quel indicateur mesure le rendement sur l\'apport personnel de l\'investisseur après service de la dette ?',
    options: ['Cap rate', 'NOI yield', 'Cash-on-cash return', 'IRR'],
    correctIndex: 2,
    explanation: 'Le cash-on-cash return = (NOI − Service de la dette) / Equity investie. C\'est le rendement annuel sur l\'apport en fonds propres.',
    difficulty: 'medium',
  },
];
