// ──────────────────────────────────────────────
//  FINA - Macroéconomie : Quiz Questions
// ──────────────────────────────────────────────

import type { QuizQuestion } from '@/types/content';

export const macroQuiz: QuizQuestion[] = [
  // ── Lesson 1 : PIB & croissance ──
  {
    id: 'macro-1-q1',
    lessonId: 'macro-1',
    question: 'La formule du PIB par les dépenses est :',
    options: ['PIB = C + I + G', 'PIB = C + I + G + (X - M)', 'PIB = C + S + T', 'PIB = Y - T + G'],
    correctIndex: 1,
    explanation: 'PIB = Consommation (C) + Investissement (I) + Dépenses publiques (G) + Exportations nettes (X - M).',
    difficulty: 'easy',
  },
  {
    id: 'macro-1-q2',
    lessonId: 'macro-1',
    question: 'Le PIB réel diffère du PIB nominal car il :',
    options: [
      'Inclut les exportations',
      'Corrige de l\'effet de l\'inflation (prix constants)',
      'Mesure uniquement les services',
      'Est toujours plus élevé que le nominal',
    ],
    correctIndex: 1,
    explanation: 'Le PIB réel mesure le volume de production à prix constants, éliminant l\'effet de la hausse des prix pour refléter la croissance réelle.',
    difficulty: 'easy',
  },
  {
    id: 'macro-1-q3',
    lessonId: 'macro-1',
    question: 'Un output gap négatif signifie :',
    options: [
      'L\'économie est en surchauffe',
      'Le PIB effectif est supérieur au PIB potentiel',
      'L\'économie est en sous-capacité avec du chômage involontaire',
      'L\'inflation est trop élevée',
    ],
    correctIndex: 2,
    explanation: 'Un output gap négatif indique que le PIB effectif est inférieur au potentiel : des ressources (travail, capital) sont sous-utilisées.',
    difficulty: 'medium',
  },
  {
    id: 'macro-1-q4',
    lessonId: 'macro-1',
    question: 'En France, la consommation des ménages représente environ ____ du PIB :',
    options: ['25 %', '40 %', '55 %', '75 %'],
    correctIndex: 2,
    explanation: 'La consommation des ménages est la composante la plus importante du PIB français, représentant environ 55 %.',
    difficulty: 'medium',
  },
  {
    id: 'macro-1-q5',
    lessonId: 'macro-1',
    question: 'Pour les marchés financiers, ce qui compte le plus n\'est pas le niveau du PIB mais :',
    options: [
      'Le PIB nominal uniquement',
      'La surprise par rapport aux attentes du consensus',
      'Le PIB des pays voisins',
      'Le PIB de l\'année précédente',
    ],
    correctIndex: 1,
    explanation: 'Les marchés anticipent les données. C\'est l\'écart entre le chiffre publié et le consensus (la surprise) qui fait bouger les cours.',
    difficulty: 'medium',
  },

  // ── Lesson 2 : Inflation ──
  {
    id: 'macro-2-q1',
    lessonId: 'macro-2',
    question: 'L\'IPC core (sous-jacent) exclut :',
    options: [
      'Les services et l\'immobilier',
      'L\'alimentation et l\'énergie',
      'Les biens durables',
      'Les impôts indirects',
    ],
    correctIndex: 1,
    explanation: 'L\'IPC core exclut les composantes alimentaire et énergétique, trop volatiles, pour mieux refléter la tendance de fond de l\'inflation.',
    difficulty: 'easy',
  },
  {
    id: 'macro-2-q2',
    lessonId: 'macro-2',
    question: 'La BCE cible une inflation de :',
    options: ['0 %', '1 %', '2 % à moyen terme', '5 %'],
    correctIndex: 2,
    explanation: 'La BCE cible une inflation de 2 % à moyen terme, considérée comme compatible avec la stabilité des prix.',
    difficulty: 'easy',
  },
  {
    id: 'macro-2-q3',
    lessonId: 'macro-2',
    question: 'L\'inflation "demand-pull" survient quand :',
    options: [
      'Les coûts de production augmentent',
      'La demande globale excède l\'offre disponible',
      'La monnaie se déprécie',
      'Le pétrole augmente',
    ],
    correctIndex: 1,
    explanation: 'L\'inflation par la demande (demand-pull) résulte d\'un excès de demande par rapport à l\'offre, typiquement en phase de surchauffe économique.',
    difficulty: 'medium',
  },
  {
    id: 'macro-2-q4',
    lessonId: 'macro-2',
    question: 'Les anticipations d\'inflation du marché se mesurent par :',
    options: [
      'Le PIB nominal',
      'Les break-even inflation rates (écart nominal vs indexé)',
      'Le taux de chômage',
      'Le cours du pétrole',
    ],
    correctIndex: 1,
    explanation: 'Le break-even inflation rate = taux nominal - taux réel (TIPS/OATi). Il reflète l\'inflation moyenne anticipée par le marché sur la durée de l\'obligation.',
    difficulty: 'medium',
  },
  {
    id: 'macro-2-q5',
    lessonId: 'macro-2',
    question: 'Le risque déflationniste est une spirale où :',
    options: [
      'Les prix montent trop vite',
      'La baisse des prix pousse à reporter les achats, réduisant la demande et accentuant la baisse des prix',
      'Les salaires augmentent trop vite',
      'Les exportations augmentent',
    ],
    correctIndex: 1,
    explanation: 'La déflation crée un cercle vicieux : baisse des prix → report d\'achats → baisse de la demande → baisse des prix. C\'est pourquoi les banques centrales la redoutent.',
    difficulty: 'hard',
  },

  // ── Lesson 3 : Politique monétaire ──
  {
    id: 'macro-3-q1',
    lessonId: 'macro-3',
    question: 'Le taux directeur de la Fed s\'appelle :',
    options: ['Le LIBOR', 'Le fed funds rate', 'L\'Euribor', 'Le taux de refinancement'],
    correctIndex: 1,
    explanation: 'Le taux directeur de la Fed est le fed funds rate, le taux auquel les banques se prêtent des réserves au jour le jour.',
    difficulty: 'easy',
  },
  {
    id: 'macro-3-q2',
    lessonId: 'macro-3',
    question: 'La règle de Taylor prescrit un taux directeur de ____ si r* = 2 %, π = 4 %, π* = 2 %, output gap = 0 :',
    options: ['4 %', '5 %', '7 %', '8 %'],
    correctIndex: 2,
    explanation: 'i = r* + π + 0,5(π-π*) + 0,5(y-y*) = 2 + 4 + 0,5×(4-2) + 0,5×0 = 2 + 4 + 1 + 0 = 7 %.',
    difficulty: 'hard',
  },
  {
    id: 'macro-3-q3',
    lessonId: 'macro-3',
    question: 'Le canal des prix d\'actifs fonctionne car des taux bas :',
    options: [
      'Réduisent les prix des actifs',
      'Font monter les prix des actions et de l\'immobilier via l\'actualisation',
      'N\'ont aucun effet sur les prix d\'actifs',
      'Font baisser les salaires',
    ],
    correctIndex: 1,
    explanation: 'Des taux bas réduisent le taux d\'actualisation des flux futurs, augmentant la valeur présente des actions et de l\'immobilier (effet richesse).',
    difficulty: 'medium',
  },
  {
    id: 'macro-3-q4',
    lessonId: 'macro-3',
    question: 'Le mandat de la BCE est :',
    options: [
      'Un double mandat (prix + emploi)',
      'Un mandat unique : la stabilité des prix',
      'La croissance du PIB uniquement',
      'La stabilité du taux de change',
    ],
    correctIndex: 1,
    explanation: 'Contrairement à la Fed (double mandat), la BCE a un mandat principal unique : maintenir la stabilité des prix (inflation proche de 2 %).',
    difficulty: 'medium',
  },
  {
    id: 'macro-3-q5',
    lessonId: 'macro-3',
    question: 'Entre mars 2022 et juillet 2023, la Fed a relevé ses taux de :',
    options: ['100 bps', '250 bps', '525 bps', '750 bps'],
    correctIndex: 2,
    explanation: 'La Fed est passée de 0-0,25 % à 5,25-5,50 %, soit une hausse cumulée de 525 bps en 16 mois, le rythme le plus rapide depuis Volcker.',
    difficulty: 'hard',
  },

  // ── Lesson 4 : QE ──
  {
    id: 'macro-4-q1',
    lessonId: 'macro-4',
    question: 'Le QE intervient principalement quand :',
    options: [
      'L\'inflation est trop élevée',
      'Les taux directeurs atteignent le Zero Lower Bound',
      'Le marché actions est en hausse',
      'Le PIB croît fortement',
    ],
    correctIndex: 1,
    explanation: 'Le QE est une politique non conventionnelle utilisée quand les taux directeurs sont à zéro (ou négatifs) et ne peuvent plus baisser.',
    difficulty: 'easy',
  },
  {
    id: 'macro-4-q2',
    lessonId: 'macro-4',
    question: 'Le bilan de la Fed est passé de ~900 Mds$ en 2008 à ____ en 2022 :',
    options: ['2 000 Mds$', '5 000 Mds$', '9 000 Mds$', '15 000 Mds$'],
    correctIndex: 2,
    explanation: 'Le bilan de la Fed a été multiplié par 10, passant de 900 Mds$ avant la crise à environ 9 000 Mds$ au pic en 2022.',
    difficulty: 'medium',
  },
  {
    id: 'macro-4-q3',
    lessonId: 'macro-4',
    question: 'L\'effet de portefeuille du QE signifie que :',
    options: [
      'Les investisseurs vendent leurs actions',
      'En absorbant les obligations souveraines, la banque centrale force les investisseurs vers des actifs plus risqués',
      'Les investisseurs achètent davantage d\'obligations',
      'Les taux longs augmentent',
    ],
    correctIndex: 1,
    explanation: 'Le QE absorbe les obligations sûres, forçant les investisseurs à chercher du rendement dans le crédit, les actions et l\'immobilier, comprimant les primes de risque.',
    difficulty: 'medium',
  },
  {
    id: 'macro-4-q4',
    lessonId: 'macro-4',
    question: 'Le "taper tantrum" de 2013 fait référence à :',
    options: [
      'L\'augmentation du QE',
      'La réaction violente des marchés à l\'annonce de la réduction du QE',
      'La faillite d\'une banque',
      'Une crise de la dette souveraine',
    ],
    correctIndex: 1,
    explanation: 'En mai 2013, Bernanke suggère de réduire le QE. Les marchés obligataires chutent brutalement (les taux US 10Y passent de 1,6 % à 3 %), illustrant la dépendance au QE.',
    difficulty: 'medium',
  },
  {
    id: 'macro-4-q5',
    lessonId: 'macro-4',
    question: 'Une critique majeure du QE est :',
    options: [
      'Il réduit trop l\'inflation',
      'Il augmente les inégalités en enrichissant davantage les propriétaires d\'actifs',
      'Il réduit la masse monétaire',
      'Il renforce la monnaie nationale',
    ],
    correctIndex: 1,
    explanation: 'Le QE fait monter les prix des actifs (actions, immobilier), bénéficiant surtout aux plus riches qui en possèdent, aggravant les inégalités de patrimoine.',
    difficulty: 'hard',
  },

  // ── Lesson 5 : Forward guidance ──
  {
    id: 'macro-5-q1',
    lessonId: 'macro-5',
    question: 'Le forward guidance date-based fixe :',
    options: [
      'Un seuil de chômage',
      'Un horizon temporel ("taux bas au moins jusqu\'en 2024")',
      'Un taux de change cible',
      'Un niveau du PIB',
    ],
    correctIndex: 1,
    explanation: 'Le forward guidance date-based engage la banque centrale sur une date précise, permettant aux marchés d\'ancrer leurs anticipations de taux.',
    difficulty: 'easy',
  },
  {
    id: 'macro-5-q2',
    lessonId: 'macro-5',
    question: 'Le "dot plot" de la Fed est :',
    options: [
      'Un graphique de l\'inflation',
      'Les projections de taux de chaque membre du FOMC',
      'Le bilan de la Fed',
      'Le compte de résultat de la Fed',
    ],
    correctIndex: 1,
    explanation: 'Le dot plot montre les projections de taux de chaque membre du FOMC (sans les nommer), publié trimestriellement.',
    difficulty: 'easy',
  },
  {
    id: 'macro-5-q3',
    lessonId: 'macro-5',
    question: 'Le forward guidance repose sur la théorie selon laquelle :',
    options: [
      'Les taux longs sont fixés par la banque centrale',
      'Les taux longs reflètent les anticipations de taux courts futurs',
      'Les taux longs sont indépendants des taux courts',
      'Les taux longs sont toujours supérieurs aux taux courts',
    ],
    correctIndex: 1,
    explanation: 'La théorie des anticipations dit que les taux longs sont la moyenne des taux courts anticipés. En guidant ces anticipations, la banque centrale influence les taux longs.',
    difficulty: 'medium',
  },
  {
    id: 'macro-5-q4',
    lessonId: 'macro-5',
    question: 'La Fed a qualifié l\'inflation de "transitoire" en 2021 puis :',
    options: [
      'L\'inflation a effectivement disparu rapidement',
      'A dû resserrer agressivement, perdant de la crédibilité sur le forward guidance',
      'A maintenu les taux à zéro indéfiniment',
      'A augmenté le QE',
    ],
    correctIndex: 1,
    explanation: 'L\'erreur de diagnostic "transitoire" a forcé la Fed à resserrer de manière urgente en 2022, entamant la crédibilité de son forward guidance.',
    difficulty: 'medium',
  },
  {
    id: 'macro-5-q5',
    lessonId: 'macro-5',
    question: 'Le risque principal du forward guidance est :',
    options: [
      'Il coûte trop cher',
      'La perte de crédibilité si les engagements ne sont pas tenus',
      'Il n\'a aucun effet sur les marchés',
      'Il augmente la volatilité des taux courts',
    ],
    correctIndex: 1,
    explanation: 'Si la banque centrale ne tient pas ses engagements de forward guidance, les marchés cessent de croire ses communications futures, rendant l\'outil inefficace.',
    difficulty: 'medium',
  },

  // ── Lesson 6 : Courbe des taux ──
  {
    id: 'macro-6-q1',
    lessonId: 'macro-6',
    question: 'Une courbe des taux "normale" est :',
    options: [
      'Plate',
      'Inversée (taux courts > taux longs)',
      'Croissante (taux longs > taux courts)',
      'En forme de U',
    ],
    correctIndex: 2,
    explanation: 'Une courbe normale est croissante : les taux longs sont supérieurs aux taux courts, reflétant la prime de terme positive.',
    difficulty: 'easy',
  },
  {
    id: 'macro-6-q2',
    lessonId: 'macro-6',
    question: 'La prime de terme compense :',
    options: [
      'Le risque de change',
      'L\'incertitude et le risque de duration des maturités longues',
      'Le risque de défaut uniquement',
      'L\'impôt sur le revenu',
    ],
    correctIndex: 1,
    explanation: 'La prime de terme rémunère les investisseurs pour le risque supplémentaire lié à la détention d\'obligations à long terme (risque de taux et incertitude).',
    difficulty: 'medium',
  },
  {
    id: 'macro-6-q3',
    lessonId: 'macro-6',
    question: 'Le taux forward 1 an dans 2 ans se calcule comme :',
    options: [
      'r_3 - r_2',
      '[(1+r_3)³/(1+r_2)²] - 1',
      'r_3 × r_2',
      '(r_3 + r_2) / 2',
    ],
    correctIndex: 1,
    explanation: 'f(2,3) = [(1+r_3)³/(1+r_2)²] - 1. C\'est le taux qui rend l\'investissement sur 3 ans équivalent à 2 ans + 1 an à terme.',
    difficulty: 'hard',
  },
  {
    id: 'macro-6-q4',
    lessonId: 'macro-6',
    question: 'Les obligations de référence pour la courbe US sont :',
    options: [
      'Les corporate bonds',
      'Les Treasury securities (Treasuries)',
      'Les mortgage-backed securities',
      'Les obligations municipales',
    ],
    correctIndex: 1,
    explanation: 'La courbe des taux souveraine US est construite à partir des rendements des Treasury securities, considérées comme sans risque de défaut.',
    difficulty: 'easy',
  },
  {
    id: 'macro-6-q5',
    lessonId: 'macro-6',
    question: 'Le modèle ACM de la Fed de New York décompose le taux 10 ans en :',
    options: [
      'Taux réel et inflation',
      'Taux court moyen anticipé et prime de terme',
      'Risque de défaut et rendement',
      'Duration et convexité',
    ],
    correctIndex: 1,
    explanation: 'Le modèle ACM (Adrian, Crump, Moench) décompose le taux long en deux composantes : les anticipations moyennes de taux courts futurs et la prime de terme.',
    difficulty: 'hard',
  },

  // ── Lesson 7 : Inversion ──
  {
    id: 'macro-7-q1',
    lessonId: 'macro-7',
    question: 'L\'inversion de la courbe des taux a précédé ____ des récessions US depuis 1955 :',
    options: ['50 %', '75 %', 'Toutes (avec un seul faux signal)', '25 %'],
    correctIndex: 2,
    explanation: 'L\'inversion du spread 2Y-10Y a précédé chaque récession américaine depuis 1955, avec un seul faux signal, ce qui en fait l\'indicateur le plus fiable.',
    difficulty: 'medium',
  },
  {
    id: 'macro-7-q2',
    lessonId: 'macro-7',
    question: 'Le délai médian entre l\'inversion et la récession est d\'environ :',
    options: ['1 mois', '6 mois', '14 mois', '3 ans'],
    correctIndex: 2,
    explanation: 'Historiquement, le délai médian entre l\'inversion de la courbe et le début de la récession est d\'environ 14 mois.',
    difficulty: 'medium',
  },
  {
    id: 'macro-7-q3',
    lessonId: 'macro-7',
    question: 'L\'inversion signifie que les marchés anticipent :',
    options: [
      'Une accélération de la croissance',
      'Une hausse de l\'inflation',
      'Un ralentissement économique nécessitant des baisses de taux futures',
      'Une stabilité des taux',
    ],
    correctIndex: 2,
    explanation: 'L\'inversion reflète l\'anticipation que la banque centrale devra baisser drastiquement ses taux pour combattre une récession, tirant les taux longs sous les courts.',
    difficulty: 'medium',
  },
  {
    id: 'macro-7-q4',
    lessonId: 'macro-7',
    question: 'L\'inversion de 2022-2023 a atteint un creux de :',
    options: ['-20 bps', '-50 bps', '-108 bps', '-200 bps'],
    correctIndex: 2,
    explanation: 'L\'inversion du spread 2Y-10Y a atteint -108 bps entre juillet 2022 et octobre 2023, la plus profonde depuis 1981.',
    difficulty: 'hard',
  },
  {
    id: 'macro-7-q5',
    lessonId: 'macro-7',
    question: 'L\'inversion peut aggraver les conditions économiques via :',
    options: [
      'La hausse des salaires',
      'La compression des marges bancaires (emprunts courts, prêts longs)',
      'L\'augmentation des exportations',
      'La baisse du taux de chômage',
    ],
    correctIndex: 1,
    explanation: 'Quand les taux courts > taux longs, les banques (qui empruntent court et prêtent long) voient leurs marges se comprimer, réduisant l\'incitation à prêter.',
    difficulty: 'hard',
  },

  // ── Lesson 8 : Réels vs nominaux ──
  {
    id: 'macro-8-q1',
    lessonId: 'macro-8',
    question: 'L\'approximation de Fisher est :',
    options: [
      'r = i × π',
      'r ≈ i - π',
      'r = i + π',
      'r = π / i',
    ],
    correctIndex: 1,
    explanation: 'L\'approximation de Fisher dit que le taux réel ≈ taux nominal - inflation : r ≈ i - π.',
    difficulty: 'easy',
  },
  {
    id: 'macro-8-q2',
    lessonId: 'macro-8',
    question: 'Les TIPS sont des obligations dont :',
    options: [
      'Le coupon est fixe et le principal aussi',
      'Le principal est indexé sur l\'inflation',
      'Le rendement est toujours négatif',
      'La maturité varie avec l\'inflation',
    ],
    correctIndex: 1,
    explanation: 'Les TIPS (Treasury Inflation-Protected Securities) ont un principal qui s\'ajuste avec l\'inflation. Leur rendement est directement le taux réel du marché.',
    difficulty: 'easy',
  },
  {
    id: 'macro-8-q3',
    lessonId: 'macro-8',
    question: 'Le break-even inflation rate se calcule comme :',
    options: [
      'Taux réel - Taux nominal',
      'Taux nominal - Taux TIPS (réel)',
      'Taux nominal × Taux réel',
      'Inflation passée - Inflation future',
    ],
    correctIndex: 1,
    explanation: 'BEI = Taux nominal - Taux TIPS. C\'est l\'inflation que le marché anticipe en moyenne sur la durée de l\'obligation.',
    difficulty: 'medium',
  },
  {
    id: 'macro-8-q4',
    lessonId: 'macro-8',
    question: 'Des taux réels négatifs signifient que :',
    options: [
      'L\'économie est en récession profonde',
      'L\'argent emprunté rapporte plus que son coût après inflation',
      'Les obligations sont sans risque',
      'L\'inflation est nulle',
    ],
    correctIndex: 1,
    explanation: 'Avec des taux réels négatifs, le coût réel de l\'emprunt est négatif : emprunter est "gratuit" en termes de pouvoir d\'achat, stimulant massivement l\'investissement.',
    difficulty: 'medium',
  },
  {
    id: 'macro-8-q5',
    lessonId: 'macro-8',
    question: 'Le r-star (r*) est :',
    options: [
      'Le taux d\'inflation cible',
      'Le taux réel neutre compatible avec le plein emploi et une inflation stable',
      'Le taux nominal de la Fed',
      'Le taux de croissance du PIB',
    ],
    correctIndex: 1,
    explanation: 'r* (r-star) est le taux d\'intérêt réel à court terme qui ni stimule ni freine l\'économie. Il est estimé entre 0,5 % et 1,5 % par la Fed de New York.',
    difficulty: 'hard',
  },

  // ── Lesson 9 : Marché FX ──
  {
    id: 'macro-9-q1',
    lessonId: 'macro-9',
    question: 'Le volume quotidien du marché des changes est d\'environ :',
    options: ['100 milliards $', '1 000 milliards $', '7 500 milliards $', '50 000 milliards $'],
    correctIndex: 2,
    explanation: 'Le marché FX est le plus grand marché financier du monde avec un volume quotidien d\'environ 7 500 milliards de dollars.',
    difficulty: 'medium',
  },
  {
    id: 'macro-9-q2',
    lessonId: 'macro-9',
    question: 'Le carry trade consiste à :',
    options: [
      'Acheter la devise la plus forte',
      'Emprunter en devise à taux bas et investir en devise à taux élevé',
      'Vendre toutes ses devises',
      'Acheter uniquement de l\'or',
    ],
    correctIndex: 1,
    explanation: 'Le carry trade exploite le différentiel de taux d\'intérêt entre deux devises, mais expose l\'investisseur au risque de change.',
    difficulty: 'medium',
  },
  {
    id: 'macro-9-q3',
    lessonId: 'macro-9',
    question: 'EUR/USD passe de 1,22 à 0,96. L\'euro a :',
    options: [
      'S\'est apprécié de 26 %',
      'S\'est déprécié d\'environ 21 %',
      'Est resté stable',
      'S\'est apprécié de 21 %',
    ],
    correctIndex: 1,
    explanation: '(0,96 - 1,22) / 1,22 = -21,3 %. L\'euro a perdu 21 % de sa valeur par rapport au dollar.',
    difficulty: 'easy',
  },
  {
    id: 'macro-9-q4',
    lessonId: 'macro-9',
    question: 'Le taux forward est calculé par :',
    options: [
      'F = S × r_d / r_f',
      'F = S × (1+r_d) / (1+r_f)',
      'F = S + r_d - r_f',
      'F = S × (r_d - r_f)',
    ],
    correctIndex: 1,
    explanation: 'Le taux forward reflète la parité couverte des taux d\'intérêt : F = S × (1+r_domestique) / (1+r_étranger).',
    difficulty: 'hard',
  },
  {
    id: 'macro-9-q5',
    lessonId: 'macro-9',
    question: 'L\'"original sin" des marchés émergents fait référence à :',
    options: [
      'Le péché d\'Adam et Ève',
      'L\'obligation d\'emprunter en devise forte car les investisseurs ne font pas confiance à leur monnaie',
      'Le premier défaut souverain de l\'histoire',
      'La création des banques centrales',
    ],
    correctIndex: 1,
    explanation: 'Le "péché originel" est l\'incapacité de nombreux pays émergents à emprunter dans leur propre devise, les exposant au risque de change sur leur dette.',
    difficulty: 'hard',
  },

  // ── Lesson 10 : PPP ──
  {
    id: 'macro-10-q1',
    lessonId: 'macro-10',
    question: 'La PPP absolue affirme que :',
    options: [
      'Les taux de change sont fixes',
      'Un panier de biens identique doit coûter le même prix partout une fois converti',
      'Les taux d\'intérêt sont identiques partout',
      'Le PIB est le même partout',
    ],
    correctIndex: 1,
    explanation: 'La PPP absolue est basée sur la loi du prix unique : un panier identique de biens doit avoir le même prix dans tous les pays après conversion.',
    difficulty: 'easy',
  },
  {
    id: 'macro-10-q2',
    lessonId: 'macro-10',
    question: 'L\'indice Big Mac de The Economist illustre :',
    options: [
      'La qualité de la restauration rapide',
      'La PPP en comparant le prix d\'un Big Mac à travers le monde',
      'Le PIB par habitant',
      'Le taux d\'obésité',
    ],
    correctIndex: 1,
    explanation: 'Le Big Mac Index compare le prix d\'un produit standardisé mondialement pour estimer si les devises sont sur- ou sous-évaluées par rapport à la PPP.',
    difficulty: 'easy',
  },
  {
    id: 'macro-10-q3',
    lessonId: 'macro-10',
    question: 'La PPP relative dit que la variation du taux de change reflète :',
    options: [
      'Le différentiel de PIB',
      'Le différentiel d\'inflation entre les deux pays',
      'Le différentiel de population',
      'Le différentiel de superficie',
    ],
    correctIndex: 1,
    explanation: 'La PPP relative : ΔS/S ≈ π_domestique - π_étranger. Si l\'inflation est plus élevée dans un pays, sa devise devrait se déprécier.',
    difficulty: 'medium',
  },
  {
    id: 'macro-10-q4',
    lessonId: 'macro-10',
    question: 'L\'effet Balassa-Samuelson explique pourquoi :',
    options: [
      'Les pays pauvres ont des prix plus élevés',
      'Les pays riches ont des prix plus élevés à cause de la productivité dans les secteurs échangeables',
      'La PPP fonctionne parfaitement',
      'Les taux de change sont toujours à la PPP',
    ],
    correctIndex: 1,
    explanation: 'Dans les pays riches, la productivité élevée dans les secteurs échangeables tire les salaires vers le haut, y compris dans les services non échangeables, augmentant le niveau général des prix.',
    difficulty: 'hard',
  },
  {
    id: 'macro-10-q5',
    lessonId: 'macro-10',
    question: 'La PPP fonctionne :',
    options: [
      'Parfaitement à court terme',
      'Mal à court terme mais raisonnablement bien à très long terme (10-20 ans)',
      'Uniquement pour les pays développés',
      'Jamais, c\'est une théorie obsolète',
    ],
    correctIndex: 1,
    explanation: 'La PPP ne tient pas à court terme (les taux de change s\'en écartent pendant des années) mais constitue un ancrage raisonnable à très long terme.',
    difficulty: 'medium',
  },

  // ── Lesson 11 : Balance des paiements ──
  {
    id: 'macro-11-q1',
    lessonId: 'macro-11',
    question: 'Le compte courant inclut :',
    options: [
      'Uniquement les flux de capitaux',
      'Les échanges de biens, services, revenus et transferts',
      'Uniquement les IDE',
      'Les réserves de change',
    ],
    correctIndex: 1,
    explanation: 'Le compte courant enregistre les transactions réelles : balance commerciale (biens), services, revenus (dividendes, intérêts) et transferts courants.',
    difficulty: 'easy',
  },
  {
    id: 'macro-11-q2',
    lessonId: 'macro-11',
    question: 'Un déficit du compte courant doit être financé par :',
    options: [
      'Une hausse du PIB',
      'Des entrées nettes de capitaux (excédent du compte financier)',
      'Une baisse de l\'inflation',
      'Une hausse des exportations immédiates',
    ],
    correctIndex: 1,
    explanation: 'Par construction, un déficit courant est compensé par un excédent du compte financier : le pays attire des capitaux étrangers pour financer sa surconsommation.',
    difficulty: 'medium',
  },
  {
    id: 'macro-11-q3',
    lessonId: 'macro-11',
    question: 'Les "Fragile Five" pendant le taper tantrum étaient fragiles à cause de :',
    options: [
      'Leur excédent courant',
      'Leurs déficits courants les rendant vulnérables aux sorties de capitaux',
      'Leur faible population',
      'Leur excès de réserves de change',
    ],
    correctIndex: 1,
    explanation: 'La Turquie, le Brésil, l\'Inde, l\'Afrique du Sud et l\'Indonésie avaient des déficits courants significatifs, les rendant dépendants des entrées de capitaux étrangers.',
    difficulty: 'hard',
  },
  {
    id: 'macro-11-q4',
    lessonId: 'macro-11',
    question: 'La "doom loop" européenne décrit :',
    options: [
      'Le cercle vertueux de la croissance',
      'Le cercle vicieux entre risque bancaire et risque souverain',
      'La convergence des taux européens',
      'Le succès de la zone euro',
    ],
    correctIndex: 1,
    explanation: 'Les banques détiennent la dette souveraine → crise souveraine affaiblit les banques → sauvetage bancaire aggrave la dette souveraine.',
    difficulty: 'hard',
  },
  {
    id: 'macro-11-q5',
    lessonId: 'macro-11',
    question: 'L\'Allemagne a historiquement un compte courant :',
    options: [
      'Fortement déficitaire',
      'Excédentaire structurel (~6 % du PIB)',
      'Toujours équilibré',
      'Variable sans tendance',
    ],
    correctIndex: 1,
    explanation: 'L\'Allemagne maintient un excédent courant structurel important (~6 % du PIB), reflétant sa compétitivité industrielle et sa relative sobriété de consommation.',
    difficulty: 'medium',
  },

  // ── Lesson 12 : Cycles ──
  {
    id: 'macro-12-q1',
    lessonId: 'macro-12',
    question: 'Les quatre phases de l\'investment clock de Merrill Lynch sont :',
    options: [
      'Lundi, mardi, mercredi, jeudi',
      'Reprise, expansion, surchauffe, récession',
      'Hausse, plateau, baisse, rebond',
      'Achat, détention, vente, attente',
    ],
    correctIndex: 1,
    explanation: 'L\'investment clock divise le cycle en 4 phases : reprise (actions), expansion (matières premières), surchauffe (cash), récession (obligations).',
    difficulty: 'easy',
  },
  {
    id: 'macro-12-q2',
    lessonId: 'macro-12',
    question: 'Une récession est techniquement définie comme :',
    options: [
      'Une baisse du PIB sur 1 trimestre',
      'Deux trimestres consécutifs de baisse du PIB',
      'Un taux de chômage supérieur à 10 %',
      'Une baisse du marché boursier de 20 %',
    ],
    correctIndex: 1,
    explanation: 'La définition technique européenne est 2 trimestres consécutifs de contraction du PIB (le NBER US utilise une définition plus large).',
    difficulty: 'easy',
  },
  {
    id: 'macro-12-q3',
    lessonId: 'macro-12',
    question: 'En phase de récession selon l\'investment clock, la classe d\'actifs à privilégier est :',
    options: [
      'Les actions cycliques',
      'Les matières premières',
      'Les obligations souveraines',
      'Les actions émergentes',
    ],
    correctIndex: 2,
    explanation: 'En récession (croissance et inflation en baisse), les obligations souveraines bénéficient des baisses de taux de la banque centrale.',
    difficulty: 'medium',
  },
  {
    id: 'macro-12-q4',
    lessonId: 'macro-12',
    question: 'Le cycle Kondratieff dure environ :',
    options: ['3-5 ans', '7-11 ans', '15-20 ans', '40-60 ans'],
    correctIndex: 3,
    explanation: 'Les cycles de Kondratieff (ondes longues) durent 40-60 ans et sont liés aux vagues d\'innovation technologique majeure.',
    difficulty: 'hard',
  },
  {
    id: 'macro-12-q5',
    lessonId: 'macro-12',
    question: 'Le cycle 2009-2020 aux US a été :',
    options: [
      'Le plus court de l\'histoire',
      'De durée moyenne',
      'Le plus long de l\'histoire US',
      'Inexistant (pas de croissance)',
    ],
    correctIndex: 2,
    explanation: 'L\'expansion de mars 2009 à février 2020 (128 mois) est le plus long cycle d\'expansion de l\'histoire américaine.',
    difficulty: 'medium',
  },

  // ── Lesson 13 : Indicateurs ──
  {
    id: 'macro-13-q1',
    lessonId: 'macro-13',
    question: 'Un PMI supérieur à 50 indique :',
    options: [
      'Une contraction de l\'activité',
      'Une expansion de l\'activité',
      'Une récession',
      'Une inflation élevée',
    ],
    correctIndex: 1,
    explanation: 'Le PMI est un indice de diffusion : au-dessus de 50, la majorité des directeurs d\'achats signalent une amélioration de l\'activité (expansion).',
    difficulty: 'easy',
  },
  {
    id: 'macro-13-q2',
    lessonId: 'macro-13',
    question: 'Le chômage est un indicateur :',
    options: [
      'Avancé',
      'Coïncident',
      'Retardé',
      'Inexistant',
    ],
    correctIndex: 2,
    explanation: 'Le chômage est un indicateur retardé : il confirme les tendances passées car les entreprises licencient après le début de la récession et embauchent après le début de la reprise.',
    difficulty: 'medium',
  },
  {
    id: 'macro-13-q3',
    lessonId: 'macro-13',
    question: 'Le LEI du Conference Board inclut ____ composantes :',
    options: ['5', '10', '15', '20'],
    correctIndex: 1,
    explanation: 'Le Leading Economic Index agrège 10 indicateurs avancés dont les permis de construire, les heures travaillées, les commandes et la courbe des taux.',
    difficulty: 'medium',
  },
  {
    id: 'macro-13-q4',
    lessonId: 'macro-13',
    question: 'Les spreads de crédit high yield qui s\'élargissent brutalement signalent :',
    options: [
      'Un assouplissement des conditions financières',
      'Un resserrement des conditions financières et un risque de récession',
      'Une amélioration de la qualité du crédit',
      'Une hausse des cours obligataires',
    ],
    correctIndex: 1,
    explanation: 'L\'élargissement des spreads HY indique que les investisseurs exigent une prime de risque plus élevée, signalant un resserrement des conditions financières et un stress de marché.',
    difficulty: 'medium',
  },
  {
    id: 'macro-13-q5',
    lessonId: 'macro-13',
    question: 'Le Citi Economic Surprise Index mesure :',
    options: [
      'Le PIB nominal',
      'Si les données économiques sortent au-dessus ou en dessous du consensus',
      'Le taux de chômage surprenant',
      'Les bénéfices des entreprises du Citi',
    ],
    correctIndex: 1,
    explanation: 'Le CESI mesure systématiquement si les publications macro sont meilleures ou pires que les attentes du consensus, pondérées par leur fraîcheur.',
    difficulty: 'medium',
  },

  // ── Lesson 14 : Émergents ──
  {
    id: 'macro-14-q1',
    lessonId: 'macro-14',
    question: 'La Chine représente environ ____ de l\'indice MSCI Emerging Markets :',
    options: ['5 %', '15 %', '30 %', '50 %'],
    correctIndex: 2,
    explanation: 'La Chine pèse environ 30 % de l\'indice MSCI EM, dominant la dynamique des marchés émergents.',
    difficulty: 'medium',
  },
  {
    id: 'macro-14-q2',
    lessonId: 'macro-14',
    question: 'Le principal risque pour les émergents quand la Fed resserre sa politique est :',
    options: [
      'La hausse du PIB',
      'La sortie des capitaux vers les US, la hausse du dollar et le durcissement du financement en USD',
      'La baisse de l\'inflation',
      'L\'augmentation des exportations',
    ],
    correctIndex: 1,
    explanation: 'Le resserrement US renforce le dollar, attire les capitaux et durcit le financement en USD pour les émergents endettés en devise forte.',
    difficulty: 'medium',
  },
  {
    id: 'macro-14-q3',
    lessonId: 'macro-14',
    question: 'Le P/E moyen des marchés émergents est typiquement :',
    options: [
      'Plus élevé que les marchés développés',
      'Similaire aux marchés développés',
      'Plus bas que les marchés développés (~12x vs ~20x)',
      'Toujours négatif',
    ],
    correctIndex: 2,
    explanation: 'Les marchés émergents se négocient historiquement avec une décote de valorisation (P/E ~12x vs ~20x pour les développés), reflétant le risque plus élevé.',
    difficulty: 'medium',
  },
  {
    id: 'macro-14-q4',
    lessonId: 'macro-14',
    question: 'Le taper tantrum de 2013 a fait chuter le MSCI EM de :',
    options: ['5 %', '15 %', '30 %', '50 %'],
    correctIndex: 1,
    explanation: 'L\'annonce par Bernanke de la réduction du QE a provoqué une chute de 15 % du MSCI EM et des dépréciations significatives des devises fragiles.',
    difficulty: 'hard',
  },
  {
    id: 'macro-14-q5',
    lessonId: 'macro-14',
    question: 'La corrélation entre marchés émergents et développés est d\'environ :',
    options: ['0,1', '0,3', '0,7', '1,0'],
    correctIndex: 2,
    explanation: 'La corrélation entre EM et DM est d\'environ 0,7, offrant un effet de diversification modéré mais qui tend à augmenter en période de crise.',
    difficulty: 'medium',
  },

  // ── Lesson 15 : Crises histoire ──
  {
    id: 'macro-15-q1',
    lessonId: 'macro-15',
    question: 'Le "Moment Minsky" survient quand :',
    options: [
      'L\'économie est en plein boom',
      'La confiance s\'effondre et les prix des actifs chutent, rendant le financement Ponzi insoutenable',
      'La banque centrale baisse les taux',
      'Le PIB atteint un record',
    ],
    correctIndex: 1,
    explanation: 'Le Moment Minsky est le point de basculement où l\'euphorie cède place à la panique, les prix des actifs chutent et le financement spéculatif s\'effondre.',
    difficulty: 'medium',
  },
  {
    id: 'macro-15-q2',
    lessonId: 'macro-15',
    question: 'Reinhart et Rogoff ("This Time Is Different") montrent que chaque crise est précédée par :',
    options: [
      'Une baisse du PIB',
      'Un boom du crédit et de l\'immobilier',
      'Une déflation',
      'Une guerre',
    ],
    correctIndex: 1,
    explanation: 'Reinhart et Rogoff documentent que les crises systémiques sont presque toujours précédées d\'un boom du crédit et des prix immobiliers.',
    difficulty: 'medium',
  },
  {
    id: 'macro-15-q3',
    lessonId: 'macro-15',
    question: 'Le coût moyen d\'une crise bancaire systémique en dette publique additionnelle est de :',
    options: ['5 % du PIB', '10 % du PIB', '23 % du PIB', '50 % du PIB'],
    correctIndex: 2,
    explanation: 'En moyenne, une crise bancaire systémique ajoute 23 % du PIB en dette publique (sauvetages, stabilisateurs automatiques, perte de recettes fiscales).',
    difficulty: 'hard',
  },
  {
    id: 'macro-15-q4',
    lessonId: 'macro-15',
    question: 'Les 5 phases de Kindleberger sont :',
    options: [
      'Hausse, plateau, baisse, rebond, stabilisation',
      'Déplacement, boom, euphorie, profit-taking, panique',
      'Investissement, production, vente, profit, réinvestissement',
      'Expansion, pic, contraction, creux, reprise',
    ],
    correctIndex: 1,
    explanation: 'Kindleberger (Manias, Panics, and Crashes) identifie 5 phases : un déplacement initial (innovation, choc), le boom, l\'euphorie, la prise de profits, puis la panique.',
    difficulty: 'hard',
  },
  {
    id: 'macro-15-q5',
    lessonId: 'macro-15',
    question: '"Cette fois c\'est différent" est considérée comme :',
    options: [
      'Une vérité absolue en finance',
      'La phrase la plus dangereuse en finance (Reinhart & Rogoff)',
      'Un bon signal d\'achat',
      'Une analyse technique',
    ],
    correctIndex: 1,
    explanation: 'Reinhart et Rogoff montrent que chaque bulle est accompagnée de la croyance que "cette fois c\'est différent" grâce à de nouvelles innovations. C\'est rarement le cas.',
    difficulty: 'easy',
  },

  // ── Lesson 16 : 2008 ──
  {
    id: 'macro-16-q1',
    lessonId: 'macro-16',
    question: 'Les subprimes sont :',
    options: [
      'Des obligations d\'État',
      'Des prêts hypothécaires accordés à des emprunteurs fragiles',
      'Des actions technologiques',
      'Des produits dérivés sur matières premières',
    ],
    correctIndex: 1,
    explanation: 'Les subprimes sont des prêts immobiliers accordés à des ménages à faible solvabilité, souvent avec des taux variables et des conditions permissives.',
    difficulty: 'easy',
  },
  {
    id: 'macro-16-q2',
    lessonId: 'macro-16',
    question: 'Lehman Brothers a fait faillite le :',
    options: ['15 mars 2008', '15 septembre 2008', '15 janvier 2009', '15 septembre 2007'],
    correctIndex: 1,
    explanation: 'La faillite de Lehman Brothers le 15 septembre 2008 a déclenché une panique systémique mondiale et le gel du marché interbancaire.',
    difficulty: 'easy',
  },
  {
    id: 'macro-16-q3',
    lessonId: 'macro-16',
    question: 'Le S&P 500 a chuté d\'environ ____ entre octobre 2007 et mars 2009 :',
    options: ['20 %', '35 %', '57 %', '75 %'],
    correctIndex: 2,
    explanation: 'Le S&P 500 a chuté d\'environ 57 % de son pic (1 565) à son creux (676), l\'une des pires baisses de l\'histoire boursière.',
    difficulty: 'medium',
  },
  {
    id: 'macro-16-q4',
    lessonId: 'macro-16',
    question: 'La règle Volcker issue de la régulation post-2008 (Dodd-Frank) :',
    options: [
      'Interdit l\'emprunt hypothécaire',
      'Limite le trading propriétaire des banques',
      'Oblige les banques à détenir de l\'or',
      'Fixe les taux d\'intérêt',
    ],
    correctIndex: 1,
    explanation: 'La règle Volcker interdit aux banques commerciales de faire du trading propriétaire (pour compte propre), limitant la prise de risque avec les dépôts des clients.',
    difficulty: 'medium',
  },
  {
    id: 'macro-16-q5',
    lessonId: 'macro-16',
    question: 'Les agences de notation ont contribué à la crise en :',
    options: [
      'Refusant de noter les CDO',
      'Attribuant des notations AAA à des tranches de CDO adossés à des subprimes',
      'Dégradant tous les émetteurs préventivement',
      'Supprimant les notations',
    ],
    correctIndex: 1,
    explanation: 'Les agences (S&P, Moody\'s, Fitch) ont attribué des AAA aux tranches senior de CDO subprime, sous-estimant massivement les corrélations de défaut.',
    difficulty: 'medium',
  },

  // ── Lesson 17 : Dette européenne ──
  {
    id: 'macro-17-q1',
    lessonId: 'macro-17',
    question: 'Le PSI (Private Sector Involvement) grec a imposé un haircut de :',
    options: ['10 %', '25 %', '53 %', '100 %'],
    correctIndex: 2,
    explanation: 'En mars 2012, les créanciers privés de la Grèce ont accepté un haircut de 53 % sur la valeur nominale de leurs obligations, la plus grande restructuration souveraine de l\'histoire.',
    difficulty: 'medium',
  },
  {
    id: 'macro-17-q2',
    lessonId: 'macro-17',
    question: 'Le "Whatever it takes" de Draghi a été prononcé en :',
    options: ['2008', '2010', 'Juillet 2012', '2015'],
    correctIndex: 2,
    explanation: 'Le 26 juillet 2012, Draghi déclare : "Within our mandate, the ECB is ready to do whatever it takes to preserve the euro. And believe me, it will be enough."',
    difficulty: 'medium',
  },
  {
    id: 'macro-17-q3',
    lessonId: 'macro-17',
    question: 'Le "péché originel" de la zone euro est :',
    options: [
      'L\'introduction de l\'euro',
      'L\'union monétaire sans union budgétaire',
      'L\'absence de banque centrale',
      'Le taux de change fixe avec le dollar',
    ],
    correctIndex: 1,
    explanation: 'La zone euro a une monnaie unique et une politique monétaire commune mais pas de budget fédéral ni de mécanisme de transferts entre pays, créant des vulnérabilités.',
    difficulty: 'medium',
  },
  {
    id: 'macro-17-q4',
    lessonId: 'macro-17',
    question: 'Le spread BTP-Bund a dépassé ____ bps en novembre 2011 :',
    options: ['100', '300', '550', '1000'],
    correctIndex: 2,
    explanation: 'Le spread entre le BTP italien 10 ans et le Bund allemand a dépassé 550 bps, reflétant le risque de défaut perçu de l\'Italie.',
    difficulty: 'hard',
  },
  {
    id: 'macro-17-q5',
    lessonId: 'macro-17',
    question: 'Le programme OMT de la BCE :',
    options: [
      'A été massivement utilisé pour acheter des obligations',
      'N\'a jamais été activé mais a stoppé la crise par sa seule existence',
      'A été annulé immédiatement',
      'Concernait uniquement la Grèce',
    ],
    correctIndex: 1,
    explanation: 'Le programme OMT (Outright Monetary Transactions) n\'a jamais été activé. La simple annonce de sa disponibilité a suffi à calmer les marchés.',
    difficulty: 'hard',
  },

  // ── Lesson 18 : COVID ──
  {
    id: 'macro-18-q1',
    lessonId: 'macro-18',
    question: 'Le S&P 500 a chuté de 34 % en ____ jours lors du crash COVID :',
    options: ['5', '23', '60', '120'],
    correctIndex: 1,
    explanation: 'Le S&P 500 a perdu 34 % en seulement 23 jours (du 19 février au 23 mars 2020), le crash le plus rapide de l\'histoire.',
    difficulty: 'medium',
  },
  {
    id: 'macro-18-q2',
    lessonId: 'macro-18',
    question: 'La Fed a réagi au COVID en :',
    options: [
      'Ne rien faisant',
      'Baissant les taux de 150 bps en deux semaines et lançant un QE illimité',
      'Augmentant les taux de 100 bps',
      'Vendant des obligations',
    ],
    correctIndex: 1,
    explanation: 'La Fed a agi avec une rapidité sans précédent : baisse de 150 bps à 0 % en deux semaines, QE illimité et création de multiples facilités de crédit.',
    difficulty: 'easy',
  },
  {
    id: 'macro-18-q3',
    lessonId: 'macro-18',
    question: 'La masse monétaire M2 US a augmenté de ____ en 2020-2021 :',
    options: ['5 %', '12 %', '27 %', '50 %'],
    correctIndex: 2,
    explanation: 'La M2 américaine a augmenté de 27 % en 2020-2021, un rythme sans précédent qui a contribué à l\'inflation record de 2022.',
    difficulty: 'hard',
  },
  {
    id: 'macro-18-q4',
    lessonId: 'macro-18',
    question: 'L\'héritage principal de la crise COVID est :',
    options: [
      'La baisse de la dette publique',
      'L\'inflation élevée, la dette record et l\'accélération de la digitalisation',
      'La disparition des banques centrales',
      'La fin du commerce international',
    ],
    correctIndex: 1,
    explanation: 'Le stimulus massif a sauvé l\'économie mais laissé des séquelles : inflation à 9 %, dette publique record, et transformation digitale accélérée.',
    difficulty: 'easy',
  },
  {
    id: 'macro-18-q5',
    lessonId: 'macro-18',
    question: 'Un investisseur qui a vendu paniqué le 23 mars 2020 et racheté le 1er janvier 2021 a manqué un rebond de :',
    options: ['10 %', '30 %', '68 %', '100 %'],
    correctIndex: 2,
    explanation: 'Le S&P 500 est passé de 2 237 (23 mars) à 3 756 (1er janvier 2021), soit un rebond de 68 % en 9 mois. La leçon : ne pas vendre dans la panique.',
    difficulty: 'medium',
  },

  // ── Lesson 19 : Politique budgétaire ──
  {
    id: 'macro-19-q1',
    lessonId: 'macro-19',
    question: 'Le multiplicateur budgétaire mesure :',
    options: [
      'Le ratio dette/PIB',
      'L\'impact d\'1 € de dépense publique sur le PIB',
      'Le taux d\'imposition',
      'Le déficit budgétaire',
    ],
    correctIndex: 1,
    explanation: 'Le multiplicateur budgétaire mesure combien d\'euros de PIB sont générés par 1 € de dépense publique supplémentaire.',
    difficulty: 'easy',
  },
  {
    id: 'macro-19-q2',
    lessonId: 'macro-19',
    question: 'Le multiplicateur est plus élevé en :',
    options: [
      'Période d\'expansion avec plein emploi',
      'Période de récession quand les ressources sont sous-utilisées',
      'Période de surchauffe inflationniste',
      'Il est constant quel que soit le cycle',
    ],
    correctIndex: 1,
    explanation: 'En récession, les ressources sont sous-utilisées. La dépense publique mobilise des capacités dormantes, générant un effet multiplicateur plus fort (1,5-2x vs 0,5-0,8x).',
    difficulty: 'medium',
  },
  {
    id: 'macro-19-q3',
    lessonId: 'macro-19',
    question: 'Les stabilisateurs automatiques sont :',
    options: [
      'Des décisions discrétionnaires du gouvernement',
      'Des mécanismes budgétaires qui agissent sans décision politique (allocations chômage, impôts progressifs)',
      'Des taux d\'intérêt fixes',
      'Des subventions aux entreprises',
    ],
    correctIndex: 1,
    explanation: 'Les stabilisateurs automatiques (baisse des recettes fiscales, hausse des allocations chômage en récession) soutiennent l\'économie sans action délibérée.',
    difficulty: 'easy',
  },
  {
    id: 'macro-19-q4',
    lessonId: 'macro-19',
    question: 'La soutenabilité de la dette est assurée tant que :',
    options: [
      'Le PIB est positif',
      'Le taux d\'intérêt est inférieur au taux de croissance (r < g)',
      'L\'inflation est nulle',
      'Le déficit est inférieur à 10 %',
    ],
    correctIndex: 1,
    explanation: 'Blanchard et Summers argumentent que tant que r < g, la croissance "dilue" la dette existante et un déficit primaire modéré est soutenable.',
    difficulty: 'hard',
  },
  {
    id: 'macro-19-q5',
    lessonId: 'macro-19',
    question: 'L\'American Rescue Plan de Biden (2021) représentait :',
    options: ['200 Mds$', '800 Mds$', '1 900 Mds$', '5 000 Mds$'],
    correctIndex: 2,
    explanation: 'L\'American Rescue Plan de mars 2021 représentait 1 900 milliards de dollars, incluant des chèques directs aux ménages et des aides aux États.',
    difficulty: 'medium',
  },

  // ── Lesson 20 : Dette souveraine ──
  {
    id: 'macro-20-q1',
    lessonId: 'macro-20',
    question: 'Le ratio dette/PIB du Japon est d\'environ :',
    options: ['60 %', '120 %', '260 %', '500 %'],
    correctIndex: 2,
    explanation: 'Le Japon a le ratio dette/PIB le plus élevé des pays développés, à environ 260 %, mais reste stable grâce à une détention domestique et la BoJ.',
    difficulty: 'medium',
  },
  {
    id: 'macro-20-q2',
    lessonId: 'macro-20',
    question: 'La dynamique de la dette est défavorable quand :',
    options: [
      'r < g',
      'r > g (le taux d\'intérêt dépasse la croissance)',
      'L\'inflation est élevée',
      'Le PIB est en croissance',
    ],
    correctIndex: 1,
    explanation: 'Quand r > g, l\'effet "boule de neige" augmente la dette automatiquement : il faut un excédent primaire pour stabiliser le ratio dette/PIB.',
    difficulty: 'medium',
  },
  {
    id: 'macro-20-q3',
    lessonId: 'macro-20',
    question: 'Les CDS spreads souverains mesurent :',
    options: [
      'Le taux de croissance du PIB',
      'Le coût de l\'assurance contre le défaut souverain',
      'Le taux d\'inflation',
      'Le rendement des actions',
    ],
    correctIndex: 1,
    explanation: 'Les CDS (Credit Default Swaps) souverains sont des contrats d\'assurance contre le défaut. Leur spread reflète la perception du risque de crédit souverain.',
    difficulty: 'medium',
  },
  {
    id: 'macro-20-q4',
    lessonId: 'macro-20',
    question: 'Le spread OAT-Bund est d\'environ :',
    options: ['0 bps', '10-20 bps', '50-80 bps', '200-300 bps'],
    correctIndex: 2,
    explanation: 'La France paie une prime de 50-80 bps par rapport à l\'Allemagne sur le 10 ans, reflétant un risque de crédit légèrement supérieur.',
    difficulty: 'hard',
  },
  {
    id: 'macro-20-q5',
    lessonId: 'macro-20',
    question: 'La monétisation de la dette signifie que :',
    options: [
      'L\'État rembourse sa dette en espèces',
      'La banque centrale achète la dette de l\'État (QE), finançant indirectement le déficit',
      'La dette est convertie en actions',
      'La dette est annulée sans contrepartie',
    ],
    correctIndex: 1,
    explanation: 'La monétisation survient quand la banque centrale achète massivement la dette publique (QE), permettant à l\'État de s\'endetter à moindre coût. C\'est controversé car potentiellement inflationniste.',
    difficulty: 'hard',
  },

  // ── Lesson 21 : Cas Cycle ──
  {
    id: 'macro-21-q1',
    lessonId: 'macro-21',
    question: 'Le cadre d\'analyse macro suit la séquence :',
    options: [
      'Marchés → Politique → Croissance',
      'Croissance → Inflation → Politique monétaire → Marchés',
      'Inflation → Marchés → Croissance → Politique',
      'Politique → Inflation → Marchés → Croissance',
    ],
    correctIndex: 1,
    explanation: 'L\'analyse macro structurée part de la croissance, passe par l\'inflation, anticipe la réponse de politique monétaire et en déduit les implications pour les marchés.',
    difficulty: 'medium',
  },
  {
    id: 'macro-21-q2',
    lessonId: 'macro-21',
    question: 'En début de cycle de baisse des taux, on surpondère typiquement :',
    options: [
      'Le cash',
      'La duration obligataire et les actions de qualité',
      'Les matières premières cycliques',
      'Les actions émergentes uniquement',
    ],
    correctIndex: 1,
    explanation: 'En début de cycle de baisse des taux, les obligations longues bénéficient de la baisse des rendements et les actions de qualité sont favorisées par l\'assouplissement.',
    difficulty: 'medium',
  },
  {
    id: 'macro-21-q3',
    lessonId: 'macro-21',
    question: 'La crise bancaire de mars 2023 (SVB) a été causée par :',
    options: [
      'Le risque de crédit',
      'Le risque de taux : la hausse des taux a déprécié les portefeuilles obligataires des banques',
      'La fraude comptable',
      'Le risque de change',
    ],
    correctIndex: 1,
    explanation: 'SVB détenait massivement des obligations longues. La hausse rapide des taux les a dépréciées, créant des pertes latentes massives et une panique des déposants.',
    difficulty: 'medium',
  },
  {
    id: 'macro-21-q4',
    lessonId: 'macro-21',
    question: 'Le "last mile" de désinflation fait référence à :',
    options: [
      'La dernière étape de la hausse des taux',
      'La difficulté à ramener l\'inflation de 3-4 % vers la cible de 2 %',
      'Le dernier kilomètre de livraison',
      'La fin du QE',
    ],
    correctIndex: 1,
    explanation: 'Le "last mile" est la phase la plus difficile de la désinflation : ramener l\'inflation de 3-4 % à 2 % est plus ardu que de la faire baisser de 9 % à 4 %.',
    difficulty: 'hard',
  },
  {
    id: 'macro-21-q5',
    lessonId: 'macro-21',
    question: 'Un gérant surpondérant les obligations longues en octobre 2023 (10Y à 5 %) a bénéficié de :',
    options: [
      'La hausse des taux',
      'La baisse des taux vers 3,9 %, générant un gain de ~15 % en 3 mois',
      'La stabilité des taux',
      'La hausse du dollar',
    ],
    correctIndex: 1,
    explanation: 'La détente des taux de 5 % à 3,9 % sur le 10Y a généré un gain important grâce à la duration. L\'analyse macro (pic de taux) a guidé cette décision.',
    difficulty: 'medium',
  },

  // ── Lesson 22 : Examen final ──
  {
    id: 'macro-22-q1',
    lessonId: 'macro-22',
    question: 'Si le PMI tombe à 48, l\'inflation core est à 2,8 % et la courbe s\'inverse, le diagnostic macro est :',
    options: [
      'Expansion avec surchauffe',
      'Late-cycle avec risque de récession imminente',
      'Reprise économique',
      'Stagflation sévère',
    ],
    correctIndex: 1,
    explanation: 'PMI < 50 (contraction), courbe inversée (récession anticipée), inflation modérée : c\'est un diagnostic late-cycle avec risque de récession.',
    difficulty: 'medium',
  },
  {
    id: 'macro-22-q2',
    lessonId: 'macro-22',
    question: 'La réponse probable de la Fed au diagnostic précédent serait :',
    options: [
      'Continuer à monter les taux',
      'Maintenir les taux inchangés puis commencer à les baisser',
      'Lancer un QE massif immédiatement',
      'Augmenter le taux de réserves obligatoires',
    ],
    correctIndex: 1,
    explanation: 'Avec un PMI < 50 et une inflation en décélération vers la cible, la Fed maintiendrait les taux puis amorcerait des baisses préventives.',
    difficulty: 'medium',
  },
  {
    id: 'macro-22-q3',
    lessonId: 'macro-22',
    question: 'La politique monétaire agit sur l\'économie via les canaux :',
    options: [
      'Un seul canal (les taux)',
      'Deux canaux (taux et crédit)',
      'Quatre canaux : taux d\'intérêt, crédit, taux de change et prix d\'actifs',
      'Aucun canal direct',
    ],
    correctIndex: 2,
    explanation: 'La transmission de la politique monétaire passe par quatre canaux principaux : les taux d\'intérêt, le crédit bancaire, le taux de change et les prix d\'actifs.',
    difficulty: 'medium',
  },
  {
    id: 'macro-22-q4',
    lessonId: 'macro-22',
    question: 'Le positionnement de portefeuille optimal en fin de cycle de hausse des taux est :',
    options: [
      'Surpondérer les actions cycliques et les matières premières',
      'Surpondérer la duration obligataire et les actifs de qualité, sous-pondérer le cash',
      'Être 100 % en cash',
      'Surpondérer les marchés émergents',
    ],
    correctIndex: 1,
    explanation: 'En fin de cycle de hausse, la duration bénéficiera des futures baisses de taux. Les actifs de qualité résistent mieux au ralentissement. Le cash verra son rendement baisser.',
    difficulty: 'hard',
  },
  {
    id: 'macro-22-q5',
    lessonId: 'macro-22',
    question: 'La plus grande leçon de la macroéconomie financière est que :',
    options: [
      'Les marchés sont toujours prévisibles',
      'Les crises ne se produisent plus',
      'Comprendre les forces macroéconomiques permet d\'anticiper les grandes tendances mais l\'humilité reste essentielle',
      'Seul le court terme compte',
    ],
    correctIndex: 2,
    explanation: 'La macroéconomie donne un cadre pour anticiper les grandes tendances mais l\'humilité est cruciale : les modèles sont imparfaits et les surprises sont la norme.',
    difficulty: 'easy',
  },
];
