// ──────────────────────────────────────────────
//  FINA - Assurance & Actuariat : Quiz
// ──────────────────────────────────────────────

import type { QuizQuestion } from '../types';

export const insuranceQuiz: QuizQuestion[] = [
  {
    id: 'ins-q1',
    lessonId: 'ins-1',
    question: 'Quel ratio mesure la rentabilité technique d\'un assureur ?',
    options: [
      'Return on Equity (ROE)',
      'Ratio combiné (sinistres + frais) / primes',
      'Ratio de solvabilité',
      'Price-to-Book',
    ],
    correctIndex: 1,
    explanation: 'Le ratio combiné = (sinistres + frais) / primes acquises. Sous 100%, l\'assureur gagne de l\'argent sur son activité technique.',
    difficulty: 'easy',
  },
  {
    id: 'ins-q2',
    lessonId: 'ins-1',
    question: 'Qu\'est-ce que le « float » en assurance ?',
    options: [
      'Le taux de change flottant',
      'Les primes encaissées mais pas encore versées en sinistres, investies entre-temps',
      'La valeur de marché des actions détenues',
      'La marge de solvabilité',
    ],
    correctIndex: 1,
    explanation: 'Le float est constitué des primes encaissées avant le paiement des sinistres. Cet argent est investi et génère des revenus financiers. C\'est le modèle de Berkshire Hathaway.',
    difficulty: 'medium',
  },
  {
    id: 'ins-q3',
    lessonId: 'ins-2',
    question: 'Quel est le risque principal en assurance vie (rentes) ?',
    options: [
      'Le risque de fréquence des sinistres',
      'Le risque de longévité (les assurés vivent plus longtemps que prévu)',
      'Le risque de vol',
      'Le risque de change',
    ],
    correctIndex: 1,
    explanation: 'En rente viagère, le risque de longévité est le risque que les assurés vivent plus longtemps que prévu, augmentant le coût des prestations.',
    difficulty: 'medium',
  },
  {
    id: 'ins-q4',
    lessonId: 'ins-3',
    question: 'Comment calcule-t-on la prime pure en assurance non-vie ?',
    options: [
      'Chiffre d\'affaires / Nombre de contrats',
      'Fréquence × Coût moyen du sinistre',
      'Provisions / Primes',
      'Sinistres / Fonds propres',
    ],
    correctIndex: 1,
    explanation: 'Prime pure = Fréquence (nombre de sinistres / nombre de contrats) × Coût moyen du sinistre. C\'est l\'espérance mathématique du coût.',
    difficulty: 'easy',
  },
  {
    id: 'ins-q5',
    lessonId: 'ins-3',
    question: 'En tarification automobile, fréquence 7% et coût moyen 3 500€. Quel est le montant de la prime pure ?',
    options: ['175€', '245€', '350€', '500€'],
    correctIndex: 1,
    explanation: 'Prime pure = 0.07 × 3 500 = 245€. C\'est le coût technique du risque avant chargements (frais, marge, réassurance).',
    difficulty: 'easy',
  },
  {
    id: 'ins-q6',
    lessonId: 'ins-4',
    question: 'Que représente qx dans une table de mortalité ?',
    options: [
      'Le nombre de décès à l\'âge x',
      'La probabilité de décéder entre l\'âge x et x+1',
      'L\'espérance de vie à l\'âge x',
      'Le nombre de survivants à l\'âge x',
    ],
    correctIndex: 1,
    explanation: 'qx est la probabilité de décéder entre l\'âge x et x+1. C\'est le paramètre fondamental d\'une table de mortalité, à partir duquel on dérive lx et ex.',
    difficulty: 'medium',
  },
  {
    id: 'ins-q7',
    lessonId: 'ins-5',
    question: 'Que signifie IBNR en provisionnement ?',
    options: [
      'Insurance Based Net Reserve',
      'Incurred But Not Reported (sinistres survenus mais non déclarés)',
      'Initial Baseline Net Ratio',
      'Internal Budget Net Result',
    ],
    correctIndex: 1,
    explanation: 'IBNR = Incurred But Not Reported : sinistres déjà survenus à la date de clôture mais pas encore déclarés à l\'assureur. Ils doivent être provisionnés.',
    difficulty: 'medium',
  },
  {
    id: 'ins-q8',
    lessonId: 'ins-6',
    question: 'Solvabilité II repose sur combien de piliers ?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
    explanation: 'Solvabilité II repose sur 3 piliers : Pilier 1 (exigences quantitatives : SCR, MCR), Pilier 2 (gouvernance, ORSA) et Pilier 3 (reporting, transparence).',
    difficulty: 'easy',
  },
  {
    id: 'ins-q9',
    lessonId: 'ins-7',
    question: 'Le SCR est calibré pour que l\'assureur survive à un événement de quelle fréquence ?',
    options: [
      '1 fois tous les 10 ans (VaR 90%)',
      '1 fois tous les 50 ans (VaR 98%)',
      '1 fois tous les 200 ans (VaR 99.5%)',
      '1 fois tous les 1000 ans (VaR 99.9%)',
    ],
    correctIndex: 2,
    explanation: 'Le SCR correspond à une VaR à 99.5% sur un horizon d\'1 an, soit un événement qui ne se produit qu\'une fois tous les 200 ans.',
    difficulty: 'medium',
  },
  {
    id: 'ins-q10',
    lessonId: 'ins-8',
    question: 'Sous IFRS 17, qu\'est-ce que la CSM (Contractual Service Margin) ?',
    options: [
      'Le coût du capital réglementaire',
      'Le profit futur non acquis, reconnu progressivement',
      'La marge de solvabilité',
      'Le coût des sinistres',
    ],
    correctIndex: 1,
    explanation: 'La CSM est le profit futur du contrat, reconnu progressivement en résultat au fur et à mesure que l\'assureur fournit le service de couverture.',
    difficulty: 'hard',
  },
  {
    id: 'ins-q11',
    lessonId: 'ins-9',
    question: 'Le Best Estimate sous Solvabilité II est actualisé à quel taux ?',
    options: [
      'Le taux de rendement du portefeuille d\'actifs',
      'La courbe des taux sans risque publiée par l\'EIOPA',
      'Le taux directeur de la BCE',
      'Le taux de rendement des obligations d\'État',
    ],
    correctIndex: 1,
    explanation: 'Le Best Estimate est actualisé à la courbe des taux sans risque publiée par l\'EIOPA, éventuellement ajustée du Volatility Adjustment ou du Matching Adjustment.',
    difficulty: 'hard',
  },
  {
    id: 'ins-q12',
    lessonId: 'ins-10',
    question: 'Quel taux de coût du capital est utilisé pour calculer la Risk Margin sous Solvabilité II ?',
    options: ['3%', '4%', '6%', '8%'],
    correctIndex: 2,
    explanation: 'La Risk Margin utilise un CoC (Cost of Capital) fixé à 6% par la réglementation, appliqué aux SCR futurs projetés et actualisés.',
    difficulty: 'medium',
  },
  {
    id: 'ins-q13',
    lessonId: 'ins-11',
    question: 'Dans un contrat Cat XL « 200 M€ xs 50 M€ », que paie le réassureur si les sinistres totalisent 180 M€ ?',
    options: ['180 M€', '200 M€', '130 M€', '50 M€'],
    correctIndex: 2,
    explanation: 'Le réassureur paie Max(0, Min(180 - 50, 200)) = Min(130, 200) = 130 M€. L\'assureur conserve les premiers 50 M€ (priorité).',
    difficulty: 'hard',
  },
  {
    id: 'ins-q14',
    lessonId: 'ins-12',
    question: 'Quel est l\'avantage des cat bonds pour les investisseurs ?',
    options: [
      'Un rendement garanti',
      'Une décorrélation avec les marchés financiers et un rendement élevé',
      'L\'absence de risque de perte',
      'La liquidité quotidienne',
    ],
    correctIndex: 1,
    explanation: 'Les cat bonds offrent un rendement élevé (taux sans risque + 5-15%) et une décorrélation avec les marchés financiers (les catastrophes naturelles sont indépendantes des cycles économiques).',
    difficulty: 'medium',
  },
];
