import type { QuizQuestion } from './index';

// Arena question pool — 200+ questions across all finance topics
export const ARENA_POOL: QuizQuestion[] = [
  // === FONDAMENTAUX (20 questions) ===
  { id: 'a1', question: 'Le Current Ratio mesure :', options: ['La liquidité à court terme', 'La rentabilité', "L'endettement", 'La croissance'], correctIndex: 0, explanation: 'Current Ratio = Actif courant / Passif courant. Il mesure la capacité à rembourser les dettes court terme.', difficulty: 'easy' },
  { id: 'a2', question: 'Formule de l\'EBITDA :', options: ['CA - Charges d\'exploitation', 'Résultat d\'exploitation + D&A', 'Résultat net + Intérêts + Impôts', 'Free Cash Flow + CAPEX'], correctIndex: 1, explanation: 'EBITDA = EBIT + Depreciation & Amortization. C\'est le résultat opérationnel avant charges non cash.', difficulty: 'easy' },
  { id: 'a3', question: 'Le BFR augmente quand :', options: ['Les stocks diminuent', 'Les délais clients augmentent', 'Les délais fournisseurs augmentent', 'Le CA baisse'], correctIndex: 1, explanation: 'BFR = Stocks + Créances clients - Dettes fournisseurs. Plus les clients paient tard, plus le BFR augmente.', difficulty: 'medium' },
  { id: 'a4', question: 'Le Free Cash Flow se calcule à partir de :', options: ['Résultat net', 'EBITDA', 'Chiffre d\'affaires', 'Dividendes'], correctIndex: 1, explanation: 'FCF = EBITDA - Impôts cash - ΔBFR - CAPEX. Le cash réellement disponible pour les investisseurs.', difficulty: 'easy' },
  { id: 'a5', question: 'Le taux d\'actualisation dans un DCF est :', options: ['Le taux sans risque', 'Le WACC', 'Le ROE', 'Le taux d\'inflation'], correctIndex: 1, explanation: 'WACC = Ke × (E/V) + Kd(1-t) × (D/V). C\'est le coût moyen pondéré du capital.', difficulty: 'easy' },
  { id: 'a6', question: 'La valeur terminale dans un DCF représente typiquement :', options: ['10-20% de l\'EV', '30-50% de l\'EV', '60-80% de l\'EV', '90-100% de l\'EV'], correctIndex: 2, explanation: 'La valeur terminale représente souvent 60-80% de la valeur d\'entreprise dans un DCF, ce qui souligne l\'importance de ses hypothèses.', difficulty: 'medium' },
  { id: 'a7', question: 'EV/EBITDA est préféré à P/E car :', options: ['Il est plus simple', 'Il est indépendant de la structure de capital', 'Il inclut les dividendes', 'Il est réglementé'], correctIndex: 1, explanation: 'EV/EBITDA neutralise les différences de structure de capital et de politique fiscale entre entreprises.', difficulty: 'medium' },
  { id: 'a8', question: 'Enterprise Value = :', options: ['Market Cap + Cash', 'Market Cap + Dette Nette', 'Total Assets', 'Equity Value × Multiple'], correctIndex: 1, explanation: 'EV = Market Cap + Dette Nette (dette financière - trésorerie) + Intérêts minoritaires + Preferred - Participations.', difficulty: 'easy' },
  { id: 'a9', question: 'Le ROE se décompose par DuPont en :', options: ['Marge × Rotation × Levier', 'CA × EBITDA × Dette', 'ROIC × WACC × g', 'Alpha × Beta × Sigma'], correctIndex: 0, explanation: 'DuPont: ROE = (RN/CA) × (CA/Actif) × (Actif/CP) = Marge nette × Rotation des actifs × Levier financier.', difficulty: 'medium' },
  { id: 'a10', question: 'Le "Football Field" en valorisation montre :', options: ['Les scores des équipes', 'Une fourchette de valorisation par méthode', 'L\'évolution du cours', 'Le classement sectoriel'], correctIndex: 1, explanation: 'Le football field est un graphique en barres horizontales montrant les fourchettes de valorisation (DCF, comps, precedents).', difficulty: 'easy' },
  { id: 'a11', question: 'Le Quick Ratio exclut :', options: ['La trésorerie', 'Les créances', 'Les stocks', 'Les VMP'], correctIndex: 2, explanation: 'Quick Ratio = (Actif courant - Stocks) / Passif courant. Les stocks sont exclus car moins liquides.', difficulty: 'easy' },
  { id: 'a12', question: 'La normalisation en valorisation sert à :', options: ['Augmenter la valeur', 'Éliminer les éléments exceptionnels', 'Réduire les impôts', 'Simplifier le bilan'], correctIndex: 1, explanation: 'La normalisation ajuste les résultats pour éliminer les éléments non récurrents et refléter la performance sous-jacente.', difficulty: 'medium' },
  { id: 'a13', question: 'Un SOTP est utilisé quand :', options: ['L\'entreprise est simple', 'L\'entreprise a des activités diversifiées', 'L\'entreprise est en difficulté', 'L\'entreprise est petite'], correctIndex: 1, explanation: 'Sum-Of-The-Parts valorise chaque division séparément, utile pour les conglomérats (ex: LVMH, Bouygues).', difficulty: 'medium' },
  { id: 'a14', question: 'Le Gearing ratio mesure :', options: ['La liquidité', 'L\'endettement relatif aux capitaux propres', 'La rentabilité', 'La croissance'], correctIndex: 1, explanation: 'Gearing = Dette nette / Capitaux propres. Il mesure le levier financier de l\'entreprise.', difficulty: 'easy' },
  { id: 'a15', question: 'Sensitivity Analysis fait varier :', options: ['Un seul paramètre à la fois', 'Tous les paramètres simultanément', 'Uniquement le WACC', 'Uniquement la croissance'], correctIndex: 0, explanation: 'La sensitivity analysis fait varier un ou deux paramètres (WACC, g) pour observer l\'impact sur la valorisation.', difficulty: 'easy' },
  { id: 'a16', question: 'Le bridge EV → Equity retranche :', options: ['Les capitaux propres', 'La dette nette', 'Les actifs immobilisés', 'Le goodwill'], correctIndex: 1, explanation: 'Equity Value = EV - Dette nette - Minoritaires - Preferred + Participations mises en équivalence.', difficulty: 'medium' },
  { id: 'a17', question: 'Gordon Growth Model : P = :', options: ['D1 / (r - g)', 'E × P/E', 'FCF / WACC', 'EBITDA × Multiple'], correctIndex: 0, explanation: 'P = D1 / (r - g) où D1 est le prochain dividende, r le taux requis, g le taux de croissance perpétuelle.', difficulty: 'medium' },
  { id: 'a18', question: 'Les Precedent Transactions sont généralement :', options: ['Inférieures aux Comps', 'Supérieures aux Comps (prime de contrôle)', 'Identiques aux Comps', 'Non comparables'], correctIndex: 1, explanation: 'Les transactions passées incluent une prime de contrôle (20-40%), d\'où des multiples supérieurs aux comparables cotés.', difficulty: 'hard' },
  { id: 'a19', question: 'Le CAPEX de maintenance est :', options: ['Le CAPEX pour croître', 'Le CAPEX pour maintenir l\'outil productif', 'Le CAPEX R&D', 'Le CAPEX acquisition'], correctIndex: 1, explanation: 'Le CAPEX de maintenance remplace les actifs usés. Il est souvent approximé par la D&A. Le CAPEX de croissance s\'y ajoute.', difficulty: 'medium' },
  { id: 'a20', question: 'Le multiple EV/Sales est utile pour :', options: ['Les entreprises rentables', 'Les entreprises en perte (startups, tech)', 'Les banques', 'Les assureurs'], correctIndex: 1, explanation: 'EV/Sales est pertinent quand l\'EBITDA est négatif. Utilisé pour les startups, tech en croissance, et les comparaisons sectorielles.', difficulty: 'medium' },

  // === CORPORATE FINANCE (25 questions) ===
  { id: 'a21', question: 'Principal levier de rendement dans un LBO :', options: ['Croissance CA', 'Effet de levier financier', 'Synergies de coûts', 'Réduction d\'impôts'], correctIndex: 1, explanation: 'La dette amplifie le rendement equity : une petite variation de l\'EV crée une grosse variation de la valeur des fonds propres.', difficulty: 'easy' },
  { id: 'a22', question: 'L\'accretion/dilution analyse :', options: ['L\'impact sur le BPA post-acquisition', 'Le goodwill', 'Les synergies', 'Le WACC'], correctIndex: 0, explanation: 'L\'analyse A/D mesure si le BPA de l\'acquéreur augmente (accretive) ou diminue (dilutive) après une acquisition.', difficulty: 'medium' },
  { id: 'a23', question: 'Modigliani-Miller (sans impôts) dit :', options: ['La dette crée de la valeur', 'La structure de capital est neutre', 'Les dividendes importent', 'Le WACC augmente avec la dette'], correctIndex: 1, explanation: 'M&M Proposition I (sans impôts) : la valeur de l\'entreprise est indépendante de sa structure de capital en marché parfait.', difficulty: 'hard' },
  { id: 'a24', question: 'Le Cash Sweep dans un LBO :', options: ['Distribue le cash aux actionnaires', 'Rembourse la dette accéléré avec le cash excédentaire', 'Finance les acquisitions', 'Augmente le fonds de roulement'], correctIndex: 1, explanation: 'Le cash sweep est un mécanisme de remboursement anticipé obligatoire qui utilise le cash flow excédentaire pour réduire la dette.', difficulty: 'medium' },
  { id: 'a25', question: 'Sources & Uses dans un LBO :', options: ['Bilan et P&L', 'Comment l\'acquisition est financée et payée', 'Revenus et coûts', 'Import et export'], correctIndex: 1, explanation: 'Sources (equity + dette) = Uses (prix d\'acquisition + frais). C\'est le montage financier de l\'opération.', difficulty: 'easy' },
  { id: 'a26', question: 'La pecking order theory prédit :', options: ['On préfère la dette à l\'equity', 'On préfère l\'autofinancement, puis la dette, puis l\'equity', 'On préfère l\'equity à la dette', 'La structure est indifférente'], correctIndex: 1, explanation: 'Myers & Majluf (1984) : les entreprises préfèrent les fonds internes, puis la dette (moins d\'asymétrie), puis l\'equity en dernier recours.', difficulty: 'hard' },
  { id: 'a27', question: 'Un SPAC est :', options: ['Un fonds de PE', 'Une société-écran cotée pour fusionner avec une cible', 'Un produit dérivé', 'Un régulateur'], correctIndex: 1, explanation: 'Special Purpose Acquisition Company : coquille vide levée en IPO pour ensuite fusionner avec une entreprise cible (alternative à l\'IPO classique).', difficulty: 'medium' },
  { id: 'a28', question: 'Le TRI cible d\'un fonds LBO est :', options: ['5-8%', '10-15%', '20-25%+', '50%+'], correctIndex: 2, explanation: 'Les fonds LBO visent un TRI (IRR) de 20-25%+ sur 5-7 ans, soit un multiple de 2-3x l\'investissement initial.', difficulty: 'medium' },
  { id: 'a29', question: 'La due diligence financière examine principalement :', options: ['Le marché', 'La qualité des résultats et la dette', 'Les brevets', 'Le management'], correctIndex: 1, explanation: 'La FDD analyse la quality of earnings, la dette nette, le BFR normalisé, le CAPEX de maintenance, et les risques cachés.', difficulty: 'medium' },
  { id: 'a30', question: 'Un spin-off est :', options: ['Une fusion', 'La séparation d\'une division en entité cotée indépendante', 'Un LBO', 'Une liquidation'], correctIndex: 1, explanation: 'Le spin-off distribue les actions de la filiale aux actionnaires existants, créant deux sociétés cotées indépendantes.', difficulty: 'easy' },
  { id: 'a31', question: 'Le covenant de levier dans un LBO limite :', options: ['Le ratio Dette/EBITDA', 'Le dividende', 'Les salaires', 'L\'investissement R&D'], correctIndex: 0, explanation: 'Le leverage covenant fixe un ratio max Dette/EBITDA (ex: 5.0x) que l\'emprunteur ne doit pas dépasser.', difficulty: 'medium' },
  { id: 'a32', question: 'La dette mezzanine dans un LBO :', options: ['Est la plus senior', 'Se situe entre la dette senior et l\'equity', 'N\'a pas d\'intérêt', 'Est sans risque'], correctIndex: 1, explanation: 'La mezzanine (subordonnée) a un rang inférieur à la dette senior mais supérieur à l\'equity, avec un rendement plus élevé (12-18%).', difficulty: 'medium' },
  { id: 'a33', question: 'Le rachat d\'actions réduit :', options: ['Le CA', 'Le nombre d\'actions en circulation', 'La dette', 'Les actifs'], correctIndex: 1, explanation: 'Le buyback réduit le nombre d\'actions, augmentant mécaniquement le BPA et le cours, tout en restituant du cash aux actionnaires.', difficulty: 'easy' },
  { id: 'a34', question: 'La trade-off theory équilibre :', options: ['CA et coûts', 'Avantage fiscal de la dette et coûts de faillite', 'Growth et value', 'Risque et rendement'], correctIndex: 1, explanation: 'La structure optimale maximise la valeur en équilibrant le bouclier fiscal de la dette et les coûts de détresse financière.', difficulty: 'hard' },
  { id: 'a35', question: 'Le multiple d\'entrée dans un LBO est typiquement exprimé en :', options: ['P/E', 'EV/EBITDA', 'P/B', 'EV/Sales'], correctIndex: 1, explanation: 'En LBO, on raisonne en EV/EBITDA (ex: entrée à 8x, sortie à 9x) car c\'est le multiple pré-dette le plus pertinent.', difficulty: 'easy' },

  // === PRODUITS DÉRIVÉS (25 questions) ===
  { id: 'a36', question: 'Si les taux montent, le prix des obligations :', options: ['Monte', 'Reste stable', 'Baisse', 'Dépend du coupon'], correctIndex: 2, explanation: 'Relation inverse fondamentale : quand les taux montent, la valeur actuelle des flux futurs baisse, donc le prix de l\'obligation baisse.', difficulty: 'easy' },
  { id: 'a37', question: 'Delta d\'un call ATM est environ :', options: ['0', '0.25', '0.5', '1'], correctIndex: 2, explanation: 'Le delta d\'un call ATM est proche de 0.5. Il mesure la sensibilité du prix de l\'option au mouvement du sous-jacent.', difficulty: 'easy' },
  { id: 'a38', question: 'Black-Scholes suppose :', options: ['Volatilité variable', 'Volatilité constante', 'Marchés à seuil', 'Dividendes continus'], correctIndex: 1, explanation: 'BS suppose : vol constante, taux sans risque constant, pas de dividendes (version de base), distribution log-normale, marché continu.', difficulty: 'medium' },
  { id: 'a39', question: 'Gamma est maximal quand l\'option est :', options: ['Deep ITM', 'ATM proche expiration', 'Deep OTM', 'Longue maturité'], correctIndex: 1, explanation: 'Le gamma est maximal pour les options ATM proches de l\'expiration, car le delta change rapidement autour du strike.', difficulty: 'hard' },
  { id: 'a40', question: 'Vega mesure la sensibilité à :', options: ['Le prix du sous-jacent', 'Le temps', 'La volatilité implicite', 'Les taux d\'intérêt'], correctIndex: 2, explanation: 'Vega = δC/δσ. Il mesure combien le prix de l\'option change pour 1% de variation de la volatilité implicite.', difficulty: 'easy' },
  { id: 'a41', question: 'Un put protecteur (protective put) :', options: ['Génère un revenu', 'Limite la perte sur une position longue', 'Augmente le levier', 'Est toujours profitable'], correctIndex: 1, explanation: 'Acheter un put sur un actif détenu crée un plancher de perte : c\'est une assurance portfolio.', difficulty: 'easy' },
  { id: 'a42', question: 'La parité put-call stipule :', options: ['C = P', 'C + PV(K) = P + S', 'C - P = S', 'C × P = K'], correctIndex: 1, explanation: 'Put-call parity : C + PV(K) = P + S (call + valeur actuelle du strike = put + sous-jacent). Fondamental en pricing d\'options.', difficulty: 'hard' },
  { id: 'a43', question: 'Un straddle combine :', options: ['Un call et un put même strike', 'Deux calls différents', 'Un call et une action', 'Un swap et un forward'], correctIndex: 0, explanation: 'Le straddle = long call + long put même strike/maturité. Pari sur un grand mouvement, direction indifférente.', difficulty: 'medium' },
  { id: 'a44', question: 'La VaR 95% à 1 jour de 10M€ signifie :', options: ['Perte maximale = 10M€', 'Probabilité 5% de perdre plus de 10M€ en 1 jour', 'Gain attendu = 10M€', 'Rendement = 5%'], correctIndex: 1, explanation: 'VaR 95% = dans 5% des cas (1 jour sur 20), la perte dépassera 10M€. Ce n\'est pas la perte maximale.', difficulty: 'medium' },
  { id: 'a45', question: 'Un CDS (Credit Default Swap) est :', options: ['Un swap de taux', 'Une assurance contre le défaut', 'Un forward sur actions', 'Un future sur obligations'], correctIndex: 1, explanation: 'Le CDS est un contrat où l\'acheteur paie une prime périodique et reçoit un paiement en cas de défaut de l\'entité de référence.', difficulty: 'easy' },
  { id: 'a46', question: 'Theta est toujours négatif pour :', options: ['Les options vendues', 'Les options achetées (long)', 'Les futures', 'Les swaps'], correctIndex: 1, explanation: 'Le theta (time decay) est négatif pour les positions longues options : la valeur temps s\'érode chaque jour.', difficulty: 'medium' },
  { id: 'a47', question: 'Monte Carlo est utilisé pour pricer :', options: ['Des forwards', 'Des options exotiques path-dependent', 'Des swaps vanille', 'Des actions'], correctIndex: 1, explanation: 'Monte Carlo simule de nombreux chemins de prix pour estimer le payoff moyen d\'options complexes (asiatiques, barrières, etc.).', difficulty: 'medium' },
  { id: 'a48', question: 'Le smile de volatilité montre :', options: ['La vol implicite est constante', 'La vol implicite varie selon le strike', 'La vol historique augmente', 'Le temps augmente la vol'], correctIndex: 1, explanation: 'Le smile montre que les options OTM/ITM ont des vol implicites plus élevées que les ATM, contredisant Black-Scholes.', difficulty: 'hard' },
  { id: 'a49', question: 'Un knock-out barrier option :', options: ['S\'active si le sous-jacent touche la barrière', 'S\'éteint si le sous-jacent touche la barrière', 'N\'expire jamais', 'A un payoff illimité'], correctIndex: 1, explanation: 'Une option knock-out cesse d\'exister si le prix du sous-jacent atteint le niveau barrière. Moins chère qu\'une vanille.', difficulty: 'medium' },
  { id: 'a50', question: 'Expected Shortfall (CVaR) mesure :', options: ['La perte médiane', 'La perte moyenne au-delà de la VaR', 'Le gain maximum', 'La volatilité'], correctIndex: 1, explanation: 'L\'ES (ou CVaR) est la moyenne des pertes dans le tail au-delà de la VaR. Plus conservateur et sous-additif contrairement à la VaR.', difficulty: 'hard' },

  // === PORTEFEUILLE & MARCHÉ (25 questions) ===
  { id: 'a51', question: 'Le ratio de Sharpe mesure :', options: ['Le rendement absolu', 'Le rendement ajusté du risque', 'La volatilité', 'Le beta'], correctIndex: 1, explanation: 'Sharpe = (Rp - Rf) / σp. Il mesure l\'excès de rendement par unité de risque total (volatilité).', difficulty: 'easy' },
  { id: 'a52', question: 'CAPM dit que le rendement attendu = :', options: ['Rf + β(Rm-Rf)', 'Rf × β', 'Rm + α', 'σ × β'], correctIndex: 0, explanation: 'E(Ri) = Rf + βi(E(Rm) - Rf). Le rendement est proportionnel au risque systématique (beta).', difficulty: 'easy' },
  { id: 'a53', question: 'Alpha positif signifie :', options: ['Sous-performance vs CAPM', 'Surperformance vs CAPM', 'Risque élevé', 'Beta > 1'], correctIndex: 1, explanation: 'Alpha = rendement réel - rendement prédit par CAPM. Alpha > 0 = le gérant génère de la valeur ajoutée.', difficulty: 'easy' },
  { id: 'a54', question: 'Markowitz a montré que la diversification :', options: ['Élimine tout risque', 'Réduit le risque spécifique mais pas systématique', 'Augmente le rendement', 'Est inutile'], correctIndex: 1, explanation: 'La diversification élimine le risque idiosyncratique mais pas le risque de marché (systématique). C\'est le fondement de la théorie moderne du portefeuille.', difficulty: 'easy' },
  { id: 'a55', question: 'Le modèle Fama-French 3 facteurs ajoute au CAPM :', options: ['Momentum et quality', 'Size (SMB) et Value (HML)', 'Volatilité et liquidité', 'ESG et sentiment'], correctIndex: 1, explanation: 'FF3 = CAPM + SMB (Small minus Big, prime taille) + HML (High minus Low B/M, prime value).', difficulty: 'medium' },
  { id: 'a56', question: 'L\'allocation stratégique se décide :', options: ['Quotidiennement', 'Sur le long terme (3-10 ans)', 'À chaque earnings', 'Jamais'], correctIndex: 1, explanation: 'L\'allocation stratégique définit les poids cibles long terme entre classes d\'actifs selon le profil rendement/risque de l\'investisseur.', difficulty: 'easy' },
  { id: 'a57', question: 'Le Sortino ratio diffère du Sharpe en utilisant :', options: ['La variance totale', 'La semi-variance (downside deviation)', 'Le beta', 'Le max drawdown'], correctIndex: 1, explanation: 'Sortino = (Rp - Rf) / Downside Deviation. Il ne pénalise que la volatilité à la baisse, plus pertinent pour la plupart des investisseurs.', difficulty: 'medium' },
  { id: 'a58', question: 'Le tracking error mesure :', options: ['L\'écart entre rendement et benchmark', 'La volatilité du marché', 'Le rendement absolu', 'Le beta du portefeuille'], correctIndex: 0, explanation: 'TE = σ(Rp - Rb). C\'est la volatilité des écarts de rendement par rapport au benchmark. Plus le TE est bas, plus la gestion est passive.', difficulty: 'medium' },
  { id: 'a59', question: 'ETF vs fonds actif, avantage principal de l\'ETF :', options: ['Meilleur rendement garanti', 'Frais de gestion plus bas', 'Pas de risque', 'Levier intégré'], correctIndex: 1, explanation: 'Les ETF ont des frais (TER) de 0.05-0.50% vs 1-2% pour les fonds actifs. Peu de fonds actifs battent leur indice après frais.', difficulty: 'easy' },
  { id: 'a60', question: 'Growth investing privilégie :', options: ['Des entreprises sous-évaluées', 'Des entreprises à forte croissance du CA/BPA', 'Des entreprises à dividende élevé', 'Des entreprises en difficulté'], correctIndex: 1, explanation: 'Le growth investing recherche des sociétés à forte croissance, même si les multiples semblent élevés (ex: tech, SaaS).', difficulty: 'easy' },

  // === MACROÉCONOMIE (20 questions) ===
  { id: 'a61', question: 'Le PIB mesure :', options: ['La richesse totale d\'un pays', 'La production de biens et services sur une période', 'Les exportations nettes', 'Le taux de chômage'], correctIndex: 1, explanation: 'Le PIB = somme des valeurs ajoutées = C + I + G + (X - M). C\'est un flux (production annuelle), pas un stock.', difficulty: 'easy' },
  { id: 'a62', question: 'L\'inversion de la courbe des taux signale :', options: ['Une expansion', 'Un risque de récession', 'De l\'inflation', 'Une hausse des actions'], correctIndex: 1, explanation: 'Quand les taux courts dépassent les taux longs, cela a historiquement précédé les récessions dans 80% des cas.', difficulty: 'medium' },
  { id: 'a63', question: 'Le QE (Quantitative Easing) consiste à :', options: ['Augmenter les taux', 'Acheter des obligations pour injecter des liquidités', 'Réduire le budget', 'Augmenter les impôts'], correctIndex: 1, explanation: 'La banque centrale achète massivement des titres (govt bonds, MBS) pour baisser les taux longs et stimuler l\'économie.', difficulty: 'easy' },
  { id: 'a64', question: 'La PPP (Parité de Pouvoir d\'Achat) dit :', options: ['Les taux de change sont fixes', 'Les prix des biens devraient s\'égaliser entre pays', 'Les taux d\'intérêt sont identiques', 'Le PIB est constant'], correctIndex: 1, explanation: 'En théorie, un panier de biens devrait coûter le même prix partout. Les écarts de change devraient refléter les différentiels d\'inflation.', difficulty: 'medium' },
  { id: 'a65', question: 'La balance courante inclut :', options: ['Uniquement les biens', 'Biens, services, revenus, transferts', 'Flux de capitaux', 'Réserves de change'], correctIndex: 1, explanation: 'La balance courante = balance commerciale (biens+services) + revenus primaires (investissements) + transferts courants.', difficulty: 'medium' },
  { id: 'a66', question: 'L\'inflation "core" exclut :', options: ['Les loyers', 'L\'alimentation et l\'énergie', 'Les salaires', 'Les services'], correctIndex: 1, explanation: 'L\'inflation sous-jacente (core) exclut alimentation et énergie (volatils) pour mieux refléter la tendance de fond.', difficulty: 'easy' },
  { id: 'a67', question: 'Le multiplicateur keynésien implique :', options: ['Les dépenses publiques réduisent le PIB', 'Un euro de dépense génère plus d\'un euro de PIB', 'L\'épargne stimule l\'économie', 'La monnaie est neutre'], correctIndex: 1, explanation: 'Le multiplicateur (1/(1-c) où c = propension à consommer) montre qu\'une dépense initiale génère un effet en cascade sur le PIB.', difficulty: 'medium' },
  { id: 'a68', question: 'Le "forward guidance" est :', options: ['Une stratégie d\'investissement', 'La communication de la banque centrale sur ses intentions', 'Un produit dérivé', 'Un indice boursier'], correctIndex: 1, explanation: 'Le forward guidance est l\'outil de communication par lequel la BC guide les anticipations de marché sur la politique monétaire future.', difficulty: 'medium' },
  { id: 'a69', question: 'La crise de 2008 a été déclenchée par :', options: ['La dette souveraine', 'Les subprimes et la titrisation', 'Le pétrole', 'Le Brexit'], correctIndex: 1, explanation: 'La crise est partie des défauts sur les crédits subprime américains, amplifiée par la titrisation (MBS, CDO) et le manque de transparence.', difficulty: 'easy' },
  { id: 'a70', question: 'Le taux d\'intérêt réel = :', options: ['Taux nominal + inflation', 'Taux nominal - inflation', 'Taux nominal × inflation', 'Taux nominal / inflation'], correctIndex: 1, explanation: 'Approximation de Fisher : r réel ≈ r nominal - π (inflation). Le taux réel reflète le vrai rendement du capital.', difficulty: 'easy' },

  // === FIXED INCOME (15 questions) ===
  { id: 'a71', question: 'La duration mesure :', options: ['La maturité', 'La sensibilité du prix aux taux', 'Le coupon', 'Le spread'], correctIndex: 1, explanation: 'La duration modifiée mesure la variation en % du prix pour 1% de variation des taux. Duration ↑ = sensibilité ↑.', difficulty: 'easy' },
  { id: 'a72', question: 'Une obligation zéro-coupon a une duration :', options: ['Nulle', 'Égale à sa maturité', 'Supérieure à sa maturité', 'Inférieure à 1'], correctIndex: 1, explanation: 'Pour un zéro-coupon, la duration de Macaulay = maturité, car il n\'y a qu\'un seul flux à la maturité.', difficulty: 'medium' },
  { id: 'a73', question: 'Le bootstrapping sert à :', options: ['Calculer le PIB', 'Construire la courbe zéro-coupon', 'Pricer les actions', 'Mesurer l\'inflation'], correctIndex: 1, explanation: 'Le bootstrapping extrait les taux zéro-coupon implicites à partir des prix des obligations couponnées.', difficulty: 'hard' },
  { id: 'a74', question: 'Un bond "Investment Grade" a un rating :', options: ['BB+ ou moins', 'BBB- ou plus', 'CCC', 'Non noté'], correctIndex: 1, explanation: 'IG = BBB-/Baa3 et au-dessus. En dessous (BB+/Ba1), c\'est du High Yield ("junk bonds").', difficulty: 'easy' },
  { id: 'a75', question: 'Le spread OAS (Option-Adjusted Spread) :', options: ['Ignore les options intégrées', 'Ajuste le spread pour les options intégrées', 'Mesure le rendement total', 'Est toujours nul'], correctIndex: 1, explanation: 'L\'OAS isole le spread de crédit en retirant la valeur des options embedded (calls, puts) dans les obligations.', difficulty: 'hard' },
  { id: 'a76', question: 'La convexité est positive quand :', options: ['Le prix baisse avec les taux', 'Le prix réagit plus à une baisse de taux qu\'à une hausse', 'La duration est nulle', 'L\'obligation est à taux variable'], correctIndex: 1, explanation: 'La convexité positive = la hausse du prix quand les taux baissent est plus grande que la baisse quand les taux montent. C\'est une propriété favorable.', difficulty: 'hard' },
  { id: 'a77', question: 'Un repo (repurchase agreement) est :', options: ['Un prêt avec collatéral obligataire', 'Un dérivé de crédit', 'Une option sur taux', 'Un swap de devises'], correctIndex: 0, explanation: 'Le repo = vente d\'un titre avec engagement de rachat. C\'est un emprunt garanti, fondamental pour le financement bancaire.', difficulty: 'medium' },
  { id: 'a78', question: 'Un MBS (Mortgage-Backed Security) :', options: ['Est sans risque', 'Est adossé à des crédits hypothécaires', 'Est un produit equity', 'N\'a pas de cash flows'], correctIndex: 1, explanation: 'Les MBS sont des titres adossés à des pools de crédits immobiliers. Le risque principal est le prépaiement.', difficulty: 'easy' },
  { id: 'a79', question: 'Les Green Bonds financent :', options: ['Toutes les entreprises', 'Des projets environnementaux spécifiques', 'La défense', 'Les crypto'], correctIndex: 1, explanation: 'Les green bonds financent des projets à bénéfice environnemental (énergies renouvelables, efficacité énergétique, transport propre).', difficulty: 'easy' },
  { id: 'a80', question: 'L\'immunisation en gestion obligataire :', options: ['Élimine tout risque', 'Match la duration du portefeuille avec l\'horizon d\'investissement', 'Maximise le rendement', 'Ignore les taux'], correctIndex: 1, explanation: 'L\'immunisation protège contre les variations de taux en alignant la duration du portefeuille avec l\'horizon d\'investissement.', difficulty: 'medium' },

  // === PRIVATE EQUITY & VC (15 questions) ===
  { id: 'a81', question: 'La J-curve en PE montre :', options: ['Des rendements positifs dès le début', 'Des pertes initiales puis des gains', 'Un rendement constant', 'Une croissance linéaire'], correctIndex: 1, explanation: 'La J-curve reflète les fees et investissements initiaux (NAV<100) puis les plus-values de sortie. Le fonds est négatif les 3-4 premières années.', difficulty: 'medium' },
  { id: 'a82', question: 'Le carried interest est :', options: ['Le salaire du GP', 'La part des profits du GP (typiquement 20%)', 'Les frais de gestion', 'L\'intérêt sur la dette'], correctIndex: 1, explanation: 'Le carry = 20% des profits au-delà du hurdle rate (généralement 8%). C\'est la rémunération à la performance du GP.', difficulty: 'medium' },
  { id: 'a83', question: 'MOIC 3.0x signifie :', options: ['Rendement de 3%', 'Triple de l\'investissement', 'IRR de 30%', 'Duration de 3 ans'], correctIndex: 1, explanation: 'MOIC (Multiple on Invested Capital) = 3.0x signifie que chaque euro investi a généré 3 euros (2 euros de profit).', difficulty: 'easy' },
  { id: 'a84', question: 'Un term sheet VC contient :', options: ['Le code source', 'Valorisation, droits, liquidation preferences', 'Le business plan', 'Les comptes annuels'], correctIndex: 1, explanation: 'Le term sheet fixe : pre/post-money valuation, type d\'actions (preferred), liquidation preferences, anti-dilution, board seats, vesting.', difficulty: 'medium' },
  { id: 'a85', question: 'La dilution cap table survient quand :', options: ['Le CA baisse', 'De nouvelles actions sont émises', 'Des dividendes sont versés', 'La dette augmente'], correctIndex: 1, explanation: 'Chaque tour de financement émet de nouvelles actions, diluant les actionnaires existants. La cap table suit l\'évolution de la propriété.', difficulty: 'easy' },
  { id: 'a86', question: 'Le vesting cliff de 1 an signifie :', options: ['Pas d\'actions la 1ère année, puis acquisition progressive', 'Toutes les actions après 1 an', 'Aucun vesting', 'Actions vendues après 1 an'], correctIndex: 0, explanation: 'Avec un cliff de 1 an sur 4 ans de vesting : 0 actions avant 12 mois, puis 25% d\'un coup, puis mensuel pendant 3 ans.', difficulty: 'medium' },
  { id: 'a87', question: 'Un SAFE (Simple Agreement for Future Equity) :', options: ['Est une dette', 'Se convertit en equity lors d\'un prochain tour', 'Donne du voting power immédiat', 'Est un prêt bancaire'], correctIndex: 1, explanation: 'Le SAFE (inventé par YC) est un instrument simple qui se convertit automatiquement en preferred lors du prochain tour de financement.', difficulty: 'medium' },
  { id: 'a88', question: 'La liquidation preference 1x non-participating :', options: ['Le VC récupère son investissement OU sa part pro-rata', 'Le VC récupère 2x son investissement', 'Le VC n\'a aucun droit', 'Le fondateur est protégé'], correctIndex: 0, explanation: 'Avec 1x non-participating, le VC choisit le meilleur entre : récupérer sa mise (downside protection) OU convertir en common (upside).', difficulty: 'hard' },

  // === REGULATION & ESG (15 questions) ===
  { id: 'a89', question: 'Le ratio CET1 de Bâle III minimum est :', options: ['2%', '4.5%', '8%', '10%'], correctIndex: 1, explanation: 'CET1 minimum = 4.5% des actifs pondérés (RWA). Avec les buffers (conservation 2.5%, countercyclical, systemic), ça monte à 10-14%.', difficulty: 'medium' },
  { id: 'a90', question: 'MiFID II vise principalement :', options: ['La protection des investisseurs et la transparence des marchés', 'La régulation bancaire', 'La politique monétaire', 'La fiscalité'], correctIndex: 0, explanation: 'MiFID II renforce la protection des investisseurs, la transparence (pré/post-trade), la gouvernance des produits, et les règles de best execution.', difficulty: 'easy' },
  { id: 'a91', question: 'Le LCR (Liquidity Coverage Ratio) exige :', options: ['Fonds propres > 8%', 'Actifs liquides ≥ sorties nettes à 30 jours', 'Dette < 3x capitaux propres', 'Rendement > 5%'], correctIndex: 1, explanation: 'LCR = HQLA / Net Cash Outflows (30 days) ≥ 100%. La banque doit pouvoir survivre 30 jours de stress.', difficulty: 'hard' },
  { id: 'a92', question: 'ESG signifie :', options: ['Economic Systemic Growth', 'Environmental Social Governance', 'European Securities Group', 'Equity Share Guarantee'], correctIndex: 1, explanation: 'ESG = critères Environnementaux, Sociaux et de Gouvernance utilisés pour évaluer la durabilité des investissements.', difficulty: 'easy' },
  { id: 'a93', question: 'La taxonomie européenne définit :', options: ['Les taux d\'impôt', 'Les activités économiques considérées comme durables', 'Les indices boursiers', 'Les taux directeurs'], correctIndex: 1, explanation: 'La EU Taxonomy est un système de classification qui définit quelles activités sont "environnementally sustainable" selon 6 objectifs.', difficulty: 'medium' },
  { id: 'a94', question: 'SFDR classe les fonds en :', options: ['Grade A, B, C', 'Article 6, 8, 9', 'Tier 1, 2, 3', 'Green, Yellow, Red'], correctIndex: 1, explanation: 'SFDR : Art.6 (pas d\'engagement ESG), Art.8 (promouvant ESG), Art.9 (objectif d\'investissement durable). De plus en plus de fonds visent Art.8+.', difficulty: 'medium' },
  { id: 'a95', question: 'KYC signifie :', options: ['Keep Your Cash', 'Know Your Customer', 'Key Yield Calculation', 'Knowledge Year Certificate'], correctIndex: 1, explanation: 'Know Your Customer est le processus d\'identification et de vérification des clients pour lutter contre le blanchiment et le financement du terrorisme.', difficulty: 'easy' },

  // === CRYPTO & IMMOBILIER (15 questions) ===
  { id: 'a96', question: 'Le consensus PoS (Proof of Stake) :', options: ['Requiert du minage intensif', 'Sélectionne les validateurs selon leur mise', 'N\'utilise pas de blockchain', 'Est centralisé'], correctIndex: 1, explanation: 'En PoS, les validateurs sont choisis proportionnellement à leur stake (tokens mis en jeu), ce qui est bien plus économe en énergie que le PoW.', difficulty: 'easy' },
  { id: 'a97', question: 'Un stablecoin est :', options: ['Une crypto très volatile', 'Un token adossé à un actif stable (USD, or)', 'Un NFT', 'Une blockchain'], correctIndex: 1, explanation: 'Les stablecoins (USDT, USDC, DAI) maintiennent une parité ~1:1 avec un actif de référence, servant de refuge et de moyen d\'échange dans la DeFi.', difficulty: 'easy' },
  { id: 'a98', question: 'Le cap rate en immobilier = :', options: ['Prix / Loyer', 'NOI / Prix d\'acquisition', 'Loyer / CAPEX', 'LTV × DSCR'], correctIndex: 1, explanation: 'Cap Rate = Net Operating Income / Valeur du bien. C\'est le taux de rendement immobilier avant financement. Cap rate ↑ = prix ↓.', difficulty: 'medium' },
  { id: 'a99', question: 'Le NOI (Net Operating Income) exclut :', options: ['Les loyers', 'Les charges opérationnelles', 'Le service de la dette et l\'impôt', 'Les taxes foncières'], correctIndex: 2, explanation: 'NOI = Revenus locatifs - Charges opérationnelles (hors dette, hors IS). C\'est le résultat opérationnel immobilier.', difficulty: 'medium' },
  { id: 'a100', question: 'Un REIT est :', options: ['Un fonds de private equity', 'Une société immobilière cotée qui distribue ses loyers', 'Un produit dérivé', 'Un type de prêt'], correctIndex: 1, explanation: 'Le REIT (Real Estate Investment Trust) est un véhicule coté qui détient et gère de l\'immobilier, distribuant ≥90% de ses revenus.', difficulty: 'easy' },
  { id: 'a101', question: 'DeFi signifie :', options: ['Definitive Finance', 'Decentralized Finance', 'Default Insurance', 'Derivative Financing'], correctIndex: 1, explanation: 'DeFi = Finance Décentralisée sur blockchain. Protocoles de lending (Aave), DEX (Uniswap), yield farming, sans intermédiaire centralisé.', difficulty: 'easy' },
  { id: 'a102', question: 'Le LTV (Loan-to-Value) en immobilier mesure :', options: ['Le rendement locatif', 'Le ratio dette/valeur du bien', 'Le taux d\'occupation', 'Les charges de copropriété'], correctIndex: 1, explanation: 'LTV = Montant du prêt / Valeur du bien. Un LTV de 70% signifie 70% de dette et 30% d\'apport. Plus le LTV est élevé, plus le risque.', difficulty: 'easy' },
  { id: 'a103', question: 'Le yield farming consiste à :', options: ['Cultiver des cryptos', 'Fournir de la liquidité en échange de rewards', 'Miner du Bitcoin', 'Acheter des NFT'], correctIndex: 1, explanation: 'Le yield farming = déposer des tokens dans des protocoles DeFi (lending, LP) pour recevoir des récompenses (intérêts + tokens de gouvernance).', difficulty: 'medium' },

  // === ASSURANCE & FINANCES PERSO (15 questions) ===
  { id: 'a104', question: 'Solvabilité II s\'applique à :', options: ['Les banques', 'Les assureurs européens', 'Les fonds de pension', 'Les crypto'], correctIndex: 1, explanation: 'Solvabilité II est le cadre réglementaire prudentiel européen pour les compagnies d\'assurance, structuré en 3 piliers.', difficulty: 'easy' },
  { id: 'a105', question: 'Le SCR (Solvency Capital Requirement) :', options: ['Est le capital minimum absolu', 'Est le capital requis pour absorber un choc 1/200 ans', 'Est le ratio de rentabilité', 'Est le plafond de dette'], correctIndex: 1, explanation: 'Le SCR est le capital nécessaire pour survivre à un choc de probabilité 0.5% (1 fois tous les 200 ans), calibré en VaR 99.5%.', difficulty: 'hard' },
  { id: 'a106', question: 'L\'intérêt composé, Einstein l\'appelait :', options: ['La 8e merveille du monde', 'Un piège financier', 'Un mythe', 'Un impôt caché'], correctIndex: 0, explanation: 'L\'intérêt composé fait croître un capital de façon exponentielle : 10 000€ à 8%/an = 21 589€ en 10 ans, 46 610€ en 20 ans.', difficulty: 'easy' },
  { id: 'a107', question: 'Le PEA (Plan d\'Épargne en Actions) offre :', options: ['Un crédit d\'impôt', 'Une exonération d\'IR sur les plus-values après 5 ans', 'Un rendement garanti', 'Un levier x10'], correctIndex: 1, explanation: 'Le PEA permet d\'investir en actions européennes avec exonération d\'IR sur les plus-values après 5 ans de détention (PS de 17.2% restants).', difficulty: 'easy' },
  { id: 'a108', question: 'La règle des 72 donne :', options: ['Le rendement optimal', 'Le temps pour doubler un capital (72/taux)', 'Le montant d\'épargne idéal', 'Le ratio dette/revenus'], correctIndex: 1, explanation: 'Règle des 72 : 72 / taux d\'intérêt ≈ nombre d\'années pour doubler. Ex: à 8%, capital double en ~9 ans.', difficulty: 'easy' },
  { id: 'a109', question: 'Le fonds d\'urgence recommandé est de :', options: ['1 mois de dépenses', '3-6 mois de dépenses', '1 an de salaire', '10% de l\'épargne'], correctIndex: 1, explanation: '3-6 mois de dépenses courantes en épargne liquide (livrets) pour faire face aux imprévus sans toucher aux investissements.', difficulty: 'easy' },
  { id: 'a110', question: 'L\'assurance-vie en France est :', options: ['Uniquement un produit décès', 'Un véhicule d\'épargne multi-supports avec avantage fiscal', 'Un compte bancaire', 'Un PEA'], correctIndex: 1, explanation: 'L\'assurance-vie est l\'enveloppe fiscale préférée des Français : fonds euros + unités de compte, avantage succession, fiscal après 8 ans.', difficulty: 'easy' },

  // === QUESTIONS BONUS — CALCUL MENTAL & BRAINTEASERS (20 questions) ===
  { id: 'a111', question: 'Si un actif perd 50%, combien doit-il gagner pour revenir à son niveau initial ?', options: ['50%', '75%', '100%', '200%'], correctIndex: 2, explanation: '100€ → -50% → 50€. Pour revenir à 100€, il faut +50€ soit +100% de 50€. Les pertes nécessitent des gains supérieurs.', difficulty: 'easy' },
  { id: 'a112', question: '10 000€ placés à 7%/an pendant 10 ans donnent environ :', options: ['17 000€', '19 672€', '22 000€', '25 000€'], correctIndex: 1, explanation: '10 000 × (1.07)^10 ≈ 19 672€. L\'intérêt composé fait environ doubler en 10 ans à 7%.', difficulty: 'medium' },
  { id: 'a113', question: 'Un P/E de 20x signifie que le marché paie :', options: ['20€ par euro de bénéfice', '20% de rendement', '20 fois le CA', '20 ans de dividendes'], correctIndex: 0, explanation: 'P/E = Prix / BPA. Un P/E de 20x signifie que les investisseurs paient 20€ pour chaque euro de bénéfice annuel.', difficulty: 'easy' },
  { id: 'a114', question: 'Si l\'EUR/USD passe de 1.10 à 1.15, l\'euro s\'est :', options: ['Déprécié', 'Apprécié', 'Pas bougé', 'Impossible à dire'], correctIndex: 1, explanation: '1 EUR achète maintenant 1.15 USD au lieu de 1.10 USD. L\'euro a gagné en valeur, il s\'est apprécié.', difficulty: 'easy' },
  { id: 'a115', question: 'Un taux annuel de 12% correspond à un taux mensuel de :', options: ['1%', '1.12%', '0.95%', '12%'], correctIndex: 0, explanation: 'En approximation simple : 12% / 12 = 1% par mois. En taux composé exact : (1.12)^(1/12) - 1 ≈ 0.949%, mais 1% est l\'approximation usuelle.', difficulty: 'easy' },
  { id: 'a116', question: 'WACC = 10%, FCF1 = 100M€, g = 2%. Valeur terminale (Gordon) :', options: ['1 000M€', '1 250M€', '1 500M€', '2 000M€'], correctIndex: 1, explanation: 'TV = FCF1 × (1+g) / (WACC - g) = 100 × 1.02 / 0.08 = 1 275M€ ≈ 1 250M€. Ou approximation : 100 / (0.10 - 0.02) = 1 250M€.', difficulty: 'medium' },
  { id: 'a117', question: 'Si beta = 1.5, Rf = 3%, Rm-Rf = 6%, le Ke (CAPM) = :', options: ['9%', '10%', '12%', '15%'], correctIndex: 2, explanation: 'Ke = Rf + β(Rm-Rf) = 3% + 1.5 × 6% = 3% + 9% = 12%.', difficulty: 'medium' },
  { id: 'a118', question: 'EV = 1 000M€, EBITDA = 125M€. Multiple EV/EBITDA = :', options: ['6.0x', '7.0x', '8.0x', '10.0x'], correctIndex: 2, explanation: '1 000 / 125 = 8.0x. Ce multiple est dans la fourchette typique pour une entreprise mid-market.', difficulty: 'easy' },
  { id: 'a119', question: 'Un LBO entre à 8x EBITDA, EBITDA de 50M€. EV d\'entrée = :', options: ['200M€', '300M€', '400M€', '500M€'], correctIndex: 2, explanation: 'EV = 8x × 50M€ = 400M€. Avec 60% de dette (240M€) et 40% d\'equity (160M€), c\'est un montage LBO classique.', difficulty: 'easy' },
  { id: 'a120', question: 'Duration de 5 ans + taux montent de 1% = prix change d\'environ :', options: ['-1%', '-3%', '-5%', '-10%'], correctIndex: 2, explanation: 'ΔP/P ≈ -D × Δr = -5 × 0.01 = -5%. La duration est l\'approximation linéaire de la sensibilité du prix aux taux.', difficulty: 'medium' },
  { id: 'a121', question: 'Combien vaut 1$ dans 10 ans si l\'inflation est de 3%/an ?', options: ['$1.30', '$0.97', '$0.74', '$0.50'], correctIndex: 2, explanation: '1 / (1.03)^10 ≈ 0.744$. L\'inflation à 3%/an érode ~26% du pouvoir d\'achat en 10 ans.', difficulty: 'medium' },
  { id: 'a122', question: 'Un portefeuille 60/40 signifie :', options: ['60% obligations, 40% actions', '60% actions, 40% obligations', '60% cash, 40% immo', '60% France, 40% étranger'], correctIndex: 1, explanation: 'L\'allocation classique 60/40 = 60% actions (croissance) + 40% obligations (stabilité). Portefeuille historiquement équilibré.', difficulty: 'easy' },
  { id: 'a123', question: 'Le risque de change affecte :', options: ['Uniquement les entreprises domestiques', 'Les investissements en devises étrangères', 'Uniquement les obligations', 'Uniquement le cash'], correctIndex: 1, explanation: 'Le risque de change (FX risk) impacte tout investissement libellé en devise étrangère. Un USD/EUR défavorable peut annuler le rendement.', difficulty: 'easy' },
  { id: 'a124', question: 'L\'effet de levier en LBO amplifie :', options: ['Uniquement les gains', 'Uniquement les pertes', 'Les gains ET les pertes', 'Le CA'], correctIndex: 2, explanation: 'Le levier amplifie les rendements dans les deux sens : si l\'EV augmente, l\'equity gagne plus ; si l\'EV baisse, l\'equity perd plus.', difficulty: 'easy' },
  { id: 'a125', question: 'La corrélation de -1 entre deux actifs signifie :', options: ['Ils bougent ensemble', 'Ils bougent en sens inverse parfaitement', 'Ils sont indépendants', 'Corrélation impossible'], correctIndex: 1, explanation: 'ρ = -1 : corrélation négative parfaite. Quand l\'un monte, l\'autre baisse exactement. C\'est le cas idéal de diversification.', difficulty: 'easy' },
];

export function getRandomQuestions(count: number, difficulty?: 'easy' | 'medium' | 'hard'): QuizQuestion[] {
  let pool = [...ARENA_POOL];
  if (difficulty) {
    pool = pool.filter((q) => q.difficulty === difficulty);
  }
  const shuffled = pool.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getQuestionsByDifficulty(
  easy: number,
  medium: number,
  hard: number
): QuizQuestion[] {
  const easyQs = getRandomQuestions(easy, 'easy');
  const mediumQs = getRandomQuestions(medium, 'medium');
  const hardQs = getRandomQuestions(hard, 'hard');
  return [...easyQs, ...mediumQs, ...hardQs].sort(() => Math.random() - 0.5);
}
