// ──────────────────────────────────────────────
//  FINA - Course Catalogue Metadata
// ──────────────────────────────────────────────

export interface CourseMetadata {
  id: string;
  title: string;
  subtitle: string;
  color: string;
  level: 'Débutant' | 'Intermédiaire' | 'Avancé';
  source: string;
  totalXP: number;
  lessonCount: number;
  duration: string;
  learners: number;
  finnRole: string;
  finnTier: 'orange' | 'gold' | 'silver';
  chartType: 'bars' | 'line' | 'candle' | 'pie' | 'curve';
}

export const COURSES: CourseMetadata[] = [
  {
    id: 'fundamentals',
    title: 'Les Fondamentaux',
    subtitle: 'Du bilan au DCF : les bases incontournables de la finance d\'entreprise',
    color: '#16A34A',
    level: 'Débutant',
    source: 'Vernimmen',
    totalXP: 4800,
    lessonCount: 24,
    duration: '12h',
    learners: 12430,
    finnRole: 'doctor',
    finnTier: 'orange',
    chartType: 'bars',
  },
  {
    id: 'corporate',
    title: 'Corporate Finance',
    subtitle: 'Fusions, acquisitions et structuration financière des entreprises',
    color: '#2563EB',
    level: 'Intermédiaire',
    source: 'Rosenbaum',
    totalXP: 5600,
    lessonCount: 28,
    duration: '18h',
    learners: 8920,
    finnRole: 'banker',
    finnTier: 'orange',
    chartType: 'line',
  },
  {
    id: 'derivatives',
    title: 'Produits Dérivés',
    subtitle: 'Options, futures, swaps : pricing et stratégies de couverture',
    color: '#7C3AED',
    level: 'Avancé',
    source: 'John C. Hull',
    totalXP: 7000,
    lessonCount: 35,
    duration: '24h',
    learners: 5640,
    finnRole: 'wizard',
    finnTier: 'orange',
    chartType: 'curve',
  },
  {
    id: 'portfolio',
    title: 'Gestion de Portefeuille',
    subtitle: 'Théorie moderne du portefeuille, allocation d\'actifs et gestion du risque',
    color: '#DB2777',
    level: 'Intermédiaire',
    source: 'Markowitz',
    totalXP: 5200,
    lessonCount: 26,
    duration: '16h',
    learners: 7810,
    finnRole: 'captain',
    finnTier: 'orange',
    chartType: 'pie',
  },
  {
    id: 'macro',
    title: 'Macroéconomie',
    subtitle: 'Politique monétaire, cycles économiques et marchés financiers',
    color: '#CA8A04',
    level: 'Intermédiaire',
    source: 'Blanchard',
    totalXP: 4400,
    lessonCount: 22,
    duration: '13h',
    learners: 9350,
    finnRole: 'explorer',
    finnTier: 'orange',
    chartType: 'line',
  },
  {
    id: 'accounting',
    title: 'Comptabilité IFRS',
    subtitle: 'Normes internationales, consolidation et retraitements comptables',
    color: '#0D9488',
    level: 'Intermédiaire',
    source: 'IFRS',
    totalXP: 4000,
    lessonCount: 20,
    duration: '11h',
    learners: 4560,
    finnRole: 'professor',
    finnTier: 'orange',
    chartType: 'bars',
  },
  {
    id: 'fixed-income',
    title: 'Fixed Income',
    subtitle: 'Obligations, courbe des taux et stratégies de taux d\'intérêt',
    color: '#0891B2',
    level: 'Avancé',
    source: 'Fabozzi',
    totalXP: 4800,
    lessonCount: 24,
    duration: '17h',
    learners: 4230,
    finnRole: 'astronaut',
    finnTier: 'orange',
    chartType: 'bars',
  },
  {
    id: 'private-equity',
    title: 'Private Equity',
    subtitle: 'LBO, due diligence et création de valeur en capital-investissement',
    color: '#7E22CE',
    level: 'Avancé',
    source: 'Kaplan',
    totalXP: 4400,
    lessonCount: 22,
    duration: '15h',
    learners: 6780,
    finnRole: 'banker',
    finnTier: 'gold',
    chartType: 'bars',
  },
  {
    id: 'venture-capital',
    title: 'Venture Capital',
    subtitle: 'Financement des startups, term sheets et stratégies de sortie',
    color: '#16A34A',
    level: 'Intermédiaire',
    source: 'Brad Feld',
    totalXP: 3600,
    lessonCount: 18,
    duration: '10h',
    learners: 11200,
    finnRole: 'superhero',
    finnTier: 'orange',
    chartType: 'line',
  },
  {
    id: 'equities',
    title: 'Marchés Actions',
    subtitle: 'Valorisation, analyse fondamentale et stratégies d\'investissement en actions',
    color: '#2563EB',
    level: 'Intermédiaire',
    source: 'Damodaran',
    totalXP: 4000,
    lessonCount: 20,
    duration: '12h',
    learners: 8120,
    finnRole: 'detective',
    finnTier: 'orange',
    chartType: 'candle',
  },
  {
    id: 'technical-analysis',
    title: 'Analyse Technique',
    subtitle: 'Figures chartistes, indicateurs et timing de marché',
    color: '#CA8A04',
    level: 'Débutant',
    source: 'Murphy',
    totalXP: 3200,
    lessonCount: 16,
    duration: '9h',
    learners: 14500,
    finnRole: 'artist',
    finnTier: 'orange',
    chartType: 'candle',
  },
  {
    id: 'quantitative',
    title: 'Finance Quantitative',
    subtitle: 'Modèles stochastiques, pricing d\'options et gestion quantitative',
    color: '#4F46E5',
    level: 'Avancé',
    source: 'Wilmott',
    totalXP: 4800,
    lessonCount: 24,
    duration: '20h',
    learners: 3890,
    finnRole: 'astronaut',
    finnTier: 'gold',
    chartType: 'curve',
  },
  {
    id: 'esg',
    title: 'Finance Durable & ESG',
    subtitle: 'Critères ESG, investissement responsable et finance verte',
    color: '#0D9488',
    level: 'Débutant',
    source: 'PRI',
    totalXP: 2800,
    lessonCount: 14,
    duration: '7h',
    learners: 6420,
    finnRole: 'explorer',
    finnTier: 'orange',
    chartType: 'pie',
  },
  {
    id: 'regulation',
    title: 'Réglementation',
    subtitle: 'Bâle III, MiFID II et cadre réglementaire financier européen',
    color: '#64748B',
    level: 'Intermédiaire',
    source: 'Bâle III',
    totalXP: 3600,
    lessonCount: 18,
    duration: '10h',
    learners: 3210,
    finnRole: 'captain',
    finnTier: 'orange',
    chartType: 'bars',
  },
  {
    id: 'real-estate',
    title: 'Finance Immobilière',
    subtitle: 'Valorisation immobilière, REITs et financement de projets',
    color: '#B45309',
    level: 'Intermédiaire',
    source: 'Geltner',
    totalXP: 3200,
    lessonCount: 16,
    duration: '10h',
    learners: 5670,
    finnRole: 'chef',
    finnTier: 'orange',
    chartType: 'bars',
  },
  {
    id: 'crypto',
    title: 'Crypto & Blockchain',
    subtitle: 'Bitcoin, DeFi, smart contracts et tokenisation des actifs',
    color: '#F59E0B',
    level: 'Débutant',
    source: 'Nakamoto',
    totalXP: 3200,
    lessonCount: 16,
    duration: '8h',
    learners: 18900,
    finnRole: 'wizard',
    finnTier: 'orange',
    chartType: 'candle',
  },
  {
    id: 'insurance',
    title: 'Assurance & Actuariat',
    subtitle: 'Tarification, provisions techniques et cadre Solvabilité II',
    color: '#64748B',
    level: 'Intermédiaire',
    source: 'Solvabilité II',
    totalXP: 2800,
    lessonCount: 14,
    duration: '9h',
    learners: 2140,
    finnRole: 'doctor',
    finnTier: 'orange',
    chartType: 'pie',
  },
  {
    id: 'personal-finance',
    title: 'Finances Personnelles',
    subtitle: 'Épargne, investissement, fiscalité et construction de patrimoine',
    color: '#16A34A',
    level: 'Débutant',
    source: 'Housel',
    totalXP: 2800,
    lessonCount: 14,
    duration: '6h',
    learners: 22100,
    finnRole: 'chef',
    finnTier: 'orange',
    chartType: 'line',
  },
];
