// Central content export
// Course metadata and content will be imported from individual course folders
// as they are generated by the content agents

export interface Lesson {
  id: string;
  title: string;
  xp: number;
  duration: string;
  content: {
    introduction: string;
    keyPoints: string[];
    explanation: string;
    formula?: string;
    example?: string;
    finnSays: string;
  };
}

export interface QuizQuestion {
  id: string;
  lessonId?: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface CourseMetadata {
  id: string;
  title: string;
  subtitle: string;
  color: string;
  level: 'Débutant' | 'Intermédiaire' | 'Avancé';
  source: string;
  totalXP: number;
  lessonCount: number;
  duration: string;
  learners: number;
  finnRole: string;
  finnTier: 'orange' | 'gold' | 'silver';
  chartType: 'bars' | 'line' | 'candle' | 'pie' | 'curve';
}
