// ──────────────────────────────────────────────
//  FINA - Finance Durable & ESG : Quiz
// ──────────────────────────────────────────────

import type { QuizQuestion } from '../types';

export const esgQuiz: QuizQuestion[] = [
  {
    id: 'esg-q1',
    lessonId: 'esg-1',
    question: 'Que signifie l\'acronyme ESG ?',
    options: [
      'Environnement, Social, Gouvernance',
      'Économie, Stratégie, Gestion',
      'Énergie, Société, Gouvernement',
      'Éthique, Soutenabilité, Globalisation',
    ],
    correctIndex: 0,
    explanation: 'ESG = Environnement, Social, Gouvernance. Ces trois piliers évaluent la performance extra-financière des entreprises.',
    difficulty: 'easy',
  },
  {
    id: 'esg-q2',
    lessonId: 'esg-1',
    question: 'En quelle année les PRI (Principles for Responsible Investment) ont-ils été lancés par l\'ONU ?',
    options: ['2000', '2003', '2006', '2010'],
    correctIndex: 2,
    explanation: 'Les PRI ont été lancés en 2006 par l\'ONU, marquant le début de l\'investissement responsable institutionnel.',
    difficulty: 'medium',
  },
  {
    id: 'esg-q3',
    lessonId: 'esg-2',
    question: 'Pour une entreprise pétrolière, quel pilier ESG a généralement le poids le plus élevé dans la notation ?',
    options: ['Social', 'Gouvernance', 'Environnement', 'Les trois à parts égales'],
    correctIndex: 2,
    explanation: 'Pour un pétrolier, le pilier E (émissions CO₂, transition énergétique, pollution) pèse environ 50% de la note ESG.',
    difficulty: 'easy',
  },
  {
    id: 'esg-q4',
    lessonId: 'esg-3',
    question: 'Pourquoi les ratings ESG divergent-ils fortement entre agences (corrélation ~0.5) ?',
    options: [
      'Les entreprises fournissent des données différentes à chaque agence',
      'Les agences utilisent des périmètres, mesures et pondérations différents',
      'Les ratings ESG ne sont pas réglementés',
      'Les agences notent des entreprises différentes',
    ],
    correctIndex: 1,
    explanation: 'La faible corrélation entre agences ESG (~0.5 vs ~0.9 pour le crédit) s\'explique par des différences de périmètre, de mesure et de pondération des critères.',
    difficulty: 'medium',
  },
  {
    id: 'esg-q5',
    lessonId: 'esg-4',
    question: 'Comment un analyste intègre-t-il le risque ESG dans un DCF ?',
    options: [
      'En augmentant le chiffre d\'affaires prévisionnel',
      'En ajustant le WACC (prime ESG) et/ou les cash-flows futurs',
      'En réduisant le nombre d\'actions',
      'En changeant la devise d\'analyse',
    ],
    correctIndex: 1,
    explanation: 'L\'intégration ESG dans un DCF passe par l\'ajustement du WACC (prime de risque ESG de 0.5-2%) et/ou l\'ajustement des cash-flows (coût carbone, amendes).',
    difficulty: 'medium',
  },
  {
    id: 'esg-q6',
    lessonId: 'esg-5',
    question: 'Qu\'est-ce que le « greenium » d\'une obligation verte ?',
    options: [
      'La prime de risque supplémentaire payée par l\'émetteur vert',
      'Le spread négatif d\'un green bond vs une obligation classique du même émetteur',
      'Le coût de la certification verte',
      'La taxe environnementale sur les obligations',
    ],
    correctIndex: 1,
    explanation: 'Le greenium est le spread négatif (2-10 bps) d\'un green bond par rapport à une obligation conventionnelle du même émetteur, reflétant la demande excédentaire des investisseurs ESG.',
    difficulty: 'hard',
  },
  {
    id: 'esg-q7',
    lessonId: 'esg-7',
    question: 'Quelle est la principale différence entre un green bond et un sustainability-linked loan (SLL) ?',
    options: [
      'Le green bond a un taux plus élevé',
      'Le SLL ne contraint pas l\'utilisation des fonds, contrairement au green bond',
      'Le green bond ne nécessite pas de reporting',
      'Le SLL est réservé aux États',
    ],
    correctIndex: 1,
    explanation: 'Le green bond impose l\'utilisation des fonds pour des projets verts (use of proceeds). Le SLL ne contraint pas l\'usage des fonds mais lie le taux à l\'atteinte d\'objectifs ESG (KPI/SPT).',
    difficulty: 'medium',
  },
  {
    id: 'esg-q8',
    lessonId: 'esg-8',
    question: 'Combien d\'objectifs environnementaux la taxonomie européenne définit-elle ?',
    options: ['3', '4', '6', '8'],
    correctIndex: 2,
    explanation: 'La taxonomie européenne définit 6 objectifs : atténuation du changement climatique, adaptation, eau, économie circulaire, pollution et biodiversité.',
    difficulty: 'easy',
  },
  {
    id: 'esg-q9',
    lessonId: 'esg-8',
    question: 'Que signifie le principe DNSH dans la taxonomie européenne ?',
    options: [
      'Do Not Share Holdings',
      'Do No Significant Harm',
      'Disclose Non-Standard Holdings',
      'Determine Net Sustainability Horizon',
    ],
    correctIndex: 1,
    explanation: 'DNSH (Do No Significant Harm) : pour être alignée taxonomie, une activité ne doit pas causer de préjudice significatif aux cinq autres objectifs environnementaux.',
    difficulty: 'easy',
  },
  {
    id: 'esg-q10',
    lessonId: 'esg-9',
    question: 'Sous SFDR, qu\'est-ce qu\'un fonds Article 9 ?',
    options: [
      'Un fonds sans aucune caractéristique ESG',
      'Un fonds qui promeut des caractéristiques ESG',
      'Un fonds qui a un objectif d\'investissement durable mesurable',
      'Un fonds qui exclut les armes controversées',
    ],
    correctIndex: 2,
    explanation: 'Un fonds Article 9 (« vert foncé ») a un objectif d\'investissement durable explicite et mesurable. C\'est le niveau le plus exigeant du classement SFDR.',
    difficulty: 'medium',
  },
  {
    id: 'esg-q11',
    lessonId: 'esg-10',
    question: 'Quel principe distingue la CSRD de l\'ancienne NFRD ?',
    options: [
      'Le reporting uniquement financier',
      'La double matérialité (impact financier ET impact sur la société)',
      'Le reporting uniquement environnemental',
      'L\'absence d\'audit obligatoire',
    ],
    correctIndex: 1,
    explanation: 'La CSRD impose la double matérialité : reporter à la fois sur les risques ESG qui affectent la performance financière ET sur les impacts de l\'entreprise sur l\'environnement et la société.',
    difficulty: 'medium',
  },
  {
    id: 'esg-q12',
    lessonId: 'esg-11',
    question: 'Quels sont les trois critères distinctifs de l\'investissement d\'impact ?',
    options: [
      'Rendement, risque, liquidité',
      'Intentionnalité, additionnalité, mesurabilité',
      'Exclusion, sélection, engagement',
      'Performance, diversification, transparence',
    ],
    correctIndex: 1,
    explanation: 'L\'impact investing se distingue par l\'intentionnalité (objectif explicite), l\'additionnalité (capital nécessaire au projet) et la mesurabilité (indicateurs d\'impact quantifiés).',
    difficulty: 'hard',
  },
  {
    id: 'esg-q13',
    lessonId: 'esg-13',
    question: 'Quels sont les deux types de risques climatiques identifiés par la TCFD ?',
    options: [
      'Risques opérationnels et risques financiers',
      'Risques physiques et risques de transition',
      'Risques de marché et risques de crédit',
      'Risques réglementaires et risques technologiques',
    ],
    correctIndex: 1,
    explanation: 'La TCFD distingue les risques physiques (événements climatiques extrêmes) et les risques de transition (réglementation carbone, obsolescence technologique, changement de comportement).',
    difficulty: 'easy',
  },
  {
    id: 'esg-q14',
    lessonId: 'esg-14',
    question: 'Dans un fonds ESG best-in-class, que mesure l\'intensité carbone du portefeuille ?',
    options: [
      'Les émissions totales en tonnes de CO₂',
      'Les émissions pondérées par le chiffre d\'affaires (tCO₂/M€ CA)',
      'Le nombre d\'entreprises du secteur énergie',
      'Le pourcentage d\'énergie renouvelable utilisée',
    ],
    correctIndex: 1,
    explanation: 'L\'intensité carbone du portefeuille = Σ(poids_i × émissions_i / CA_i), exprimée en tCO₂ par million d\'euros de chiffre d\'affaires. Elle permet de comparer des portefeuilles de taille différente.',
    difficulty: 'hard',
  },
];
