// ──────────────────────────────────────────────
//  FINA - Réglementation : Quiz
// ──────────────────────────────────────────────

import type { QuizQuestion } from '../types';

export const regulationQuiz: QuizQuestion[] = [
  {
    id: 'reg-q1',
    lessonId: 'reg-1',
    question: 'Quel est le principe fondamental de la transformation bancaire ?',
    options: [
      'Acheter des actions pour les revendre',
      'Emprunter à court terme pour prêter à long terme',
      'Convertir des devises étrangères',
      'Transformer des dépôts en obligations',
    ],
    correctIndex: 1,
    explanation: 'La transformation de maturité est le cœur du métier bancaire : collecter des dépôts à court terme pour financer des crédits à long terme.',
    difficulty: 'easy',
  },
  {
    id: 'reg-q2',
    lessonId: 'reg-2',
    question: 'Quel est le mandat principal de la BCE ?',
    options: [
      'Le plein emploi en zone euro',
      'La stabilité des prix (cible d\'inflation à 2%)',
      'La croissance du PIB',
      'L\'équilibre budgétaire des États membres',
    ],
    correctIndex: 1,
    explanation: 'Le mandat principal de la BCE est la stabilité des prix, avec une cible d\'inflation de 2% à moyen terme. Contrairement à la Fed, elle n\'a pas de mandat de plein emploi.',
    difficulty: 'easy',
  },
  {
    id: 'reg-q3',
    lessonId: 'reg-3',
    question: 'Quel est le ratio minimum imposé par Bâle I (ratio Cooke) ?',
    options: [
      'Fonds propres ≥ 4% des actifs totaux',
      'Fonds propres ≥ 8% des actifs pondérés par le risque',
      'Fonds propres ≥ 10% des dépôts',
      'Fonds propres ≥ 6% du chiffre d\'affaires',
    ],
    correctIndex: 1,
    explanation: 'Le ratio Cooke (Bâle I) exige que les fonds propres (Tier 1 + Tier 2) représentent au moins 8% des actifs pondérés par les risques de crédit.',
    difficulty: 'easy',
  },
  {
    id: 'reg-q4',
    lessonId: 'reg-4',
    question: 'Quel risque a été ajouté au pilier 1 de Bâle II par rapport à Bâle I ?',
    options: [
      'Le risque de liquidité',
      'Le risque de réputation',
      'Le risque opérationnel',
      'Le risque climatique',
    ],
    correctIndex: 2,
    explanation: 'Bâle II a ajouté le risque opérationnel au pilier 1 (en plus du risque de crédit et du risque de marché déjà présents dans l\'amendement de 1996 à Bâle I).',
    difficulty: 'medium',
  },
  {
    id: 'reg-q5',
    lessonId: 'reg-4',
    question: 'En approche IRB (Bâle II), quels paramètres la banque estime-t-elle pour calculer les RWA de crédit ?',
    options: [
      'LTV, DSCR, ICR',
      'PD, LGD, EAD, Maturité',
      'VaR, CVaR, Expected Shortfall',
      'CET1, AT1, Tier 2',
    ],
    correctIndex: 1,
    explanation: 'En approche IRB, la banque estime la Probabilité de Défaut (PD), la Perte en cas de Défaut (LGD), l\'Exposition au Défaut (EAD) et la Maturité.',
    difficulty: 'medium',
  },
  {
    id: 'reg-q6',
    lessonId: 'reg-5',
    question: 'Quel est le minimum réglementaire de CET1 sous Bâle III (hors coussins) ?',
    options: ['3%', '4.5%', '6%', '8%'],
    correctIndex: 1,
    explanation: 'Le CET1 minimum est de 4.5% des RWA sous Bâle III. Avec les coussins (conservation 2.5%, contracyclique, G-SIB), le minimum effectif est souvent > 9-10%.',
    difficulty: 'easy',
  },
  {
    id: 'reg-q7',
    lessonId: 'reg-6',
    question: 'Que mesure le LCR (Liquidity Coverage Ratio) ?',
    options: [
      'La capacité à résister à un an de stress',
      'La capacité à résister à 30 jours de stress de liquidité',
      'Le ratio de fonds propres sur les dépôts',
      'Le rendement des actifs liquides',
    ],
    correctIndex: 1,
    explanation: 'Le LCR mesure la capacité de la banque à résister à 30 jours de stress de liquidité : HQLA / Sorties nettes 30 jours ≥ 100%.',
    difficulty: 'easy',
  },
  {
    id: 'reg-q8',
    lessonId: 'reg-7',
    question: 'Quel est le minimum du leverage ratio sous Bâle III ?',
    options: ['1%', '2%', '3%', '5%'],
    correctIndex: 2,
    explanation: 'Le leverage ratio minimum est de 3% (Tier 1 / Exposition totale). Les G-SIBs ont un supplément de 50% de leur coussin G-SIB.',
    difficulty: 'medium',
  },
  {
    id: 'reg-q9',
    lessonId: 'reg-8',
    question: 'Quel événement a illustré le mécanisme de bail-in des AT1 en 2023 ?',
    options: [
      'La faillite de Silicon Valley Bank',
      'Le write-down des AT1 de Credit Suisse',
      'La recapitalisation de Deutsche Bank',
      'Le sauvetage de Monte dei Paschi',
    ],
    correctIndex: 1,
    explanation: 'En mars 2023, les 16 Md CHF d\'AT1 de Credit Suisse ont été annulés (write-down à zéro) lors de sa reprise par UBS, illustrant le mécanisme de bail-in.',
    difficulty: 'medium',
  },
  {
    id: 'reg-q10',
    lessonId: 'reg-9',
    question: 'Quel est l\'objectif principal d\'un stress test bancaire ?',
    options: [
      'Maximiser la rentabilité du portefeuille',
      'Évaluer la résistance de la banque à un scénario macroéconomique adverse',
      'Déterminer les bonus des dirigeants',
      'Calculer les dividendes distribuables',
    ],
    correctIndex: 1,
    explanation: 'Les stress tests simulent un choc macroéconomique sévère sur 3 ans pour vérifier que les ratios de capital de la banque restent au-dessus des minimums.',
    difficulty: 'easy',
  },
  {
    id: 'reg-q11',
    lessonId: 'reg-10',
    question: 'Sous MiFID II, quel test doit être réalisé avant de conseiller un produit financier à un client retail ?',
    options: [
      'Test de résistance',
      'Test de stress',
      'Test d\'adéquation (suitability)',
      'Test de liquidité',
    ],
    correctIndex: 2,
    explanation: 'Le test d\'adéquation (suitability) vérifie que le produit correspond aux objectifs, à l\'horizon et à la tolérance au risque du client retail.',
    difficulty: 'easy',
  },
  {
    id: 'reg-q12',
    lessonId: 'reg-13',
    question: 'Que impose EMIR pour les dérivés OTC standardisés ?',
    options: [
      'L\'interdiction pure et simple',
      'La compensation centrale obligatoire via une CCP',
      'Un capital réglementaire de 50%',
      'La conversion en actions',
    ],
    correctIndex: 1,
    explanation: 'EMIR impose la compensation centrale obligatoire pour les dérivés OTC standardisés (IRS vanille, CDS index) via des CCP comme LCH ou Eurex.',
    difficulty: 'medium',
  },
  {
    id: 'reg-q13',
    lessonId: 'reg-14',
    question: 'Qu\'est-ce qu\'un UBO en matière de KYC ?',
    options: [
      'United Banking Organization',
      'Ultimate Beneficial Owner (bénéficiaire effectif)',
      'Universal Business Obligation',
      'Unified Bank Oversight',
    ],
    correctIndex: 1,
    explanation: 'L\'UBO (Ultimate Beneficial Owner) est le bénéficiaire effectif, la personne physique qui détient ou contrôle in fine le client. Son identification est obligatoire dans le processus KYC.',
    difficulty: 'medium',
  },
  {
    id: 'reg-q14',
    lessonId: 'reg-15',
    question: 'Sous MAR, qu\'est-ce qu\'une information privilégiée ?',
    options: [
      'Toute information publiée dans la presse financière',
      'Une information précise, non publique, susceptible d\'influencer le cours',
      'Le rapport annuel de l\'entreprise',
      'Les recommandations des analystes sell-side',
    ],
    correctIndex: 1,
    explanation: 'Une information privilégiée est précise, non publique et susceptible d\'influencer significativement le cours de l\'instrument financier.',
    difficulty: 'medium',
  },
  {
    id: 'reg-q15',
    lessonId: 'reg-16',
    question: 'Quelle a été la plus grosse amende bancaire pour violation des sanctions ?',
    options: [
      'HSBC : 1.9 Md$ (2012)',
      'Standard Chartered : 1.1 Md$ (2019)',
      'BNP Paribas : 8.9 Md$ (2014)',
      'Deutsche Bank : 7.2 Md$ (2017)',
    ],
    correctIndex: 2,
    explanation: 'BNP Paribas a payé 8.9 Md$ en 2014 pour avoir traité des transactions en dollars avec le Soudan, Cuba et l\'Iran en violation des sanctions OFAC.',
    difficulty: 'hard',
  },
  {
    id: 'reg-q16',
    lessonId: 'reg-17',
    question: 'Une banque a un CET1 de 45 Md€ et des RWA de 350 Md€. Quel est son ratio CET1 ?',
    options: ['10.0%', '12.86%', '14.5%', '7.78%'],
    correctIndex: 1,
    explanation: 'CET1 ratio = 45 / 350 = 12.86%. Ce ratio est confortable, au-dessus du minimum effectif pour une G-SIB (~9.5-10%).',
    difficulty: 'easy',
  },
  {
    id: 'reg-q17',
    lessonId: 'reg-6',
    question: 'Quel ratio vérifie l\'adéquation du financement stable sur un horizon d\'un an ?',
    options: ['LCR', 'NSFR', 'Leverage ratio', 'CET1 ratio'],
    correctIndex: 1,
    explanation: 'Le NSFR (Net Stable Funding Ratio) vérifie que le financement stable disponible (ASF) couvre le financement stable requis (RSF) sur un horizon d\'un an.',
    difficulty: 'medium',
  },
  {
    id: 'reg-q18',
    lessonId: 'reg-18',
    question: 'Quelle est la hiérarchie d\'absorption des pertes en cas de résolution bancaire (bail-in) ?',
    options: [
      'Dépôts → Senior → AT1 → Actions',
      'Actions → AT1 → Tier 2 → Senior non-preferred → Senior preferred',
      'Senior → Tier 2 → AT1 → Actions',
      'AT1 → Actions → Tier 2 → Senior',
    ],
    correctIndex: 1,
    explanation: 'Les pertes sont absorbées par ordre de subordination : actionnaires (premiers à perdre), AT1, Tier 2, dette senior non-preferred, puis senior preferred. Les dépôts garantis sont protégés.',
    difficulty: 'hard',
  },
];
